octokit/octokit.net

- Octokit.Tests/Clients/TagsClientTests.cs
- Octokit.Tests/Http/JsonHttpPipelineTests.cs
- Octokit.Tests/Models/CommitTests.cs
- Octokit/Models/Response/GitHubCommit.cs
- Octokit/Models/Response/GitHubCommitFile.cs
- Octokit/Models/Response/GitHubCommitStats.cs
- Octokit/Models/Response/Signature.cs
- Octokit/Octokit-Mono.csproj
- Octokit/Octokit-MonoAndroid.csproj
- Octokit/Octokit-Monotouch.csproj
- Octokit/Octokit-Portable.csproj
- Octokit/Octokit-netcore45.csproj
- Octokit/Octokit.csproj
Added `Stats` and `Patch` fields to `GitHubCommit` and `GitHubCommitFile`, repectively. Also, modified the type for the `Signature.Date` field since it was `DateTime` and everywhere else in the project uses `DateTimeOffset`. 
PS. My stupid Mac or stupid Xamarin instance won't build the test projects for some reason I have yet to run the tests at all so don't be surprised if I fail the continous integration build :sunglasses:
> Added missing fields to GitHubCommit

- .gitignore
- Octokit.Reactive/Clients/IObservableCommitStatusClient.cs
- Octokit.Reactive/Clients/ObservableCommitStatusClient.cs
- Octokit.Tests.Integration/Clients/CommitStatusClientTests.cs
- Octokit.Tests/Clients/CommitStatusClientTests.cs
- Octokit/Clients/CommitStatusClient.cs
- Octokit/Clients/ICommitStatusClient.cs
- Octokit/Helpers/ApiUrls.cs
- Octokit/Models/Response/CombinedCommitStatus.cs
- Octokit/Octokit-Mono.csproj
- Octokit/Octokit-MonoAndroid.csproj
- Octokit/Octokit-Monotouch.csproj
- Octokit/Octokit-Portable.csproj
- Octokit/Octokit-netcore45.csproj
- Octokit/Octokit.csproj
Added the new endpoint for [combined commit statuses](https://developer.github.com/v3/repos/statuses/#get-the-combined-status-for-a-specific-ref), replaced a legacy URL and added some XML docs :lipstick: 
Tell me if you want the commits squashed after a review :smile:
> Overhaul of status API client

- .gitignore
The roslyn compiler creates a folder name [solutionname].sln.ide next to the solution file.  This folder is used for storing temporary files and should not be committed to source control.
> Adds roslyn temporary files to the gitignore file.

- Octokit.Tests/SimpleJsonSerializerTests.cs
- Octokit/Models/Response/TreeResponse.cs
See https://developer.github.com/v3/git/trees/#get-a-tree for details on the truncated attribute.
I am operating under the assumption that if a property is missing from the json object then the property will be set to its default value (false in this case).
I'm not sure how to test this.  If someone can point me at some existing tests that validate the json deserializer behaves correctly in certain scenarios (like when the property is missing) I can add some test coverage.  Though, if using an off-the-shelf deserializer then perhaps that wouldn't be testing anything meaningful in the library.
> Adds truncated attribute to TreeResponse.

- Octokit.Reactive/Clients/IObservableTreesClient.cs
- Octokit.Reactive/Clients/ObservableTreesClient.cs
- Octokit.Tests/Clients/TreesClientTests.cs
- Octokit.Tests/Reactive/ObservableTreesClientTests.cs
- Octokit/Clients/ITreesClient.cs
- Octokit/Clients/TreesClient.cs
- Octokit/Helpers/ApiUrls.cs
Initially I implemented this as an optional boolean parameter on `TreeClient.Get` that would append `?recursive=1` to the end of the URI.  Unfortunately, code analysis complained about that (optional parameters) so I went with a set of new overloads instead.
Let me know if a different approach is preferred for adding optional query string parameters to API methods or if this is the preferred solution.  The problem with this solution is that it doesn't scale out well with multiple optional parameters.
> Adds TreeClient.GetRecursive method.

- Octokit.Tests.Integration/Properties/AssemblyInfo.cs
This is a fix that @ammeep found a few days ago for the VS test runner parallelizing all tests by default.
I've applied this to the integration tests only, as everything else has been fine. 
And here's what it looks like running non-integration tests from VS2013:
```
------ Run test started ------
[xUnit.net 00:00:00.0000040] Execution started
[xUnit.net 00:00:00.0022132] Settings: MaxParallelThreads = 0, NameDisplay = Short, ParallelizeAssemblies = False, ParallelizeTestCollections = True, ShutdownAfterRun = False
[xUnit.net 00:00:00.0053948] Discovery started
[xUnit.net 00:00:00.1806443] Discovery starting: Octokit.Tests.Conventions.dll
[xUnit.net 00:00:03.3871694] Discovery finished: Octokit.Tests.Conventions.dll (272 tests)
[xUnit.net 00:00:03.6478859] Discovery starting: …
```
> less parallelism, less upset

- Octokit/Models/Request/NewRepository.cs
Not sure how those 's' characters got there, but they would show up in the VS tooltip.
> Removes doc comment typos.

- Octokit.Reactive/Clients/IObservableGistCommentsClient.cs
- Octokit.Reactive/Clients/ObservableGistCommentsClient.cs
- Octokit.Tests/Clients/GistCommentsClientTests.cs
- Octokit/Clients/GistCommentsClient.cs
- Octokit/Clients/IGistCommentsClient.cs
- Octokit/Helpers/ApiUrls.cs
Gists & their comments all have string Ids. Changed the GistCommentClient to take a string instead of an int.
e.g: https://api.github.com/gists/edaab9be9eaa9bf1ee5f/comments
> Changed Gist Comment Client Id param from int to string

- Octokit.Tests/Clients/RepositoriesClientTests.cs
Rename test methods. 
**From:**
_RequestsTheCorrectUrlAndReturnsOrganizations()_
_RequestsTheCorrectUrlAndReturnsOrganizations()_
_RequestsTheCorrectUrlAndReturnsOrganizations()_
**To:**
_RequestsTheCorrectUrlAndReturnsRepositories()_
_RequestsTheCorrectUrlAndReturnsRepositories()_
_RequestsTheCorrectUrlAndReturnsRepositories()_
> RepositoriesClientTests - Wrong Method Names #692

- Octokit/Models/Response/EventInfo.cs
Let's use the official spelling of [event types](https://developer.github.com/v3/issues/events/) to avoid blowing up on deserialization of events. 
Fixes https://github.com/octokit/octokit.net/issues/707
> Support the correct spelling of event types

- Octokit.Tests.Integration/Clients/RepositoriesClientTests.cs
- Octokit.Tests.Integration/Clients/UsersClientTests.cs
- Octokit.Tests/Clients/SearchClientTests.cs
- Octokit.Tests/Clients/UsersClientTests.cs
- Octokit/Models/Request/SearchUsersRequest.cs
- Octokit/Models/Response/Account.cs
- Octokit/Models/Response/AccountType.cs
- Octokit/Models/Response/Organization.cs
- Octokit/Models/Response/User.cs
- Octokit/Octokit-Mono.csproj
- Octokit/Octokit-MonoAndroid.csproj
- Octokit/Octokit-Monotouch.csproj
- Octokit/Octokit-Portable.csproj
- Octokit/Octokit-netcore45.csproj
- Octokit/Octokit.csproj
> Added Account.Type support

- Octokit.Tests.Integration/Clients/IssuesClientTests.cs
- Octokit.Tests/Models/IssueTest.cs
- Octokit/Models/Request/IssueUpdate.cs
- Octokit/Models/Request/RepositoryIssueRequest.cs
- Octokit/Models/Response/Issue.cs
- docs/issues.md
- docs/labels.md
- docs/milestones.md
Fixes #715 
When you update an issue, the value in `Labels` is important. From the [docs](https://developer.github.com/v3/issues/#edit-an-issue):
> Labels to associate with this issue. Pass one or more Labels to *replace* the set of Labels on this Issue. Send an empty array (`[ ]`) to clear all Labels from the Issue. 
There's three scenarios we need to support here, and I think this is the best compromise:
How does that feel @thedillonb @haacked?
> actually fix regression with updating issue labels

- Octokit.Tests/SimpleJsonSerializerTests.cs
- Octokit/Http/SimpleJsonSerializer.cs
- Octokit/Models/Response/EventInfo.cs
[Pull request #711](https://github.com/octokit/octokit.net/pull/711) was created under the assumption that the Parameter attribute worked on both serialization and deserialization of json. Unfortunately that turned out not to be the case. It's only supported under serialization. 
Let's try again! :)
> Support the correct spelling of event types, take two.

- Octokit.Reactive/Clients/IObservableRepositoriesClient.cs
- Octokit.Reactive/Clients/ObservableRepositoriesClient.cs
- Octokit.Tests.Integration/Clients/RepositoriesClientTests.cs
- Octokit.Tests/Clients/RepositoriesClientTests.cs
- Octokit/Clients/IRepositoriesClient.cs
- Octokit/Clients/RepositoriesClient.cs
- Octokit/Helpers/ApiUrls.cs
Added the functionality and tests. Not sure if it can be used as is though.
The request takes to long to return. About 10 minutes for about 65K repositories in my tests.
Maybe this could be done passing the pagination ability to the caller of the method.
> Fix for issue #686 List all public repositories

- README.md
AFAIK qed isn't used in this repo anymore.
I also added a link to the AppVeyor account to the build badge which is much more useful than getting the image.
> Replace qed with AppVeyor in readme

- Octokit.Reactive/Clients/IObservableRepositoriesClient.cs
- Octokit.Reactive/Clients/ObservableRepositoriesClient.cs
- Octokit.Tests.Integration/Clients/RepositoriesClientTests.cs
- Octokit/Clients/IRepositoriesClient.cs
- Octokit/Clients/RepositoriesClient.cs
> Nuke GetReadme and GetReadmeHtml

- Octokit.Tests.Integration/Clients/AssigneesClientTests.cs
- Octokit.Tests.Integration/Clients/BlobClientTests.cs
- Octokit.Tests.Integration/Clients/BranchesClientTests.cs
- Octokit.Tests.Integration/Clients/CommitStatusClientTests.cs
- Octokit.Tests.Integration/Clients/CommitsClientTests.cs
- Octokit.Tests.Integration/Clients/DeploymentStatusClientTests.cs
- Octokit.Tests.Integration/Clients/DeploymentsClientTests.cs
- Octokit.Tests.Integration/Clients/IssuesClientTests.cs
- Octokit.Tests.Integration/Clients/IssuesEventsClientTests.cs
- Octokit.Tests.Integration/Clients/IssuesLabelsClientTests.cs
- Octokit.Tests.Integration/Clients/MergingClientTests.cs
- Octokit.Tests.Integration/Clients/MilestonesClientTests.cs
- Octokit.Tests.Integration/Clients/PullRequestReviewCommentsClientTests.cs
- Octokit.Tests.Integration/Clients/PullRequestsClientTests.cs
- Octokit.Tests.Integration/Clients/ReferencesClientTests.cs
- Octokit.Tests.Integration/Clients/ReleasesClientTests.cs
- Octokit.Tests.Integration/Clients/RepositoriesClientTests.cs
- Octokit.Tests.Integration/Clients/RepositoryCommitsClientTests.cs
- Octokit.Tests.Integration/Clients/RepositoryContentsClientTests.cs
- Octokit.Tests.Integration/Clients/RepositoryDeployKeysClientTests.cs
- Octokit.Tests.Integration/Clients/StatisticsClientTests.cs
- Octokit.Tests.Integration/Clients/TreeClientTests.cs
- Octokit.Tests.Integration/Reactive/ObservableIssuesClientTests.cs
- Octokit.Tests.Integration/Reactive/ObservableRespositoryDeployKeysClientTests.cs
- Octokit.Tests/Clients/RepositoriesClientTests.cs
- Octokit/Clients/RepositoriesClient.cs
- Octokit/Models/Request/NewRepository.cs
I was trying to create a repository and I wasn't sure which parameters were required. Following our philosophy of exposing required parameters in the constructor, I change the `NewRepository` object to take in a repository name and to make that property readonly.
> Repository name is required when creating a repo

- Octokit.Reactive/Clients/IObservableRepositoriesClient.cs
- Octokit.Reactive/Clients/ObservableRepositoriesClient.cs
- Octokit.Tests.Integration/Clients/RepositoriesClientTests.cs
- Octokit.Tests.Integration/Reactive/ObservableRepositoriesClientTests.cs
- Octokit.Tests/Clients/RepositoriesClientTests.cs
- Octokit.Tests/Reactive/ObservableRepositoriesClientTests.cs
- Octokit/Clients/IRepositoriesClient.cs
- Octokit/Clients/RepositoriesClient.cs
- Octokit/Models/Request/PublicRepositoryRequest.cs
- Octokit/Octokit-Mono.csproj
- Octokit/Octokit-MonoAndroid.csproj
- Octokit/Octokit-Monotouch.csproj
- Octokit/Octokit-Portable.csproj
- Octokit/Octokit-netcore45.csproj
- Octokit/Octokit.csproj
> Add `since` parameter for public repositories

- Octokit/Clients/AuthorizationsClient.cs
- Octokit/Exceptions/ApiException.cs
- Octokit/Exceptions/TwoFactorAuthorizationException.cs
- Octokit/Exceptions/TwoFactorChallengeFailedException.cs
- Octokit/Exceptions/TwoFactorRequiredException.cs
- Octokit/Http/Connection.cs
- Octokit/Octokit-Mono.csproj
- Octokit/Octokit-MonoAndroid.csproj
- Octokit/Octokit-Monotouch.csproj
- Octokit/Octokit-Portable.csproj
- Octokit/Octokit-netcore45.csproj
- Octokit/Octokit.csproj
I was running into an issue where i wanted more information from the
TwoFactorChallengeFailedException. It turns out, the exception could
easily provide both the TwoFactorType AND the authentication code
provided. So :boom:!
> Add more info to TwoFactorChallengeFailedException

- Octokit/Http/HttpClientAdapter.cs
> Allow to download zip-attachments

- Octokit.Reactive/Clients/IObservableRepositoriesClient.cs
- Octokit.Reactive/Clients/ObservableRepositoriesClient.cs
- Octokit.Tests.Integration/Clients/RepositoriesClientTests.cs
- Octokit.Tests.Integration/Reactive/ObservableRepositoriesClientTests.cs
- Octokit.Tests/Clients/RepositoriesClientTests.cs
- Octokit.Tests/Reactive/ObservableRepositoriesClientTests.cs
- Octokit/Clients/IRepositoriesClient.cs
- Octokit/Clients/RepositoriesClient.cs
- Octokit/Helpers/ApiUrls.cs
As part of shipping 0.10 I disabled `GetAllPublic` because I couldn't get to the bottom of why it was infinite-looping. With a bit of sleep, however, I found a workaround.
As part of generating the complete URL for the request, Octokit will take values in it's request collection and overwrite whatever's in the URL. This is fine for the first request, but it was also kicking in for subsequent requests - and getting stuck.
I'm taking away this nice thing for just this endpoint, and providing just the URL it needs to start things off.
The test is still taking too long, so I've disabled it anyway until I can get a chance to finish off #760.
cc @alfhenrik
> bring back GetAllPublic repositories

- Octokit.Reactive/Clients/IObservableRepositoryContentsClient.cs
- Octokit.Reactive/Clients/ObservableRepositoryContentsClient.cs
- Octokit.Tests.Integration/Clients/RepositoryContentsClientTests.cs
- Octokit.Tests/Clients/RepositoryContentsClientTests.cs
- Octokit/Clients/IRepositoryContentsClient.cs
- Octokit/Clients/RepositoryContentsClient.cs
- Octokit/Helpers/ApiExtensions.cs
- Octokit/Helpers/ApiUrls.cs
- Octokit/Http/ApiConnection.cs
- Octokit/Http/Connection.cs
- Octokit/Http/IApiConnection.cs
- Octokit/Http/IConnection.cs
Partial fix for #748 
- ~~[ ] Get the **actual** content of the archive.... :santa: :gift:~~ Will send a separate PR for this one
> Repository Get Archive Link

- Octokit.Tests.Integration/HttpClientAdapterTests.cs
- Octokit.Tests/Http/HttpClientAdapterTests.cs
- Octokit/GitHubClient.cs
- Octokit/Http/HttpClientAdapter.cs
This is the first step down the path I talked about in #781 - a minor internal change to `HttpClientAdapter` to make it's `HttpClient` reusable
- use a `CancellationToken` based on the specified `IRequest.Timeout` value
- deprecate the `BaseAddress` and `Timeout` values when constructing the `HttpClient`
- update impacted tests
> deprecate httpclient timeout in favour of cancellation token

- Octokit.Tests.Integration/Clients/PullRequestsClientTests.cs
- Octokit.Tests/Clients/PullRequestsClientTests.cs
- Octokit.Tests/Reactive/ObservablePullRequestsClientTests.cs
- Octokit/Models/Request/MergePullRequest.cs
> Add SHA and make message optional for pull request merge

- Octokit.Reactive/Clients/IObservableRepositoryContentsClient.cs
- Octokit.Reactive/Clients/ObservableRepositoryContentsClient.cs
- Octokit.Tests.Integration/Clients/RepositoryContentsClientTests.cs
- Octokit.Tests/Http/RedirectHandlerTests.cs
- Octokit/Clients/IRepositoryContentsClient.cs
- Octokit/Clients/RepositoryContentsClient.cs
- Octokit/Http/Connection.cs
- Octokit/Http/HttpClientAdapter.cs
- Octokit/Http/IRequest.cs
- Octokit/Http/Request.cs
This was started in #765 but due to #808 we either need to:
- implement a workaround for users to opt-out of redirects, leave the feature incomplete
- just finish the feature, make retrieving the link unnecessary
I've favoured the latter, and marked the existing `GetArchiveLink` methods as obsolete.
Doing this as a separate PR into the redirect PR so we can discuss whether users want to access the link without initiating the download.
Fixes #748 
cc @alfhenrik
> finish support for downloading the code archive

- Octokit.Reactive/Clients/IObservableTeamsClient.cs
- Octokit.Reactive/Clients/ObservableTeamsClient.cs
- Octokit.Tests.Integration/Clients/TeamsClientTests.cs
- Octokit.Tests/Clients/TeamsClientTests.cs
- Octokit/Clients/ITeamsClient.cs
- Octokit/Clients/TeamsClient.cs
- Octokit/Helpers/ApiUrls.cs
- Octokit/Models/Response/TeamMembership.cs
- Octokit/Octokit-Mono.csproj
- Octokit/Octokit-MonoAndroid.csproj
- Octokit/Octokit-Monotouch.csproj
- Octokit/Octokit-Portable.csproj
- Octokit/Octokit-netcore45.csproj
- Octokit/Octokit.csproj
Thanks to @phantomtypist for starting this off.
> adding missing organization teams APIs

- Octokit.Tests.Integration/Clients/SearchClientTests.cs
- Octokit.Tests/Clients/SearchClientTests.cs
- Octokit/Models/Request/SearchCodeRequest.cs
- Octokit/Models/Request/SearchIssuesRequest.cs
I didn't remove the validation, since it still gives some value in validating the owner and repo names separately.
> Changed repos to a specialized collection

- Octokit.Reactive/Octokit.Reactive-MonoAndroid.csproj
- Octokit.Reactive/Octokit.Reactive.csproj
- Octokit.Tests.Conventions/Octokit.Tests.Conventions.csproj
- Octokit.Tests.Integration/Octokit.Tests.Integration.csproj
- Octokit.Tests/OctoKit.Tests-NetCore45.csproj
- Octokit.Tests/Octokit.Tests-Portable.csproj
- Octokit.Tests/Octokit.Tests.csproj
- Octokit/Octokit-Mono.csproj
- Octokit/Octokit-Portable.csproj
- Octokit/Octokit-netcore45.csproj
- Octokit/Octokit.csproj
- clean-up-after-tests/clean-up-after-tests.csproj
Looks like the tool I wrote to add `<LangVersion>5<LangVersion />` to all *.csproj's had a bug that added them to the `Debug` section, not the global one. This has been fixed now :smile:
> Second take on LangVersion

- Octokit.Reactive/Octokit.Reactive.csproj
- Octokit/Octokit-Portable.csproj
- Octokit/Octokit-netcore45.csproj
- Octokit/Octokit.csproj
- appveyor.yml
We were bumped up to MSBuild v14 a few days ago, which highlighted [this bug](https://connect.microsoft.com/VisualStudio/feedback/details/1446883/code-analysis-autofac-bug) with PCL projects with Code Analysis enabled.
For now, I'm going to mute this - the other projects run Code Analysis, so I'm happy what we lose here is covered elsewhere.
- ~~[ ] restore xml-doc generation~~ https://github.com/octokit/octokit.net/issues/847
> get CI builds back to a happy place

- Octokit.Reactive/Clients/IObservableRepositoryContentsClient.cs
- Octokit.Reactive/Clients/ObservableRepositoryContentsClient.cs
- Octokit.Tests/Clients/RepositoryContentsClientTests.cs
- Octokit/Clients/IRepositoryContentsClient.cs
- Octokit/Clients/RepositoryContentsClient.cs
- Octokit/Helpers/ApiUrls.cs
as far as i could tell, it was impossible to specify the ref parameter on the get contents api method https://developer.github.com/v3/repos/contents/#get-content
> added support for ref value in get contents api

- .gitignore
- Octokit.Reactive/Octokit.Reactive.csproj
- Octokit.Tests.Integration/Clients/SearchClientTests.cs
- Octokit.Tests/Clients/SearchClientTests.cs
- Octokit/Exceptions/RepositoryFormatException.cs
- Octokit/Helpers/StringExtensions.cs
- Octokit/Models/Request/SearchCodeRequest.cs
- Octokit/Models/Request/SearchIssuesRequest.cs
- Octokit/Octokit-Mono.csproj
- Octokit/Octokit-MonoAndroid.csproj
- Octokit/Octokit-Monotouch.csproj
- Octokit/Octokit-Portable.csproj
- Octokit/Octokit-netcore45.csproj
- Octokit/Octokit.csproj
- build.cmd
- build.fsx
- docs/search.md
Fixes #834 
This is a breaking API change to support being able to search across repositories. We currently have an `ctor` overload that accepts an `owner` and `name` for the repository:
```csharp
var request = new SearchIssuesRequest("windows", "aspnet", "dnx");
```
The change here is adding a public property `Repos` which accepts a collection of `owner/name` strings (i've added some validation to ensure these are formatted correctly for the server):
```csharp
var request = new SearchIssuesRequest("windows");
request.Repos = new Collection<string> {
"aspnet/dnx",
"aspnet/dnvm"
};
```
This replaces the old `Repo` property, which was constrained to one string:
```csharp
var request = new SearchIssuesRequest("windows");
request.Repo = "aspnet/dnx";
```
Rather than carry around both `Repo` …
> search across multiple repositories

- Octokit.Tests/Clients/TeamsClientTests.cs
- Octokit.Tests/Http/ConnectionTests.cs
- Octokit/Clients/TeamsClient.cs
- Octokit/Http/ApiConnection.cs
- Octokit/Http/RequestBody.cs
- Octokit/Octokit-Mono.csproj
- Octokit/Octokit-MonoAndroid.csproj
- Octokit/Octokit-Monotouch.csproj
- Octokit/Octokit-Portable.csproj
- Octokit/Octokit-netcore45.csproj
- Octokit/Octokit.csproj
While exploring some organizational automation with `octokit.net` I discovered that the `TeamClient.AddMembership(..)` call passes a `null` value into a parameter of `ApiConnection.Put(..)` that fails on an `Octokit.Ensure.ArgumentNotNull(..)` call.
The GitHub API 3.0 Team docs state that the correct way to call the _Add Team Member_ endpoint is to essentially pass an empty body:
> Note that you’ll need to set Content-Length to zero when calling out to this endpoint. For more information, see “HTTP verbs.”
> -  [Add Team Member](https://developer.github.com/v3/orgs/teams/#add-team-member) API docs
My proposed fix (that I will submit shortly in this PR) is to have `ApiConnection.Put(..)` check for a `null` body and respond by setting the `Content-Length` header to zero as instructed, if …
> fix the TeamClient.AddMembership(..) call

- Octokit.Tests.Integration/Clients/RepositoryCommitsClientTests.cs
- Octokit/Models/Response/GitHubCommitFile.cs
This PreviousFileName property is returned from the GitHub API when a file was modified. Check https://api.github.com/repos/octokit/octokit.net/commits/997e955f for an example of returning a commit containing file renames. 
Let me know what you think about the change and if there are any modifications I should make related to it.
> Added PreviousFileName property to GitHubCommitFile

- Octokit.Reactive/IObservableGitHubClient.cs
- Octokit.Reactive/ObservableGitHubClient.cs
- Octokit.Tests.Integration/Clients/GitHubClientTests.cs
- Octokit.Tests.Integration/Helper.cs
- Octokit.Tests.Integration/Helpers/PersonalAccessTokenTestAttribute.cs
- Octokit.Tests.Integration/Octokit.Tests.Integration.csproj
- Octokit.Tests/GitHubClientTests.cs
- Octokit.Tests/Http/ApiInfoTests.cs
- Octokit.Tests/Http/ConnectionTests.cs
- Octokit.Tests/Http/RateLimitTests.cs
- Octokit.Tests/Octokit.Tests.csproj
- Octokit/GitHubClient.cs
- Octokit/Helpers/CollectionExtensions.cs
- Octokit/Http/ApiInfo.cs
- Octokit/Http/Connection.cs
- Octokit/Http/HttpClientAdapter.cs
- Octokit/Http/IApiInfo.cs
- Octokit/Http/IApiInfoProvider.cs
- Octokit/Http/IConnection.cs
- Octokit/Http/IHttpClient.cs
- Octokit/Http/RateLimit.cs
- Octokit/IGitHubClient.cs
- Octokit/Octokit-Mono.csproj
- Octokit/Octokit-MonoAndroid.csproj
- Octokit/Octokit-Monotouch.csproj
- Octokit/Octokit-Portable.csproj
- Octokit/Octokit-netcore45.csproj
- Octokit/Octokit.csproj
As discussed in issue #504 
Allows the user to get the contents of the last ApiInfo (so last Api call).  Provided as a property of GitHubClient which calls a property of Connection then a property of HttpClientAdapter.
The most obvious use for it is to check the current rate limit without making a separate API call.
Two concerns for me:
* Can't put a test in for the HttpClientAdapter.  The underlying HttpClient is concrete and the send method is not virtual so can be substituted.  Could abstract the HttpClient (interface and wrapper) - this would help to put more testing into for the HttpClientAdapter (currently quite light).
* Must be a better design than having to implement a property through every layer
Thanks
> Access to the last ApiInfo object

- Octokit.Tests/Clients/AuthorizationsClientTests.cs
- Octokit/Clients/AuthorizationsClient.cs
- Octokit/Helpers/ApiUrls.Authorizations.cs
Octokit currently uses an undocumented endpoint for creating app authorizations.
```
PUT /authorizations/clients/:client_id/:fingerprint
```
This makes Octokit send the fingerprint as part of the URL which only works as long as the fingerprint doesn't contain any characters that has special meaning in urls (most notably `/`). Seeing how fingerprints are an opaque string we can't expect them not to contain reserved characters.
This PR switches the endpoint to the [documented one](https://developer.github.com/v3/oauth_authorizations/#get-or-create-an-authorization-for-a-specific-app) which accepts the fingerprint as part of the JSON body where we can use any characters we want.
cc @Haacked @shiftkey
> Use non-deprecated auth endpoint 

- Octokit.Tests/Clients/IssuesClientTests.cs
- Octokit/Models/Response/Issue.cs
This fix surfaces the comments URL in the Issue response object. #883
> Fixes for the comments URL not surfaced in the issue response

- Octokit.Tests.Integration/Clients/SearchClientTests.cs
- Octokit.Tests/Clients/SearchClientTests.cs
- Octokit/Models/Request/SearchCodeRequest.cs
I couldn't find a helpful `FileName` property for code search (see https://help.github.com/articles/searching-code/#search-by-filename) , so I added it!
> add filename for code search

- Octokit.Tests.Conventions/ModelTests.cs
- Octokit.Tests.Conventions/SyncObservableClients.cs
- Octokit.Tests.Integration/Clients/StatisticsClientTests.cs
- Octokit.Tests/Clients/StatisticsClientTests.cs
- Octokit.Tests/Helpers/UnixTimestampExtensionsTests.cs
- Octokit.Tests/Http/ApiConnectionTests.cs
- Octokit.Tests/OctoKit.Tests-NetCore45.csproj
- Octokit.Tests/Octokit.Tests-Portable.csproj
- Octokit.Tests/Octokit.Tests.csproj
- Octokit/Clients/IStatisticsClient.cs
- Octokit/Clients/StatisticsClient.cs
- Octokit/Helpers/UnixTimeStampExtensions.cs
- Octokit/Http/ApiConnection.cs
- Octokit/Http/IApiConnection.cs
Fixes #836
If we get a 204 No Content response to GetQueuedContent, we should return an empty collection rather than throw an exception.
> Handle empty content better

- Octokit.Reactive/Octokit.Reactive-MonoAndroid.csproj
- Octokit/Octokit-MonoAndroid.csproj
The mono android projects were referencing to files that were missing which was causing the build to fail. This is similar to #888
> Fixes for missing files in the Mono-Android project 

- Octokit.Tests/Helpers/StringExtensionsTests.cs
- Octokit/Helpers/StringExtensions.cs
Fix for Upload to Github releases stopped working #894. The `ExpandUriTemplate` could handle only one parameter which is the bug.
> Fix for Upload to Github releases stopped working #894

- Octokit.Tests/Http/ReadOnlyPagedCollectionTests.cs
- Octokit.Tests/OctoKit.Tests-NetCore45.csproj
- Octokit.Tests/Octokit.Tests-Portable.csproj
- Octokit.Tests/Octokit.Tests.csproj
- Octokit/Http/ReadOnlyPagedCollection.cs
> 893 readonlypagecollection null body

- README.md
The readme doesn't mention the docs folder, and it should.
I wasn't sure exactly where to put the link so if anyone thinks it should be bumped down a bit (perhaps in the "Getting Started" section?) let me know and i'll move it.
> Add docs link into README

- Octokit.Tests.Conventions/Exception/InvalidDebuggerDisplayAttributeValueException.cs
- Octokit.Tests.Conventions/Exception/InvalidDebuggerDisplayReturnType.cs
- Octokit.Tests.Conventions/Exception/MissingDebuggerDisplayAttributeException.cs
- Octokit.Tests.Conventions/Exception/MissingDebuggerDisplayPropertyException.cs
- Octokit.Tests.Conventions/Exception/MutableModelPropertiesException.cs
- Octokit.Tests.Conventions/ModelTests.cs
- Octokit.Tests.Conventions/Octokit.Tests.Conventions.csproj
- Octokit.Tests.Conventions/TypeExtensions.cs
- Octokit.Tests/Helpers/AssertEx.cs
Related to #907
The failing test yields:
>    Expected: True
Actual:   False
Now it will include the offending members, which IMO is much more helpful:
> Model type 'Octokit.RepositoryContent' contains the following mutable properties: 
EncodedContent
> Clarify why convention tests are failing

- Octokit/Models/Response/RepositoryContent.cs
Making `EncodedContent` public to get the raw bytes of a file. #861
> Making Encodedcontent public #861

- Octokit.Tests.Integration/Clients/AssigneesClientTests.cs
- Octokit.Tests.Integration/Clients/AuthorizationClientTests.cs
- Octokit.Tests.Integration/Clients/BlobClientTests.cs
- Octokit.Tests.Integration/Clients/BranchesClientTests.cs
- Octokit.Tests.Integration/Clients/CommitStatusClientTests.cs
- Octokit.Tests.Integration/Clients/CommitsClientTests.cs
- Octokit.Tests.Integration/Clients/DeploymentStatusClientTests.cs
- Octokit.Tests.Integration/Clients/DeploymentsClientTests.cs
- Octokit.Tests.Integration/Clients/GistsClientTests.cs
- Octokit.Tests.Integration/Clients/GitHubClientTests.cs
- Octokit.Tests.Integration/Clients/IssuesClientTests.cs
- Octokit.Tests.Integration/Clients/IssuesEventsClientTests.cs
- Octokit.Tests.Integration/Clients/IssuesLabelsClientTests.cs
- Octokit.Tests.Integration/Clients/MergingClientTests.cs
- Octokit.Tests.Integration/Clients/MilestonesClientTests.cs
- Octokit.Tests.Integration/Clients/PullRequestReviewCommentsClientTests.cs
- Octokit.Tests.Integration/Clients/PullRequestsClientTests.cs
- Octokit.Tests.Integration/Clients/ReferencesClientTests.cs
- Octokit.Tests.Integration/Clients/ReleasesClientTests.cs
- Octokit.Tests.Integration/Clients/RepositoriesClientTests.cs
- Octokit.Tests.Integration/Clients/RepositoryCommitsClientTests.cs
- Octokit.Tests.Integration/Clients/RepositoryContentsClientTests.cs
- Octokit.Tests.Integration/Clients/RepositoryDeployKeysClientTests.cs
- Octokit.Tests.Integration/Clients/StatisticsClientTests.cs
- Octokit.Tests.Integration/Clients/TreeClientTests.cs
- Octokit.Tests.Integration/Helpers/GithubClientExtensions.cs
- Octokit.Tests.Integration/Helpers/RepositoryContext.cs
- Octokit.Tests.Integration/Octokit.Tests.Integration.csproj
- Octokit.Tests.Integration/Reactive/ObservableIssuesClientTests.cs
This solves Issue #655 
I created the structure and refactored the `RepositoriesClientTests` as a way to test what the new syntax looks like. It looks good, but having to write  `var createdRepository = context.Repository;` every  time is kinda boring, I wonder if this can be simplified somehow.
If this looks good I'll refactor the other test classes to use the new syntax as well
____
Those use the same repository for multiple tests, so they won't have the nice `using` syntax. I'll change them for consistency, though
`RepositoryHooksClientTests`, however, uses the `RepositoriesHooksFixture` class, I wonder if this shoud be replaced to use the new context approach or not
> Disposable repositories

- Octokit.nuspec
Currently, installing Octokit into a project which does not have a reference to `System` fails like so:
I always strip out all references from a project and only add back in what is required (it's surprising how often something like a simple business logic lib doesn't even need a reference to `System`).
Anyhow, this nasty looking error can be avoided by declaring `System` as a required framework assembly reference.
I've no idea if this is also required for `netcore45`. I tried it out in a sample `netcore45` project but the whole notion of referencing framework assemblies explicitly doesn't even seem to exist there.
> add System to required framework assemblies for net45

- build.fsx
The FAKE build has deprecated XUnit2Helper http://fsharp.github.io/FAKE/apidocs/fake-xunit2helper.html .
This fix replaces XUnit2Helper with XUnit2
http://fsharp.github.io/FAKE/apidocs/fake-testing-xunit2.html.
> Fixes for FAKE Xunit warning

- Octokit/Exceptions/PrivateRepositoryQuotaExceededException.cs
Fixes #389
Added following links to the Message property:
- 'Deleting a repository' at https://help.github.com/articles/deleting-a-repository/
- 'What plan should I use?' at https://help.github.com/articles/what-plan-should-i-choose/
> Add .com links to PrivateRepositoryQuotaExceededException

- Octokit/Models/Request/NewRepository.cs
> Make NewRepository.HasIssues nullable as it's optional

- docs/search.md
Let me kickstart my documentation contribution with this PR.
Relates to #948
Let me know what you want me to improve on.
/cc @shiftkey
This PR negates #950
> Searching repos

- docs/search.md
Search dem users.
Replaces #952
> Searching users docs

- docs/search.md
> Prepping searching code doc

- .gitignore
- Octokit.Reactive/Octokit.Reactive.csproj
- Octokit/Clients/IRepositoryContentsClient.cs
- Octokit/Clients/OAuthClient.cs
- Octokit/Clients/RepositoryContentsClient.cs
- Octokit/Http/ApiResponse.cs
- Octokit/Http/HttpVerb.cs
- Octokit/Http/ICredentialStore.cs
- Octokit/Http/InMemoryCredentialStore.cs
- Octokit/Models/Request/NewArbitraryMarkDown.cs
- Octokit/Models/Request/SearchRepositoriesRequest.cs
- Octokit/Models/Response/Meta.cs
- Octokit/Octokit-Mono.csproj
- Octokit/Octokit-Portable.csproj
- Octokit/Octokit-netcore45.csproj
- Octokit/Octokit.csproj
- README.md
- build.fsx
> VS2015 migration

- Octokit.Tests.Integration/Clients/RepositoryHooksClientTests.cs
- Octokit.Tests/Models/NewRepositoryWebHookTests.cs
- Octokit.Tests/Octokit.Tests.csproj
- Octokit/Clients/RepositoryHooksClient.cs
- Octokit/Exceptions/RepositoryWebHookConfigException.cs
- Octokit/Helpers/StringExtensions.cs
- Octokit/Helpers/WebHookConfigComparer.cs
- Octokit/Models/Request/NewRepositoryHook.cs
- Octokit/Models/Request/NewRepositoryWebHook.cs
- Octokit/Octokit-Mono.csproj
- Octokit/Octokit-MonoAndroid.csproj
- Octokit/Octokit-Monotouch.csproj
- Octokit/Octokit-Portable.csproj
- Octokit/Octokit-netcore45.csproj
- Octokit/Octokit.csproj
Introducing `NewRepositoryWebHook`, a new strongly typed class that derives from the existing `NewRepositoryHook` class but adds properties and constructor parameters for config settings that should be passed to the API when creating a new web hook. These settings are merged with the config settings that are specific to the web service the web hook will be interacting with (as per [https://api.github.com/hooks](https://api.github.com/hooks)).
Fixes octokit/octokit.net#914
> Add helper class for creating web hooks

- appveyor.yml
Generate nuget packages on appveyor is something that will help consuming the latest master build without waiting for a release 
For example in this  https://github.com/octokit/octokit.net/issues/967#issuecomment-162253541 the consumer of the package had to go through the hazzle of building nuget locally to test this. 
I was enable to enable the nuget packages on my appveyor builds 
https://ci.appveyor.com/nuget/octokit-net-naveen
As part of this PR the main appveyor build settings page has to be updated with a meaningful nuget name which I think is owned by @Haacked 
Here is mine
https://ci.appveyor.com/project/naveensrinivasan/octokit-net/settings/nuget
After updating that we could include that in the README.md so that anyone can consume the latest builds.
> Generate nuget packages on appveyor 

- Octokit.Tests/SimpleJsonSerializerTests.cs
- Octokit/SimpleJson.cs
- SolutionInfo.cs
This will fix the Unicode Json serialization bug https://github.com/octokit/octokit.net/issues/967.
When I was looking at the code I realized there was already a fix with a PR https://github.com/facebook-csharp-sdk/simple-json/pull/66 .Reused the same code for this fix.
> Json serialization for Unicode

- .gitignore
This was renamed from `.ide` when VS2015 was released, but for some reason I've only noticed it now.
I'll leave the old rule around for now, because it's harmless.
> added new rule for VS local cache

- Octokit.Tests.Integration/HttpClientAdapterTests.cs
- Octokit/Http/IRequest.cs
- Octokit/Http/Request.cs
This is no longer supported due to the redirect work implemented in #808 and shipped in `v0.14` - and given `v0.17` is now shipping let's :fire: this member finally...
> removed obsolete member AllowAutoRedirect

- samples/linqpad-samples/6-create-repository.linq
Linqpad example fixes had reference to `SignatureResponse` which is now changed to `Committer` #983. This only fixes the specific file that is causing the build to fail.
> Linqpad example fixes for SignatureResponse

- Octokit.Tests/Clients/RepositoryContentsClientTests.cs
- Octokit/Clients/RepositoryContentsClient.cs
- Octokit/Helpers/ApiExtensions.cs
- Octokit/Http/ApiConnection.cs
- Octokit/Http/IConnection.cs
This should have been picked up earlier, but I didn't `[Obsolete]` the interface so the message didn't flow through the internals to reach the `GetArchiveLink` overloads.
So let's get this into the next release:
> obsolete GetArchiveLink endpoint

- Octokit.Tests/Exceptions/ApiErrorTests.cs
- Octokit.Tests/Exceptions/ApiExceptionTests.cs
- Octokit/Exceptions/ApiException.cs
- Octokit/Models/Response/ApiError.cs
Overrided `ToString` methods for `ApiException` and `ApiError`
Fixes #945 
I'm not really sure about format though. Right now `ToString` produces the following output: 
```
Octokit.ApiException: Validation Failed
Octokit.ApiErrorMessage: Validation Failed
Documentation url: 
Errors:
Message: key is already in use
Code: custom
Field: key
Resource: PublicKey
```
> ToString for ApiException should contain response payload

- Octokit.Tests.Integration/Clients/PullRequestsClientTests.cs
- Octokit.Tests/Clients/SearchClientTests.cs
- Octokit/Models/Response/PullRequest.cs
This replaces #970 (which replaced #936)
As well as the original changes that removed the Merged property, Ive also removed MergeCommitSha as mentioned by @Haacked in #936 
Ive actually added the ```bool Merged ``` property back, with only a getter that returns ```MergedAt.HasValue```  
Happy with this?  Otherwise I could remove this property entirely and all consumers would have to do their own check for ```MergedAt.HasValue```
> Complete PullRequest Merged field changes

- README.md
- appveyor.yml
- build.fsx
This is some parity work as part of moving our OSS projects over to some dedicated resources on AppVeyor. I wanted to do this later in the week but it looks like webhooks weren't being delivered over the weekend, so let's fix this:
cc @haacked
> let's do CI right

- CONTRIBUTING.md
- Octokit.Tests.Integration/Clients/AuthorizationClientTests.cs
- Octokit.Tests.Integration/Clients/PullRequestsClientTests.cs
- Octokit.Tests.Integration/Clients/RepositoriesClientTests.cs
- Octokit.Tests.Integration/Clients/RepositoryDeployKeysClientTests.cs
- Octokit.Tests.Integration/Clients/RepositoryForksClientTests.cs
- Octokit.Tests.Integration/Clients/RepositoryHooksClientTests.cs
- Octokit.Tests.Integration/Helper.cs
- Octokit.Tests.Integration/Helpers/BasicAuthenticationTestAttribute.cs
- Octokit.Tests.Integration/Octokit.Tests.Integration.csproj
- Octokit.Tests.Integration/Reactive/ObservableRespositoryDeployKeysClientTests.cs
- Octokit.Tests.Integration/RedirectTests.cs
- Octokit.Tests.Integration/fixtures/RepositoriesHooksFixture.cs
- Octokit/Clients/PullRequestsClient.cs
- script/configure-integration-tests.ps1
I found myself on a fresh VM and realised I hadn't set up the test variables for Octokit.
So I scripted it out in some rough PowerShell (indicating which are optional parameters for tests which are specific to features not everyone runs - like private repositories or application tests):
```
> .\script\configure-integration-tests.ps1
BIG FREAKING WARNING!!!!!
You should use a test account when running the Octokit integration tests!
Set the account name to use for the integration tests (required): shiftkey-tester
Set the account password to use for the integration tests (optional):
Set the OAuth token to use for the integration tests (required): {token}
Do you have private repositories associated with your test account? Press Y to set this, otherwise we'll skip it: Y
Set the organization …
```
> setting test credentials - now eleventy billion % easier

- CustomDictionary.xml
- Octokit.Tests.Integration/Clients/ReleasesClientTests.cs
- Octokit/Models/Response/Release.cs
- Octokit/Models/Response/ReleaseAsset.cs
Fixes #1008 
Added `Author` to `Release` response. Added integration test ensuring login is set on `Author` property.
I noticed that some other properties are missing too:
- `assets` (this is an object)
- `tarball_url`
- `zipball_url`
Do we want to add those too?
Sample response:
```json
{
"url": "https://api.github.com/repos/git-tfs/git-tfs/releases/2276624",
"assets_url": "https://api.github.com/repos/git-tfs/git-tfs/releases/2276624/assets",
"upload_url": "https://uploads.github.com/repos/git-tfs/git-tfs/releases/2276624/assets{?name,label}",
"html_url": "https://github.com/git-tfs/git-tfs/releases/tag/v0.24.1",
"id": 2276624,
"tag_name": "v0.24.1",
"target_commitish": "master",
"name": "",
"draft": false,
"author": {
"login": "spraints",
"id": 20158,
"avatar_url": …
```
> Fixed Add Author To Release Response

- Octokit.Tests.Integration/Clients/PullRequestsClientTests.cs
- Octokit/Clients/PullRequestsClient.cs
Fixes #1001 
I made two changes:
1. I updated `master` head with the new commit so that the PR is not mergeable (not sure if it's the best way to do this.
2. The `Merge` method wasn't awaiting the API call so the exception couldn't be caught, I made the method `async` and I'm now awaiting the `PUT` request.
> Fixes #1001 CannotBeMergedDueNotInMergeableState

- Octokit.Reactive/Clients/IObservableRepositoriesClient.cs
- Octokit.Reactive/Clients/ObservableRepositoriesClient.cs
- Octokit.Tests.Conventions/ModelTests.cs
- Octokit.Tests.Integration/Clients/BranchesClientTests.cs
- Octokit.Tests/Clients/RepositoriesClientTests.cs
- Octokit.Tests/Reactive/ObservableRepositoriesClientTests.cs
- Octokit/Clients/IRepositoriesClient.cs
- Octokit/Clients/RepositoriesClient.cs
- Octokit/Helpers/AcceptHeaders.cs
- Octokit/Models/Request/BranchUpdate.cs
- Octokit/Models/Response/Branch.cs
- Octokit/Models/Response/BranchProtection.cs
- Octokit/Octokit-Mono.csproj
- Octokit/Octokit-MonoAndroid.csproj
- Octokit/Octokit-Monotouch.csproj
- Octokit/Octokit-Portable.csproj
- Octokit/Octokit-netcore45.csproj
- Octokit/Octokit.csproj
This Work-In-Progress PR adds support for the protected branches API, which is [currently in PREVIEW](https://developer.github.com/changes/2015-11-11-protected-branches-api/)
This is our first contribution to octokit.net so just let us know if anything isn't as desired etc... I've tried to comply with existing similar implementations, coding/comment styles, unit and integration tests and so on, so hopefully it isn't too far off the mark
Since the protected branches API is in preview, I wasn't sure if it's OK to be added, but we need this support for tooling we are writing and would rather contribute to upstream than use a local fork, unless we have to!  I did notice a couple of other preview features in the codebase.  I also saw that octokit.rb has implemented the protected branches …
> Add Protected Branches API support

- CONTRIBUTING.md
I am working in gitter to understand what to put in a seperate file of custom coding conventions for the project.
But this should be here either way
> Add link to corefx coding conventions

- Octokit.Reactive/Clients/IObservableIssueCommentsClient.cs
- Octokit.Reactive/Clients/ObservableIssueCommentsClient.cs
- Octokit/Clients/IIssueCommentsClient.cs
- Octokit/Clients/IssueCommentsClient.cs
- Octokit/Helpers/ApiUrls.cs
As described in the documentation:
- https://developer.github.com/v3/issues/comments/#get-a-single-comment
- https://developer.github.com/v3/issues/comments/#edit-a-comment
- https://developer.github.com/v3/issues/comments/#delete-a-comment
Issue comments are identified by `Id` instead of `Number`. I didn't add any tests as I only renamed parameters and modified XML comments,
> Issue comments are identified by Id instead of Number

- Octokit.Reactive/Clients/IObservableRepositoriesClient.cs
- Octokit.Reactive/Clients/ObservableRepositoriesClient.cs
- Octokit.Reactive/Clients/ObservableRepositoryCommentsClient.cs
- Octokit.Tests.Integration/Clients/PullRequestsClientTests.cs
- Octokit/Clients/IRepositoriesClient.cs
- Octokit/Clients/RepositoriesClient.cs
> IRepositoriesClient.RepositoryComments -> IRepositoriesClient.Comment

- Octokit.Tests.Integration/Clients/IssuesClientTests.cs
- Octokit.Tests.Integration/Clients/IssuesEventsClientTests.cs
- Octokit.Tests/Clients/EventsClientTests.cs
- Octokit/Clients/IssuesClient.cs
- Octokit/Models/Response/ActivityPayloads/IssueEventPayload.cs
- Octokit/Models/Response/Issue.cs
- Octokit/Models/Response/IssueEvent.cs
Also has an `Id` and `Locked` [properties](https://developer.github.com/v3/issues/#get-a-single-issue). I tested the change in the `CanDeserializeIssue` method.
Doesn't have a property `Assignee` or `Label`. GitHub only fire an event when an issue is opened, closed or re-opened. GitHub does not fire an event when assigning someone to the issue, assigning a label or a milestone (I tested manually on my test repository).
Has a `CommitUrl` [property](https://developer.github.com/v3/issues/events/#get-a-single-event). I tested the change in the `CanDeserializeMergedEvent` method.
**Note**: the documentation doesn't have the `CommitUrl` property yet but it is being returned by the API (I used `Fiddler` as my proxy to inspect what was returned).
> Added missing fields from API and removed fields that are not returned by API

- Octokit.Reactive/Clients/IObservableRepositoriesClient.cs
- Octokit.Reactive/Clients/ObservableRepositoriesClient.cs
- Octokit.Reactive/Clients/ObservableRepositoryCommitsClients.cs
- Octokit.Tests.Integration/Clients/RepositoryCommitsClientTests.cs
- Octokit.Tests/Reactive/ObservableRepositoriesClientTests.cs
- Octokit/Clients/IRepositoriesClient.cs
- Octokit/Clients/RepositoriesClient.cs
> IRepositoriesClient.Commits -> IRepositoriesClient.Commit

- Octokit.Tests.Integration/Clients/RepositoryCollaboratorClientTests.cs
- Octokit.Tests.Integration/Octokit.Tests.Integration.csproj
I've added 2 tests and hope to add more. Just want to make sure that I am on the right track.
fixes #1045
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/octokit/octokit.net/1051)
> Add integration tests for RepoCollab client

- Octokit.Reactive/Clients/IObservableRepositoriesClient.cs
- Octokit.Reactive/Clients/ObservableReleasesClient.cs
- Octokit.Reactive/Clients/ObservableRepositoriesClient.cs
- Octokit.Reactive/IObservableGitHubClient.cs
- Octokit.Reactive/ObservableGitHubClient.cs
- Octokit.Tests.Integration/Clients/ReleasesClientTests.cs
- Octokit.Tests/Reactive/ObservableReleasesClientTests.cs
- Octokit/Clients/IRepositoriesClient.cs
- Octokit/Clients/RepositoriesClient.cs
- Octokit/GitHubClient.cs
- Octokit/IGitHubClient.cs
> Dev put release on iRepository from iGitHub client

- Octokit.Reactive/Clients/IObservableStarredClient.cs
- Octokit.Reactive/Clients/ObservableStarredClient.cs
- Octokit.Tests.Integration/Clients/StarredClientTests.cs
- Octokit.Tests.Integration/Octokit.Tests.Integration.csproj
- Octokit/Clients/IStarredClient.cs
- Octokit/Clients/StarredClient.cs
- Octokit/Helpers/AcceptHeaders.cs
- Octokit/Models/Response/RepositoryStar.cs
- Octokit/Models/Response/UserStar.cs
- Octokit/Octokit-Mono.csproj
- Octokit/Octokit-MonoAndroid.csproj
- Octokit/Octokit-Monotouch.csproj
- Octokit/Octokit-Portable.csproj
- Octokit/Octokit-netcore45.csproj
- Octokit/Octokit.csproj
> Adds support for alternate accept header to retrieve star creation timestamps

- Octokit.Reactive/Clients/IObservableRepositoriesClient.cs
- Octokit.Reactive/Clients/IObservableRepositoryPagesClient.cs
- Octokit.Reactive/Clients/ObservableRepositoriesClient.cs
- Octokit.Reactive/Clients/ObservableRepositoryPagesClient.cs
- Octokit.Reactive/Octokit.Reactive-Mono.csproj
- Octokit.Reactive/Octokit.Reactive-MonoAndroid.csproj
- Octokit.Reactive/Octokit.Reactive-Monotouch.csproj
- Octokit.Reactive/Octokit.Reactive.csproj
- Octokit.Tests/Clients/RepositoryPagesClientTests.cs
- Octokit.Tests/OctoKit.Tests-NetCore45.csproj
- Octokit.Tests/Octokit.Tests-Portable.csproj
- Octokit.Tests/Octokit.Tests.csproj
- Octokit/Clients/IRepositoriesClient.cs
- Octokit/Clients/IRepositoryPagesClient.cs
- Octokit/Clients/RepositoriesClient.cs
- Octokit/Clients/RepositoryPagesClient.cs
- Octokit/Helpers/ApiUrls.cs
- Octokit/Models/Response/ApiError.cs
- Octokit/Models/Response/ApiErrorDetail.cs
- Octokit/Models/Response/Page.cs
- Octokit/Models/Response/PagesBuild.cs
- Octokit/Octokit-Mono.csproj
- Octokit/Octokit-MonoAndroid.csproj
- Octokit/Octokit-Monotouch.csproj
- Octokit/Octokit-Portable.csproj
- Octokit/Octokit-netcore45.csproj
- Octokit/Octokit.csproj
Fixes #1033 
**TODO:**
**Questions:**
- The following is an undocumented endpoint.
```
- GET /repos/:owner/:repo/pages/builds:buildID
```
Should it be included?
- The response includes an error field which seems to be mapped to the `ApiError` class. Does that get included in the model?
**Drawing attention**
- Do enums get their own file?
- Is an implementation *needed* for `DebuggerDisplay`?
- What is the level of importance of integration tests for such a client?
> Implement Repository Pages client

- Octokit.Tests/Clients/BlobClientTests.cs
- Octokit.Tests/Clients/CommitStatusClientTests.cs
- Octokit.Tests/Clients/CommitsClientTests.cs
- Octokit.Tests/Clients/FeedsClientTests.cs
- Octokit.Tests/Clients/GistCommentsClientTests.cs
- Octokit.Tests/Clients/GistsClientTests.cs
- Octokit.Tests/Clients/IssueCommentsClientTests.cs
- Octokit.Tests/Clients/IssuesClientTests.cs
- Octokit.Tests/Clients/IssuesEventsClientTests.cs
- Octokit.Tests/Clients/IssuesLabelsClientTests.cs
- Octokit.Tests/Clients/MilestonesClientTests.cs
- Octokit.Tests/Clients/OrganizationsClientTests.cs
- Octokit.Tests/Clients/PullRequestReviewCommentsClientTests.cs
- Octokit.Tests/Clients/PullRequestsClientTests.cs
- Octokit.Tests/Clients/ReferencesClientTests.cs
- Octokit.Tests/Clients/ReleasesClientTests.cs
- Octokit.Tests/Clients/RepositoriesClientTests.cs
- Octokit.Tests/Clients/RepositoryCommentsClientTests.cs
- Octokit.Tests/Clients/RepositoryDeployKeysClientTests.cs
- Octokit.Tests/Clients/RepositoryHooksClientTest.cs
- Octokit.Tests/Clients/TagsClientTests.cs
- Octokit.Tests/Clients/TeamsClientTests.cs
- Octokit.Tests/Clients/TreesClientTests.cs
- Octokit/Helpers/ApiExtensions.cs
- Octokit/Http/ApiConnection.cs
- Octokit/Http/IApiConnection.cs
Fixes #1062
As part of #1062 I found that an extension methods for `Get<T>(uri)` is interfering with some of our unit tests - as it's an extension method contributors can't verify it was invoked correctly, and when that doesn't work blindly add the second parameter to get the test to pass. 
This is done in a lot of tests, and it's a trivial extension, so why not just make it a feature of the interface?
I'm happy to leave the other methods in `ApiExtensions` as-is, they're not used as broadly.
cc @Haacked for feels and any potential quirks about switching from extension method to interface method.
> remove Get<T> extension method to make tests more clear

- Octokit.Reactive/Clients/IObservableOrganizationMembersClient.cs
- Octokit.Reactive/Clients/ObservableOrganizationMembersClient.cs
- Octokit.Tests.Integration/Clients/OrganizationMembersClientTests.cs
- Octokit.Tests.Integration/Octokit.Tests.Integration.csproj
- Octokit.Tests/Clients/OrganizationMembersClientTests.cs
- Octokit/Clients/IOrganizationMembersClient.cs
- Octokit/Clients/OrganizationMembersClient.cs
- Octokit/Helpers/ApiUrls.cs
While working on implementing GitHub Enterprise APIs I came across the fact that the OrganizationMembers API implementation was missing the "Role" filter option (all, admin, member).  
https://developer.github.com/v3/orgs/members/#parameters
I also added integration tests for the GetAll method (previously there were none for this whole API) and all work fine in my integration tests... 
however I found that querying for Admin/Member role only returns correct results when the requester is a member of the organization.  When the requester is not in the organization, the member and admin filters just return all users in the org.  
I also found that with the existing "filter" attribute (2fa_disabled, all) only owners of an organization are allowed to use the ```2fa_disabled``` filter, and …
> Add member role filter to OrganizationMembersClient.GetAll() functions

- CustomDictionary.xml
- Octokit.Reactive/Clients/IObservableUserAdministrationClient.cs
- Octokit.Reactive/Clients/IObservableUsersClient.cs
- Octokit.Reactive/Clients/ObservableUserAdministrationClient.cs
- Octokit.Reactive/Clients/ObservableUsersClient.cs
- Octokit.Reactive/Octokit.Reactive-Mono.csproj
- Octokit.Reactive/Octokit.Reactive-MonoAndroid.csproj
- Octokit.Reactive/Octokit.Reactive-Monotouch.csproj
- Octokit.Reactive/Octokit.Reactive.csproj
- Octokit.Tests/Clients/UserAdministrationClientTests.cs
- Octokit.Tests/OctoKit.Tests-NetCore45.csproj
- Octokit.Tests/Octokit.Tests-Portable.csproj
- Octokit.Tests/Octokit.Tests.csproj
- Octokit.Tests/Reactive/ObservableUserAdministrationClientTests.cs
- Octokit/Clients/IUserAdministrationClient.cs
- Octokit/Clients/IUsersClient.cs
- Octokit/Clients/UserAdministrationClient.cs
- Octokit/Clients/UsersClient.cs
- Octokit/Helpers/ApiUrls.cs
- Octokit/Octokit-Mono.csproj
- Octokit/Octokit-MonoAndroid.csproj
- Octokit/Octokit-Monotouch.csproj
- Octokit/Octokit-Portable.csproj
- Octokit/Octokit-netcore45.csproj
- Octokit/Octokit.csproj
- SolutionInfo.cs
Per, #1030. All implemented tests are passing.
> Implement user Administrator Client

- Octokit.Reactive/Clients/IObservableAuthorizationsClient.cs
- Octokit.Reactive/Clients/ObservableAuthorizationsClient.cs
- Octokit.Tests.Integration/Clients/AuthorizationClientTests.cs
- Octokit/Clients/AuthorizationsClient.cs
- Octokit/Clients/IAuthorizationsClient.cs
As we've done with other breaking changes for this release, we're `[Obsolete]`-ing this method to indicate the behaviour is no longer available.
Fixes #1078
> Revoke All Authentications no longer supported by the API

- Octokit.Reactive/Clients/IObservableReleasesClient.cs
- Octokit.Reactive/Clients/ObservableReleasesClient.cs
- Octokit.Tests/Clients/ReleasesClientTests.cs
- Octokit.Tests/Reactive/ObservableReleasesClientTests.cs
- Octokit/Clients/IReleasesClient.cs
- Octokit/Clients/ReleasesClient.cs
- Octokit/Helpers/ApiUrls.cs
> Implemented GetLatestRelease API.

- Octokit.Tests/Clients/ReleasesClientTests.cs
- Octokit.Tests/Reactive/ObservableReleasesClientTests.cs
Merging #975 caught a couple of API changes in v0.18 which weren't available to the tests at the time of writing. Oops.
> fixing the build

- Octokit.Tests/Clients/StatisticsClientTests.cs
- Octokit/Clients/StatisticsClient.cs
Fixes #822
All other routes - e.g. `ApiUrls` - are defined without a leading slash.
Except these. This fixes that.
> StatisticsClient should not clobber /api/v3/ in path

- Octokit.Tests.Integration/Clients/ReleasesClientTests.cs
> Add integration tests for GetLatestRelease

- Octokit/Octokit.csproj
- Octokit/packages.config
Looks like https://github.com/octokit/octokit.net/commit/38ef6302ec25d8246361e80cb89bd496ff318dc2 introduced a nuget warning/import to the Bcl targets. Pretty sure that should only exist on Portable projects?
> Remove extraneous Bcl .targets reference

- Octokit.Tests/SimpleJsonSerializerTests.cs
- Octokit/Http/SimpleJsonSerializer.cs
As discussed in [#1026](https://github.com/octokit/octokit.net/issues/1026#issuecomment-178856752), there is an issue with the Json parser in a specific edge case.
When deserialising a ```string``` property into a class where that property is declared as a ```List<string>``` (as is the case with the responses from the Enterprise SearchIndexing API), hyphens in the string are stripped during deserialization.
Json
```{ "message":"User \"ryan-gribble\" was added to the indexing queue" }```
Class
```public class MessageList { public IReadOnlyList<string> Message { get; private set; } }```
Result
```"User \"ryangribble\" was added to the indexing queue"```
Expected Result
```"User \"ryan-gribble\" was added to the indexing queue"```
[This …
> Fix Json deserializion of string containing hyphens to List<string> property

- Octokit.Tests.Integration/Clients/RepositoryContentsClientTests.cs
- Octokit.Tests/Clients/RepositoryContentsClientTests.cs
- Octokit/Models/Request/CreateFileRequest.cs
> Add overloads to specify branch for ContentRequest

- Octokit.Tests/Clients/RepositoriesClientTests.cs
- Octokit/Helpers/UriExtensions.cs
- Octokit/Models/Request/RepositoryRequest.cs
As per the issue  #1065 opened by @shiftkey, i have added new parameters to RepositoryRequest class.
> added new parameters to RepositoryRequest.cs

- Octokit.Tests/Clients/RepositoryContentsClientTests.cs
- Octokit/Clients/RepositoryContentsClient.cs
Fix is finished and tested. Also unit test is added.
> Fix passing wrong reference in GetArchive method of RepositoryContentsClient

- Octokit.Reactive/Clients/IObservableUserAdministrationClient.cs
- Octokit.Reactive/Clients/ObservableUserAdministrationClient.cs
- Octokit.Tests.Integration/Clients/UserAdministrationClientTests.cs
- Octokit.Tests.Integration/EnterpriseHelper.cs
- Octokit.Tests.Integration/Helpers/EnterpriseUserContext.cs
- Octokit.Tests.Integration/Helpers/GithubClientExtensions.cs
- Octokit.Tests.Integration/Helpers/ObservableGithubClientExtensions.cs
- Octokit.Tests.Integration/Octokit.Tests.Integration.csproj
- Octokit.Tests.Integration/Reactive/Enterprise/ObservableEnterpriseLdapClientTests.cs
- Octokit.Tests.Integration/Reactive/ObservableUserAdministrationClientTests.cs
- Octokit.Tests/Clients/UserAdministrationClientTests.cs
- Octokit.Tests/Reactive/ObservableUserAdministrationClientTests.cs
- Octokit/Clients/IUserAdministrationClient.cs
- Octokit/Clients/UserAdministrationClient.cs
- Octokit/Helpers/ApiUrls.cs
- Octokit/Models/Request/NewImpersonationToken.cs
- Octokit/Models/Request/NewUser.cs
- Octokit/Models/Request/UserRename.cs
- Octokit/Models/Response/User.cs
- Octokit/Models/Response/UserRenameResponse.cs
- Octokit/Octokit-Mono.csproj
- Octokit/Octokit-MonoAndroid.csproj
- Octokit/Octokit-Monotouch.csproj
- Octokit/Octokit-Portable.csproj
- Octokit/Octokit-netcore45.csproj
- Octokit/Octokit.csproj
:rocket: Ready to merge
~~This is built on top of #1099 which is not yet merged.~~
~~Only the last 4 commits are actually relating to this PR.  I will rebase this as soon as #1099  is merged.~~
~~Here's a diff link showing the consolidated changes for what will be in just this PR:~~
~~https://github.com/TattsGroup/octokit.net/compare/8be8c41966b57de0d994120e733ff02c9d111438...enterprise-useradministration~~
https://developer.github.com/enterprise/2.5/v3/users/administration/
Includes normal and reactive implementations plus unit and integration tests for both, including integration tests for the 4 previously implemented methods in #1068 
Differences in the API docs between github.com and github enterprise are few and far between however one of the major ones I found was that on GitHub …
> Implement Additional Enterprise methods on User Administration Client 

- script/configure-integration-tests.ps1
Made changes in .\script\configure-integration-tests.ps1.
For an optional value it gives the option to change or remove the value, for a necessary value it doesn't give an option.
Fixes #1104
> Fixed Issue 1104

- Octokit.Tests/Http/ConnectionTests.cs
- Octokit/Http/Connection.cs
Passing on serialize argument to Connection's ctor, wasn't passing on before. Breaks tests. Cannot merge.
Refer #1119 
This breaks six tests in total, one of them being [this](https://github.com/octokit/octokit.net/blob/master/Octokit.Tests%2FHttp%2FConnectionTests.cs#L38), I guess that's because, the `IJsonSerializer` in the test is a substitute, it doesn't actually provide a serialization strategy. I don't know much about unit testing and mocking frameworks.
@shiftkey @M-Zuber thoughts?
> [RFC] [WIP] IJsonSerializer parameter in Connection.cs wasn't being used

- Octokit.Tests/Models/RepositoryRequestTests.cs
- Octokit.Tests/Octokit.Tests.csproj
- Octokit/Models/Request/RepositoryRequest.cs
- Octokit/Models/Request/RequestParameters.cs
An attempt to fix mixing of visibility/affiliation and type described in #1107.
> #1107 Do no set default visibility and affiliation values to avoid mixing with type

- Octokit.Reactive/Clients/IObservableUserKeysClient.cs
- Octokit.Reactive/Clients/ObservableUserKeysClient.cs
- Octokit.Tests.Integration/Clients/UserKeysClientTests.cs
- Octokit.Tests.Integration/Reactive/ObservableUserKeysClientTests.cs
- Octokit.Tests/Clients/UserKeysClientTests.cs
- Octokit.Tests/Reactive/ObservableUserKeysClientTests.cs
- Octokit/Clients/IUserKeysClient.cs
- Octokit/Clients/UserKeysClient.cs
> IUserKeysClient.GetAll -> GetAllForCurrent()

- CONTRIBUTING.md
- OVERVIEW.md
[Rendered Markdown](https://github.com/shiftkey/octokit.net/blob/rewrite-contributing/CONTRIBUTING.md)
The influx of new contributors indicates that I need to revisit this document and basically update it.
On top of just refreshing it, I want to have two documents at the end of this:
- `CONTRIBUTING.md` - walk through the process to get your machine setup, know how to find issues (both code and non-code), know how to test your changes locally (both code and non-code)
- `OVERVIEW.md` - the starting point of a document discussing the architecture of Octokit and the important design decisions made
Here's how I'm going about it:
> rewrite contributing docs

- Octokit.Reactive/Clients/IObservableAssigneesClient.cs
- Octokit.Reactive/Clients/ObservableAssigneesClient.cs
- Octokit.Tests.Integration/Octokit.Tests.Integration.csproj
- Octokit.Tests.Integration/Reactive/ObservableAssigneesClientTests.cs
- Octokit.Tests/Clients/AssigneesClientTests.cs
- Octokit/Clients/AssigneesClient.cs
- Octokit/Clients/IAssigneesClient.cs
Fixes #1148.
I have added the necessary overloads and corresponding tests. But one test is failing: 
`AssigneesClientTests+TheGetForRepositoryMethod.RequestsCorrectUrl()`
[Here](https://github.com/octokit/octokit.net/pull/1186/files#diff-a41fcaa8133dfe3db5942c64690de5adR24) are the changes I made. All other tests including integration tests are passing.
/cc @shiftkey
> Add ApiOption overloads to methods on Assignees API

- build.cmd
This tweaks the output of the bootstrapping steps we do with NuGet packages to be less noist.
So no more of this noise when you run `.\build *`
```
Attempting to gather dependencies information for package 'xunit.runner.console.2.1.0' with respect to project 'tools', targeting 'Any,Version=v0.0'
Using credentials from config. UserName: nuget
Attempting to resolve dependencies for package 'xunit.runner.console.2.1.0' with DependencyBehavior 'Lowest'
Resolving actions to install package 'xunit.runner.console.2.1.0'
Resolved actions to install package 'xunit.runner.console.2.1.0'
Adding package 'xunit.runner.console.2.1.0' to folder 'C:\projects\octokit-net\tools'
Added package 'xunit.runner.console.2.1.0' to folder 'C:\projects\octokit-net\tools'
Successfully installed 'xunit.runner.console …
```
> sssh nuget.exe, there is no upset

- build.sh
I should have done this as part of #1191 
This also ensures `Octokit.CodeFormatter` is available as a pre-requisite when running `.\build.sh`
> ssssh nuget - the sequel

- Octokit.Reactive/Clients/IObservableUserEmailsClient.cs
- Octokit.Reactive/Clients/ObservableUserEmailsClient.cs
- Octokit.Tests.Integration/Clients/UserEmailsClientTests.cs
- Octokit.Tests.Integration/Reactive/ObservableUserEmailsClientTests.cs
- Octokit.Tests/Clients/UserEmailsClientTests.cs
- Octokit.Tests/Reactive/ObservableUserEmailsClientTests.cs
- Octokit/Clients/IUserEmailsClient.cs
- Octokit/Clients/UserEmailsClient.cs
- Octokit/Helpers/ApiExtensions.cs
- Octokit/Models/Request/ApiOptions.cs
Refer #1182 .
To-do:
/cc @shiftkey
> Add ApiOption overloads to methods on IUserEmailsClient

- Octokit.Reactive/Clients/IObservableAuthorizationsClient.cs
- Octokit.Reactive/Clients/ObservableAssigneesClient.cs
- Octokit.Reactive/Clients/ObservableAuthorizationsClient.cs
- Octokit.Tests.Integration/Clients/AuthorizationClientTests.cs
- Octokit.Tests.Integration/Octokit.Tests.Integration.csproj
- Octokit.Tests.Integration/Reactive/ObservableAuthorizationsClientTests.cs
- Octokit.Tests/Clients/AssigneesClientTests.cs
- Octokit.Tests/Clients/AuthorizationsClientTests.cs
- Octokit.Tests/Clients/ReleasesClientTests.cs
- Octokit.Tests/Clients/UserEmailsClientTests.cs
- Octokit.Tests/Octokit.Tests.csproj
- Octokit.Tests/Reactive/ObservableAuthorizationsClientTests.cs
- Octokit/Clients/AuthorizationsClient.cs
- Octokit/Clients/IAuthorizationsClient.cs
Refer #1149  .
To-do:
I have one question about integration tests for (Observable)AuthorizationsClient. There are no any integration tests for these clients, so should I add it?
> Add ApiOption overloads to methods on IAuthorizationsClient

- Octokit.Tests/Reactive/ObservablePullRequestsClientTests.cs
Resharper has some useful code analysis that used to eliminate code redundancies. I used Resharper to find "Redundant string.Format() call" and delete them.
> Redundant string.Format() call was removed.

- Octokit/Http/ApiInfo.cs
Resharper has some useful code analysis that used to eliminate code redundancies. I used Resharper to find redundant "this." qualifiers and delete them.
Also, I want to deliver a few PR that are connected with some of redundancies in Octokit.Net, Have I open issue for each of them? Or I could create just PR without appropriate issue?
/cc @shiftkey
> Redundant "this." qualifier was removed.

- Octokit.Tests/Http/RedirectHandlerTests.cs
- Octokit/Http/Credentials.cs
- Octokit/Http/HttpClientAdapter.cs
Resharper has some useful code analysis that used to eliminate code redundancies. I used Resharper to find "Inconsistent modifiers declaration order" issues and fix them.
> Inconsistent modifiers declaration order was fixed.

- Octokit.Reactive/Clients/IObservableRepositoriesClient.cs
- Octokit.Reactive/Clients/ObservableRepositoriesClient.cs
- Octokit/Clients/IRepositoriesClient.cs
- Octokit/Clients/RepositoriesClient.cs
- Octokit/GitHubClient.cs
- Octokit/IGitHubClient.cs
Fixes #1202.
`docmentation -> doc'u'mentation`
Minor issue. Few files changed.
> Correct spelling: docmentation -> documentation

- Octokit.Reactive/IObservableGitHubClient.cs
- Octokit.Tests.Integration/Clients/BranchesClientTests.cs
- Octokit.Tests.Integration/Clients/CommitsClientTests.cs
- Octokit.Tests.Integration/Clients/IssuesClientTests.cs
- Octokit.Tests.Integration/Clients/OrganizationMembersClientTests.cs
- Octokit.Tests/Authentication/CredentialsTests.cs
- Octokit.Tests/Clients/MiscellaneousClientTests.cs
- Octokit.Tests/Clients/RepositoryContentsClientTests.cs
- Octokit.Tests/Clients/StarredClientTests.cs
- Octokit.Tests/Clients/UserAdministrationClientTests.cs
- Octokit.Tests/Exceptions/ForbiddenExceptionTests.cs
- Octokit.Tests/Http/RedirectHandlerTests.cs
- Octokit.Tests/Reactive/AuthorizationExtensionsTests.cs
- Octokit.Tests/Reactive/Enterprise/ObservableEnterpriseSearchIndexingClientTests.cs
- Octokit.Tests/Reactive/ObservableCommitsClientTests.cs
- Octokit.Tests/Reactive/ObservableUserAdministrationClientTests.cs
- Octokit/Clients/IRepositoriesClient.cs
- Octokit/Clients/RepositoriesClient.cs
- Octokit/IGitHubClient.cs
- Octokit/Models/Request/SearchIssuesRequest.cs
- Octokit/Models/Response/CodeFrequency.cs
- Octokit/Models/Response/CommitActivity.cs
- Octokit/SimpleJson.cs
I've removed some common redundancies of code from Octokit.Net.
List of redundancies:
1. Redundant explicit array creation in argument of 'params' parameter.
2. Redundant type qualifiers.
3. Empty constructors.
4.  Redundant explicit array type specification.
5. Redundant member initializers.
6.  Redundant collection list initializers.
7.  Unused "using" directives were removed (in modified files).
8. Some misspellings were fixed.
This PR was made in order to support code quality in Octokit.Net.
> Fix common redundancies by resharper

- Octokit.Tests/Clients/SearchClientTests.cs
I found methods with duplicated piece of code in SearchClientTests.cs (TestingTheRepoQualifier and TestingTheRepoQualifier_InConstructor) and just remove it.
> Duplicated code was removed in SearchClientTests.

- Octokit.Tests.Integration/Clients/RepositoryCommitsClientTests.cs
This test was added in #1195 but it was comparing the wrong branch.
cc @rogertinsley
> verify correct branch in integration test

- Octokit.Reactive/Clients/ObservableAssigneesClient.cs
- Octokit.Tests/Octokit.Tests.csproj
- Octokit.Tests/Reactive/ObservableAssigneesClientTests.cs
After the discussion https://github.com/octokit/octokit.net/pull/1218/commits/42c3a2b728a30def1e8e4385804eeb77b8162c32,  I checked usage of ApiOptions and add necessary null checking.
/cc @shiftkey
> Some ArgumentNotNullOrEmptyString cheсks were added in ObservableAssigneesClient

- Octokit.Tests/Clients/RepositoriesClientTests.cs
- Octokit.Tests/Reactive/ObservableRepositoriesClientTests.cs
- Octokit/Helpers/ApiUrls.cs
- Octokit/Http/HttpClientAdapter.cs
Due to shenanigans with the way dotnet joins`Uri` objects together, if any relative `Uri` endpoint starts with a leading slash, this "wipes out" the `/api/v3/` component of the `BaseAddress` for GitHub Enterprise.  
There were 2 occurrences of endpoint Uri's being set in `ApiUrls` helper class that had incorrect leading slashes on them, causing these calls (both for `RepositoriesClient.GetAllPublic()`) to return HTTP 406 "NotAccepted" errors when run against GitHub Enterprise due to the Url being incorrect.  These have now been corrected.
Additionally I have added a safety in `HttpClientAdapter` class, when constructing the full uri, to trim any leading slashes off relative Uri endpoint before joining it to `BaseAddress`.  
@shiftkey is this OK or is there another way you'd prefer to …
> RepositoriesClient.GetAllPublic() fails on GitHub Enterprise due to incorrect endpoint Uri

- Octokit.Reactive/Clients/ObservableAuthorizationsClient.cs
- Octokit.Reactive/Clients/ObservableRepoCollaboratorsClient.cs
- Octokit.Reactive/Helpers/AuthorizationExtensions.cs
- Octokit/Clients/AuthorizationsClient.cs
- Octokit/Clients/DeploymentsClient.cs
- Octokit/Clients/ReleasesClient.cs
- Octokit/Clients/RepositoriesClient.cs
- Octokit/Clients/RepositoryContentsClient.cs
- Octokit/Clients/TeamsClient.cs
- Octokit/Models/Request/CreateFileRequest.cs
- Octokit/Models/Request/NewReference.cs
I found and fixed some issues when Ensure.ArgumentNotNull and Ensure.ArgumentNotNullOrEmptyString were used.
> Fix Ensure methods parameters

- Octokit.Reactive/Clients/IObservableCommitStatusClient.cs
- Octokit.Reactive/Clients/ObservableCommitStatusClient.cs
- Octokit.Reactive/Clients/ObservableReleasesClient.cs
- Octokit.Tests.Integration/Octokit.Tests.Integration.csproj
- Octokit.Tests.Integration/Reactive/ObservableCommitStatusClientTests.cs
- Octokit.Tests/Clients/CommitStatusClientTests.cs
- Octokit.Tests/Reactive/ObservableReleasesClientTests.cs
- Octokit/Clients/CommitStatusClient.cs
- Octokit/Clients/ICommitStatusClient.cs
This implementation targets the issue [#1150](https://github.com/octokit/octokit.net/issues/1150)
Ps: this is my first contribution to this repo, your remarks are welcome
@shiftkey
> Add ApiOption overloads to methods on ICommitStatusClient

- Octokit.Reactive/Clients/IObservableDeploymentsClient.cs
- Octokit.Reactive/Clients/ObservableDeploymentsClient.cs
- Octokit.Tests.Integration/Clients/DeploymentsClientTests.cs
- Octokit.Tests/Clients/DeploymentsClientTests.cs
- Octokit.Tests/Reactive/ObservableDeploymentsClientTests.cs
- Octokit/Clients/DeploymentsClient.cs
- Octokit/Clients/IDeploymentsClient.cs
Refer #1151 .
To-do:
Some additional checks for count of received parameters were added in ObservableDeploymentsClientTests. If these are ambiguous checks, pls, let me know :+1:
> Add ApiOption overloads to methods on IDeploymentsClient

- Octokit.Reactive/Clients/ObservableMiscellaneousClient.cs
- Octokit.Reactive/ObservableGitHubClient.cs
- Octokit.Tests.Integration/Clients/MiscellaneousClientTests.cs
- Octokit.Tests/Clients/MiscellaneousClientTests.cs
- Octokit.Tests/Octokit.Tests.csproj
- Octokit.Tests/Reactive/ObservableMiscellaneousClientTests.cs
- Octokit/Models/Response/Meta.cs
Adds new field "Importers" to the Metadata request of MiscellaneousClient
API docs: https://developer.github.com/v3/meta/
Fixes #1234 
- Revealed a bug with an existing field `GitHubServicesSha` not being deserialised properly, added a fix to this PR
No tests for this observable client existed, so all methods were implemented
(Marked old constructor as `[Obsolete]` so it can be removed in a later release)
> Add "importers" field to MiscellaneousClient.Meta response

- Octokit.Reactive/Clients/IObservableTeamsClient.cs
- Octokit.Reactive/Clients/ObservableTeamsClient.cs
- Octokit.Tests.Integration/Clients/TeamsClientTests.cs
- Octokit.Tests.Integration/Reactive/ObservableTeamsClientTests.cs
- Octokit.Tests/Clients/TeamsClientTests.cs
- Octokit.Tests/Octokit.Tests.csproj
- Octokit.Tests/Reactive/ObservableTeamsClientTests.cs
- Octokit/Clients/ITeamsClient.cs
- Octokit/Clients/TeamsClient.cs
Fixes #1181 .
Checklist:
As I was doing this, a couple of questions sprung up in my mind:
- ~~After adding `ApiOptions` overload to the methods, we change the implementation of the old method to just call the new one with `ApiOptions.None`. Why don't we just write one method and use default values of `ApiOptions.None`?~~ see discussion
- ~~Secondly, modifying the test for the overloads requires you to check for `Args.ApiOptions`, neither `ApiOptions.None` nor `Arg.Any<ApiOptions>(ApiOptions.None)` work. Why is that so?~~ see discussion
/cc @shiftkey @ryangribble
> Add ApiOptions overloads to ITeamsClient

- Octokit.Reactive/Clients/IObservableIssuesClient.cs
- Octokit.Reactive/Clients/ObservableIssuesClient.cs
- Octokit.Tests.Integration/Clients/IssuesClientTests.cs
- Octokit.Tests.Integration/Reactive/ObservableIssuesClientTests.cs
- Octokit.Tests/Clients/IssuesClientTests.cs
- Octokit.Tests/Reactive/ObservableIssuesClientTests.cs
- Octokit/Clients/IIssuesClient.cs
- Octokit/Clients/IssuesClient.cs
- Octokit/Helpers/AcceptHeaders.cs
- Octokit/Helpers/ApiUrls.cs
- Octokit/Http/ApiConnection.cs
- Octokit/Http/Connection.cs
- Octokit/Http/IApiConnection.cs
- Octokit/Http/IConnection.cs
- SolutionInfo.cs
@shiftkey 
I have added the unit and integration tests for issue #896 . however the build is not running successfully.
> Implemented Lock/Unlock Functionality for Issues

- Octokit/Clients/AssigneesClient.cs
- Octokit/Clients/AuthorizationsClient.cs
- Octokit/Clients/Enterprise/EnterpriseAdminStatsClient.cs
- Octokit/Clients/Enterprise/EnterpriseLdapClient.cs
- Octokit/Clients/Enterprise/EnterpriseLicenseClient.cs
- Octokit/Clients/Enterprise/EnterpriseOrganizationClient.cs
- Octokit/Clients/Enterprise/EnterpriseSearchIndexingClient.cs
- Octokit/Clients/FollowersClient.cs
- Octokit/Clients/GistsClient.cs
- Octokit/Clients/MiscellaneousClient.cs
- Octokit/Clients/OAuthClient.cs
- Octokit/Clients/OrganizationMembersClient.cs
- Octokit/Clients/PullRequestReviewCommentsClient.cs
- Octokit/Clients/PullRequestsClient.cs
- Octokit/Clients/RepoCollaboratorsClient.cs
- Octokit/Clients/RepositoriesClient.cs
- Octokit/Clients/RepositoryContentsClient.cs
- Octokit/Clients/StarredClient.cs
- Octokit/Clients/StatisticsClient.cs
- Octokit/Clients/TeamsClient.cs
- Octokit/Clients/UserAdministrationClient.cs
- Octokit/Clients/WatchedClient.cs
- Octokit/Helpers/AuthorizationExtensions.cs
- Octokit/Helpers/ReferenceExtensions.cs
- Octokit/Http/ApiConnection.cs
- Octokit/Http/Connection.cs
- Octokit/Http/HttpClientAdapter.cs
As discussed in #1111, there are some places where we use `await` but do not specify the context correctly.
This is me scanning the codebase and doing three things with each scenario I find:
- if possible, drop the `async/await` usage completely
- if not possible to remove, ensure `ConfigureAwait` is set
- ensure that the `await` and `ConfigureAwait` are on the same line - to make finding and verifying these usages easier in the future
cc @ryangribble as I found myself refactoring in some of the Enterprise API clients
> Always Be Auditing Your Awaits

- CONTRIBUTING.md
Fix the Testing Documentation's guide link after merging/deleting the rewrite-contributing branch.
> Fix a broken link

- Octokit.Tests/Exceptions/LegalRestrictionExceptionTests.cs
- Octokit.Tests/Octokit.Tests.csproj
- Octokit/Exceptions/LegalRestrictionException.cs
- Octokit/Http/Connection.cs
- Octokit/Octokit-Mono.csproj
- Octokit/Octokit-MonoAndroid.csproj
- Octokit/Octokit-Monotouch.csproj
- Octokit/Octokit-Portable.csproj
- Octokit/Octokit-netcore45.csproj
- Octokit/Octokit.csproj
- SolutionInfo.cs
Implements #1237.
As per this [blog](https://developer.github.com/changes/#--the-451-status-code-is-now-supported) post.
GitHub API will now return a HTTP 451 response (rather than a 403) when a repository or gist cannot be accessed due to a DMCA notice.
Checklist:
/cc @ryangribble
> Add custom exception for the HTTP 451 response

- Octokit.Reactive/Clients/IObservableGistCommentsClient.cs
- Octokit.Reactive/Clients/ObservableGistCommentsClient.cs
- Octokit.Tests.Integration/Octokit.Tests.Integration.csproj
- Octokit.Tests.Integration/Reactive/ObservableGistCommentsClientTests.cs
- Octokit.Tests/Clients/GistCommentsClientTests.cs
- Octokit/Clients/GistCommentsClient.cs
- Octokit/Clients/IGistCommentsClient.cs
This implementation targets the issue : #1155
> Add ApiOption overloads to methods on IGistCommentsClient

- Octokit.Reactive/Clients/IObservableFollowersClient.cs
- Octokit.Reactive/Clients/ObservableFollowersClient.cs
- Octokit.Tests.Integration/Octokit.Tests.Integration.csproj
- Octokit.Tests.Integration/Reactive/ObservableFollowersClientTests.cs
- Octokit.Tests/Clients/FollowersClientTests.cs
- Octokit.Tests/Reactive/ObservableFollowersTest.cs
- Octokit/Clients/FollowersClient.cs
- Octokit/Clients/IFollowersClient.cs
This implementation targets the issue : #1154
> Add ApiOption overloads to methods on IFollowersClient

- Octokit.Tests.Integration/Clients/RepositoryCommitsClientTests.cs
- Octokit/Models/Response/CompareResult.cs
MergeBaseCommit was spelled incorrectly in CompareResult causing Octokit to pass
"null" no matter what the comparison is. This commit makes MergedBaseCommit (the
previous spelling) obsolete, introduces MergeBaseCommit property and adds a test
to ensure that MergeBaseCommit is set properly in CompareResult.
In the test, I specifically compared a commit with itself since the test only
cares whether the property is filled correctly or not, it is not testing whether
the internal computation is correct or not.
Closes #1258.
> Ensure that Commit.Compare(..) sets MergeBaseCommit correctly.

- Octokit.Reactive/Clients/IObservableOrganizationMembersClient.cs
- Octokit.Reactive/Clients/IObservableRepositoryContentsClient.cs
- Octokit.Reactive/Clients/IObservableTeamsClient.cs
- Octokit.Reactive/Clients/ObservableOrganizationMembersClient.cs
- Octokit.Reactive/Clients/ObservableRepositoryContentsClient.cs
- Octokit.Reactive/Clients/ObservableTeamsClient.cs
- Octokit/Clients/IOrganizationMembersClient.cs
- Octokit/Clients/IRepositoryContentsClient.cs
- Octokit/Clients/ITeamsClient.cs
- Octokit/Clients/OrganizationMembersClient.cs
- Octokit/Clients/RepositoryContentsClient.cs
- Octokit/Clients/TeamsClient.cs
- Octokit/Helpers/ApiExtensions.cs
- Octokit/Helpers/ApiUrls.cs
- Octokit/Http/Connection.cs
- Octokit/Http/IApiConnection.cs
- Octokit/Http/IConnection.cs
- Octokit/Models/Request/SearchIssuesRequest.cs
- Octokit/Models/Response/Repository.cs
per #1194 (specifically [this comment](https://github.com/octokit/octokit.net/issues/1194#issuecomment-199810285))
- one small item to draw attention to is [this question](https://github.com/octokit/octokit.net/issues/1194#issuecomment-202014873)
> Cleanup obsolete items

- Octokit.Reactive/Clients/IObservableIssueCommentsClient.cs
- Octokit.Reactive/Clients/ObservableIssueCommentsClient.cs
- Octokit.Tests.Integration/Octokit.Tests.Integration.csproj
- Octokit.Tests.Integration/Reactive/ObservableIssueCommentsClientTests.cs
- Octokit.Tests/Clients/IssueCommentsClientTests.cs
- Octokit.Tests/Reactive/ObservableIssueCommentsClientTests.cs
- Octokit/Clients/IIssueCommentsClient.cs
- Octokit/Clients/IssueCommentsClient.cs
> Add ApiOption overloads to methods on IIssueCommentsClient 

- Octokit.Reactive/Clients/IObservableGistsClient.cs
- Octokit.Reactive/Clients/ObservableGistsClient.cs
- Octokit.Tests.Integration/Octokit.Tests.Integration.csproj
- Octokit.Tests.Integration/Reactive/ObservableGistClientTests.cs
- Octokit.Tests/Clients/GistsClientTests.cs
- Octokit.Tests/Helpers/Arg.cs
- Octokit.Tests/Reactive/ObservableGistsTests.cs
- Octokit/Clients/GistsClient.cs
- Octokit/Clients/IGistsClient.cs
> Add ApiOption overloads to methods on IGistsClient

- Octokit.Reactive/Clients/IObservableRepositoryHooksClient.cs
- Octokit.Reactive/Clients/ObservableRepositoryHooksClient.cs
- Octokit.Tests.Integration/Clients/RepositoryHooksClientTests.cs
- Octokit.Tests.Integration/Octokit.Tests.Integration.csproj
- Octokit.Tests.Integration/Reactive/ObservableRepositoryHooksClientTests.cs
- Octokit.Tests.Integration/fixtures/RepositoriesHooksFixture.cs
- Octokit.Tests/Clients/RepositoryHooksClientTest.cs
- Octokit.Tests/Octokit.Tests.csproj
- Octokit.Tests/Reactive/ObservableRepositoryHooksClientTests.cs
- Octokit/Clients/IRepositoryHooksClient.cs
- Octokit/Clients/RepositoryHooksClient.cs
Fixes #1149 .
To-do:
Please review these changes, especially changes in RepositoriesHooksFixture.cs. I had to change it in order to get additional hooks and properly test methods with ApiOptions parameter.
> Add ApiOption overloads to methods on IRepositoryHooksClient

- Octokit.Tests.Conventions/ModelTests.cs
- Octokit.Tests.Conventions/PaginationTests.cs
- Octokit.Tests.Conventions/SyncObservableClients.cs
- Octokit.Tests.Conventions/TypeExtensions.cs
Refers #1246 
As was discussed in #1246 top level types should be used to determine assembly name in conventions tests. I've changed type from IEventsClient to IGitHubClient and GitHubClientTests types.
/cc @shiftkey @ryangribble
> Method of assembly determination was changed in order to use types of top level

- Octokit.Tests.Integration/Helpers/ObservableGithubClientExtensions.cs
Modifiers declaration order was adjusted a little as part of whole check of Octokit by Resharper.
The order `internal async static` was changed to 'internal static async'
Citation from [Resharper documentation](https://www.jetbrains.com/help/resharper/10.0/Modifiers_Style.html?origin=old_help)
> C# modifiers of types and type members can be written in any order. However, arranging them in a similar way throughout your code is a good practice, which improves code readability. 
/cc @shiftkey
> Modifiers declaration order was adjusted

- Octokit.Tests.Integration/Clients/BranchesClientTests.cs
- Octokit.Tests.Integration/Clients/RepositoryDeployKeysClientTests.cs
- Octokit.Tests.Integration/Reactive/ObservableRepositoryDeployKeysClientTests.cs
- Octokit.Tests/Clients/GistsClientTests.cs
- Octokit.Tests/Clients/IssueCommentsClientTests.cs
- Octokit.Tests/Clients/RepositoryHooksClientTest.cs
- Octokit.Tests/Http/RedirectHandlerTests.cs
- Octokit.Tests/Models/RequestParametersTests.cs
- Octokit.Tests/Reactive/ObservableGistsTests.cs
- Octokit.Tests/Reactive/ObservableIssueCommentsClientTests.cs
Redundant braces of argument list were removed as part of whole check of Octokit by Resharper.
/cc @shiftkey
> Redundant braces of argument list were removed

- Octokit.Reactive/Clients/IObservableRepositoryCommitsClients.cs
- Octokit.Tests.Integration/Clients/IssuesClientTests.cs
- Octokit.Tests.Integration/Clients/PullRequestReviewCommentsClientTests.cs
- Octokit.Tests.Integration/Clients/RepositoryCommitsClientTests.cs
- Octokit.Tests.Integration/Clients/UserAdministrationClientTests.cs
- Octokit.Tests.Integration/Reactive/ObservableRepositoryCommitsClientTests.cs
- Octokit.Tests.Integration/Reactive/ObservableUserAdministrationClientTests.cs
- Octokit.Tests/Clients/GistsClientTests.cs
- Octokit.Tests/Clients/IssueCommentsClientTests.cs
- Octokit.Tests/Http/ApiInfoTests.cs
Just continue my war with redundancies in code.
1) redundant @ prefix was removed
2) redundant explicit array type specifications were removed
3) redundant argument list was removed
4) redundant commas in object initializer were removed.
/cc @shiftkey
> Fix common redundancies

- Octokit.Reactive/Clients/IObservableRepoCollaboratorsClient.cs
- Octokit.Reactive/Clients/ObservableRepoCollaboratorsClient.cs
- Octokit.Tests.Integration/Clients/RepositoryCollaboratorClientTests.cs
- Octokit.Tests.Integration/Octokit.Tests.Integration.csproj
- Octokit.Tests.Integration/Reactive/ObservableRepositoryCollaboratorClientTests.cs
- Octokit.Tests/Clients/RepoCollaboratorsClientTests.cs
- Octokit.Tests/Octokit.Tests.csproj
- Octokit.Tests/Reactive/ObservableRepoCollaboratorsClientTests.cs
- Octokit/Clients/IRepoCollaboratorsClient.cs
- Octokit/Clients/RepoCollaboratorsClient.cs
Refer #1170
To-do:
Unfortunately, I haven't found the approach to add more than 2 users on integration tests. So, there are only two users in each test case: user configured on local machine ("dampirtest" for my PC) and "m-zuber-octokit-integration-tests". How and where "m-zuber-octokit-integration-tests" was added as repository user I not found.
> Add ApiOption overloads to methods on IRepoCollaboratorsClient

- Octokit.Reactive/Clients/IObservableUserKeysClient.cs
- Octokit.Reactive/Clients/ObservableUserKeysClient.cs
- Octokit.Tests/Clients/UserKeysClientTests.cs
- Octokit.Tests/Reactive/ObservableUserKeysClientTests.cs
- Octokit/Clients/IUserKeysClient.cs
- Octokit/Clients/UserKeysClient.cs
Fixes #1183.
Adds pagination support in the Users->SSH Keys API.
Checklist:
/cc @shiftkey
> Add pagination support (ApiOptions overloads) to UserKeys client.

- Octokit.Tests.Integration/Clients/SearchClientTests.cs
- Octokit.Tests/Clients/SearchClientTests.cs
- Octokit.Tests/Models/SearchIssuesRequestExclusionsTests.cs
- Octokit.Tests/Models/SearchIssuesRequestTests.cs
- Octokit.Tests/Octokit.Tests.csproj
- Octokit/Models/Request/SearchIssuesRequest.cs
- Octokit/Models/Request/SearchIssuesRequestExclusions.cs
- Octokit/Octokit-Mono.csproj
- Octokit/Octokit-MonoAndroid.csproj
- Octokit/Octokit-Monotouch.csproj
- Octokit/Octokit-Portable.csproj
- Octokit/Octokit-netcore45.csproj
- Octokit/Octokit.csproj
Fixes #1227 
https://developer.github.com/v3/search/#search-issues
https://help.github.com/articles/searching-issues
Added new options to `SearchIssuesRequest`
- Searching by [`team`](https://help.github.com/articles/searching-issues/#search-by-a-team-thats-mentioned-within-an-issue-or-pull-request)
- Searching by "not" label syntax [`-label`](https://help.github.com/articles/searching-issues/#search-by-the-labels-on-an-issue)
- Searching on missing metadata [`no`](https://help.github.com/articles/searching-issues/#search-by-missing-metadata-on-an-issue-or-pull-request)
- The "human" styled [`is`](https://help.github.com/articles/searching-issues/#search-based-on-the-state-of-an-issue-or-pull-request) query 
- (although `state` and `type` cover most of the `is` options, the …
> Implement additional `SearchIssuesRequest` options

- Octokit.Reactive/Clients/IObservableEventsClient.cs
- Octokit.Reactive/Clients/ObservableEventsClient.cs
- Octokit.Tests.Integration/Reactive/ObservableEventsClientTests.cs
- Octokit.Tests/Clients/EventsClientTests.cs
- Octokit.Tests/Reactive/ObservableEventsClientTests.cs
- Octokit/Clients/EventsClient.cs
- Octokit/Clients/IEventsClient.cs
- Octokit/Helpers/ApiUrls.cs
Currently in EventsClient, "GetAllForRepository" actually gets the Issues activity feed, rather than the actual repository activity feed. This commit fixes that by adding "GetAllIssuesForRepository" and changing "GetAllForRepository" to correctly use the right endpoint.
> Add actual "GetAllForRepository" Activity Feed

- README.md
Fixes #1285 
I looked to the rest of the documentation, but couldn't find another reference to Read The Docs, besides the one in the readme file.
> #1285 Updated the ReadTheDocs link to .io

- Octokit/Helpers/ApiUrls.cs
As part of my work on #1120 I've done some improvements in ApiUrls.cs class. 
I've found that in order to support work with repo by their ID we should add 83 new methods in ApiUrls.cs that would duplicate methods that allow to work with repo by their owner and name identificators.
E.g.
We have the next method in ApiUrls.cs:
```cs
public static Uri RepoBranch(string owner, string name, string branchName)
{
return "repos/{0}/{1}/branches/{2}".FormatUri(owner, name, branchName);
}
```
So we should add the new one:
```cs
public static Uri RepoBranch(int repositoryId, string branchName)
{
return "repositories/{0}/branches/{1}".FormatUri(repositoryId, branchName);
}
```
Because of the fact that we should add 83 new methods, I've decided to generate them programmatically. And in order to get …
> Fixed inconsistency in ApiUrls.cs

- Octokit/Clients/BlobsClient.cs
- Octokit/Helpers/ApiUrls.cs
As part of my work on #1120 I've added new api urls to get access by repository id.
Here one example of new method
Protorype:
```cs
/// <summary>
/// Returns the <see cref="Uri"/> that returns the assets specified by the asset id.
/// </summary>
/// <param name="owner">The owner of the repository</param>
/// <param name="name">The name of the repository</param>
/// <param name="id">The id of the release asset</param>
/// <returns></returns>
public static Uri Asset(string owner, string name, int id)
{
return "repos/{0}/{1}/releases/assets/{2}".FormatUri(owner, name, id);
}
```
New method:
```cs
/// <summary>
/// Returns the <see cref="Uri"/> that returns the assets specified by the asset id.
/// </summary>
/// <param name="repositoryId">The ID of the repository</param>
/// <param …
```
> Added new api urls to get access be repository id

- Octokit.Reactive/Clients/IObservableRepositoryDeployKeysClient.cs
- Octokit.Reactive/Clients/ObservableRepositoryDeployKeysClient.cs
- Octokit.Tests.Integration/Clients/RepositoryDeployKeysClientTests.cs
- Octokit.Tests/Clients/RepositoryDeployKeysClientTests.cs
- Octokit.Tests/Reactive/ObservableRepositoryDeployKeysClientTests.cs
- Octokit/Clients/IRepositoryDeployKeysClient.cs
- Octokit/Clients/RepositoryDeployKeysClient.cs
Refer #1175 .
To-do:
I've implemented the integration tests, but they are skipped now, because we don't have opportunity generate ssh keys in C# code (#1003).
Also I haven't implemented integration tests for ObservableRepositoryDeployKeysClient because internally ObservableRepositoryDeployKeysClient use RepositoryDeployKeysClient that have integration tests already (just they skipped :smile: ).
> Add ApiOptions overloads to methods on I(Observable)RepositoryDeployKeysClient

- Octokit/Clients/RepositoryCommitsClient.cs
Just removed redundant ApiConnection field and use protected property ApiConection instead.
> Redundant ApiConnection field was removed

- Octokit.Reactive/Clients/IObservableRepositoryCommentsClient.cs
- Octokit.Reactive/Clients/ObservableRepositoryCommentsClient.cs
- Octokit.Tests.Integration/Clients/RepositoryCommentsClientTests.cs
- Octokit.Tests.Integration/Octokit.Tests.Integration.csproj
- Octokit.Tests/Clients/RepositoryCommentsClientTests.cs
- Octokit.Tests/Octokit.Tests.csproj
- Octokit.Tests/Reactive/ObservableRepoCollaboratorsClientTests.cs
- Octokit.Tests/Reactive/ObservableRepositoryCommentsClientTests.cs
- Octokit/Clients/IRepositoryCommentsClient.cs
- Octokit/Clients/RepositoryCommentsClient.cs
Refer #1172
Despite on this #1262, I've do this by myself, because we should finish Pagination milestone in near future in order to start working on repositoryId functionality (#1120).
To-do:
Also I've added await\async modifiers into unit tests class RepositoryCommentsClientTests.cs , because I suppose these modifiers should be there to get determined results of tests.
No integration tests exists for these clients, so I've add whole new integration test for RepositoryCommentsClient,
> Add ApiOption overloads to methods on I(Observable)RepositoryCommentsClient

- Octokit.Tests.Integration/Clients/RepositoryDeployKeysClientTests.cs
I've fixed incorrect names of tests in RepositoryDeployKeysClientTests.
> Fixed incorrect names of tests in RepositoryDeployKeysClientTests

- Octokit.Reactive/Clients/IObservableMilestonesClient.cs
- Octokit.Reactive/Clients/ObservableMilestonesClient.cs
- Octokit.Tests.Integration/Clients/MilestonesClientTests.cs
- Octokit.Tests/Clients/MilestonesClientTests.cs
- Octokit.Tests/Reactive/ObservableMilestonesClientTests.cs
- Octokit/Clients/IMilestonesClient.cs
- Octokit/Clients/MilestonesClient.cs
Refer #1161
To-do:
~~I've added all new units tests, but **_I've one failed test and I need some help in order to fix it._**
public async Task SendsAppropriateParametersMulti() is failed [here](https://github.com/octokit/octokit.net/blob/43f6cfe28ba4fd67f56e0c127d2ccdf082f787db/Octokit.Reactive/Helpers/ConnectionExtensions.cs#L58) on second pass, because of ApiInfo equal to null. As I found out, ApiInfo is class and NSubstitute cannot substitute ApiInfo automatically. So there is NullReferenceException occur on the second pass i.e. when Observable.Defer(() => getPageFunc(nextPageUrl, null, null)) fires for the first time. 
For better illustration I captured [the video](https://yadi.sk/i/2jNxQ6pvrvMWf) (please select HD quality in right bottom corner). In this video I showed that …
> Add ApiOption overloads to methods on I(Observable)MilestonesClient

- Octokit.Reactive/Clients/IObservableDeploymentStatusClient.cs
- Octokit.Reactive/Clients/ObservableDeploymentStatusClient.cs
- Octokit.Tests.Integration/Clients/DeploymentStatusClientTests.cs
- Octokit.Tests/Clients/DeploymentStatusClientTests.cs
- Octokit.Tests/Reactive/ObservableDeploymentStatusClientTests.cs
- Octokit/Clients/DeploymentStatusClient.cs
- Octokit/Clients/IDeploymentStatusClient.cs
> Add ApiOption overloads to methods on I(Observable)DeploymentStatusClient

- Octokit.Reactive/Clients/IObservablePullRequestsClient.cs
- Octokit.Reactive/Clients/ObservablePullRequestsClient.cs
- Octokit.Tests.Integration/Clients/PullRequestsClientTests.cs
- Octokit.Tests/Clients/PullRequestsClientTests.cs
- Octokit.Tests/Reactive/ObservablePullRequestsClientTests.cs
- Octokit/Clients/IPullRequestsClient.cs
- Octokit/Clients/PullRequestsClient.cs
> Add ApiOption overloads to methods on I(Observable)PullRequestsClient

- Octokit.Reactive/Clients/IObservableReleasesClient.cs
- Octokit.Reactive/Clients/ObservableReleasesClient.cs
- Octokit.Tests.Integration/Clients/ReleasesClientTests.cs
- Octokit.Tests/Clients/ReleasesClientTests.cs
- Octokit.Tests/Reactive/ObservableReleasesClientTests.cs
- Octokit/Clients/IReleasesClient.cs
- Octokit/Clients/ReleasesClient.cs
Fixes #1169
To-do:
Also I've added await\async modifiers into unit tests class ReleasesClientTests.cs , because I suppose these modifiers should be there to get determined results of tests, shouldn't be?
/cc @shiftkey , @ryangribble all is done, but there are some strange failures in test cases.
> Add ApiOption overloads to methods on I(Observable)ReleasesClient

- Octokit.Reactive/Clients/IObservableIssuesLabelsClient.cs
- Octokit.Reactive/Clients/ObservableIssuesLabelsClient.cs
- Octokit.Tests.Integration/Clients/IssuesLabelsClientTests.cs
- Octokit.Tests/Clients/IssuesLabelsClientTests.cs
- Octokit.Tests/Octokit.Tests.csproj
- Octokit.Tests/Reactive/ObservableIssuesLabelsClientTests.cs
- Octokit/Clients/IIssuesLabelsClient.cs
- Octokit/Clients/IssuesLabelsClient.cs
> Add ApiOptions overloads to methods on I(Observable)IssuesLabelsClient

- Octokit.Tests.Integration/Clients/RepositoriesClientTests.cs
- Octokit.Tests.Integration/Clients/RepositoryCommentsClientTests.cs
Preparing another release now that we're closing to wrapping up all the `ApiOptions` changes, and found a couple of integration tests that needed updating:
- as GitHub now supports unlimited repositories for paid plans, we cannot really check for quotas. I'll clean up that test later.
- deleting a comment and then trying to retrieve it should return a 404 - I'm not sure why that test has been that way for so long, but let's test the correct behaviour here.
> correcting a couple of integration tests

- Octokit.Reactive/Clients/IObservableOrganizationsClient.cs
- Octokit.Reactive/Clients/ObservableOrganizationsClient.cs
- Octokit.Tests.Integration/Clients/OrganizationClientTests.cs
- Octokit.Tests.Integration/Clients/OrganizationsClientTests.cs
- Octokit.Tests.Integration/Octokit.Tests.Integration.csproj
- Octokit.Tests/Clients/OrganizationsClientTests.cs
- Octokit.Tests/Octokit.Tests.csproj
- Octokit.Tests/Reactive/ObservableOrganizationsClientTests.cs
- Octokit/Clients/IOrganizationsClient.cs
- Octokit/Clients/OrganizationsClient.cs
Fixes #1165 
To-do:
I had to use [GitHubEnterpriseTest] to get these tests done, because I should create organizations firstly.
> Add ApiOption overloads to methods on I(Observable)OrganizationsClient

- Octokit.Reactive/Clients/IObservableOrganizationMembersClient.cs
- Octokit.Reactive/Clients/ObservableOrganizationMembersClient.cs
- Octokit.Tests.Integration/Clients/OrganizationMembersClientTests.cs
- Octokit.Tests/Clients/OrganizationMembersClientTests.cs
- Octokit.Tests/Reactive/ObservableOrganizationMembersClientTests.cs
- Octokit/Clients/IOrganizationMembersClient.cs
- Octokit/Clients/OrganizationMembersClient.cs
Fixes #1164
To-do:
Added only for  GetAll(string org) overload, the others overloads are skipped, so I decide do not add them. If I have to, please let me know :smile: 
> Add ApiOptions overloads to methods on I(Observable)OrganizationMembersClient

- Octokit.Reactive/Clients/IObservableNotificationsClient.cs
- Octokit.Reactive/Clients/ObservableNotificationsClient.cs
- Octokit.Tests/Clients/NotificationsClientTests.cs
- Octokit.Tests/Octokit.Tests.csproj
- Octokit.Tests/Reactive/ObservableNotificationsClientTests.cs
- Octokit/Clients/INotificationsClient.cs
- Octokit/Clients/NotificationsClient.cs
Fixes #1163 
To-do:
It's seems like now we do not have ability to create integration tests for I(Observable)NotificationsClient. I've opened issue #1333 to discuss it in details.
> Add ApiOptions overloads to methods on I(Observable)NotificationsClient

- Octokit.Reactive/Clients/IObservableIssuesClient.cs
- Octokit.Reactive/Clients/ObservableIssuesClient.cs
- Octokit.Tests.Integration/Clients/IssuesClientTests.cs
- Octokit.Tests.Integration/Reactive/ObservableIssuesClientTests.cs
- Octokit.Tests/Clients/IssuesClientTests.cs
- Octokit.Tests/Reactive/ObservableIssuesClientTests.cs
- Octokit/Clients/IIssuesClient.cs
- Octokit/Clients/IssuesClient.cs
Fixes #1158
This is a big one, so I'm going through it as slowly and methodically as possible:
> Add ApiOption overloads to IIssuesClient and IObservableIssuesClient

- Octokit.Reactive/Clients/IObservableStarredClient.cs
- Octokit.Reactive/Clients/ObservableStarredClient.cs
- Octokit.Reactive/Helpers/ConnectionExtensions.cs
- Octokit.Tests.Integration/Clients/StarredClientTests.cs
- Octokit.Tests/Clients/StarredClientTests.cs
- Octokit.Tests/Reactive/ObservableStarredClientTests.cs
- Octokit/Clients/IStarredClient.cs
- Octokit/Clients/StarredClient.cs
> Add ApiOptions overloads to methods on I(Observable)StarredClient

- Octokit.Tests.Integration/Clients/SearchClientTests.cs
- Octokit/Models/Request/BaseSearchRequest.cs
- Octokit/Models/Request/SearchCodeRequest.cs
This change adds a parameter-less constructor to `SearchCodeRequest` and modifies `BaseSearchRequest` to handle the case where the 'Term' is null.  This supports the scenario of searching for a filename without specifying a search term, as in this search: https://github.com/dotnet/corefx/search?utf8=%E2%9C%93&q=filename%3Aproject.json
> Add support for code searches without a search term

- Octokit/Models/Response/Issue.cs
Fixes #1350 
Add `ClosedBy` key to Issue response if you request an single Issue.
> Add closed_by key to Issue

- Octokit.Reactive/Clients/ObservableTeamsClient.cs
- Octokit.Reactive/Helpers/ConnectionExtensions.cs
- Octokit.Tests.Integration/Clients/RepositoryCollaboratorClientTests.cs
- Octokit.Tests.Integration/Clients/TeamsClientTests.cs
- Octokit.Tests.Integration/Reactive/ObservableRepositoryCollaboratorClientTests.cs
- Octokit.Tests.Integration/Reactive/ObservableTeamsClientTests.cs
- Octokit.Tests/Clients/RepoCollaboratorsClientTests.cs
- Octokit.Tests/Clients/TeamsClientTests.cs
- Octokit/Clients/RepoCollaboratorsClient.cs
- Octokit/Clients/TeamsClient.cs
- Octokit/Helpers/AcceptHeaders.cs
- Octokit/Models/Response/User.cs
Fixes #1319
Added/ensured `Permissions` are supported for:
Added `Permission` attribute to `User` object, updated tests for Repository Collaborators to ensure field is populated.  Although preview period has ended I decided to pass the preview accepts header anyway since GHE 2.5 requires it
Found that `Repository` already had `Permissions` attribute and the Team's Repositories call was already working (once preview period ended).  Added accept header so it works on GHE 2.5 and added some integration tests to ensure the property is being deserialized
> Add permission attribute to collaborators and team's repositories

- Octokit.Reactive/Clients/IObservableUsersClient.cs
- Octokit.Reactive/Clients/ObservableUserKeysClient.cs
- Octokit.Reactive/Clients/ObservableUsersClient.cs
- Octokit.Tests.Integration/Clients/UserKeysClientTests.cs
- Octokit.Tests.Integration/Helper.cs
- Octokit.Tests.Integration/Helpers/GithubClientExtensions.cs
- Octokit.Tests.Integration/Helpers/ObservableGithubClientExtensions.cs
- Octokit.Tests.Integration/Reactive/ObservableUserKeysClientTests.cs
- Octokit.Tests/Reactive/ObservableUserKeysClientTests.cs
- Octokit/Clients/IUsersClient.cs
- Octokit/Clients/UsersClient.cs
Fixes #1253 
In both the normal and reactive clients and interfaces,
- Rename `client.User.Keys` to `client.User.GitSshKey`
- Mark `client.User.Keys` as `[Obsolete]`
This has been done on top of #1343 so the commit list in this PR should tidy itself up once #1343 is merged
> Rename client.User.Keys to client.User.GitSshKey

- Octokit.Reactive/Clients/IObservableRepositoryForksClient.cs
- Octokit.Reactive/Clients/ObservableRepositoryForksClient.cs
- Octokit.Tests.Integration/Clients/RepositoryForksClientTests.cs
- Octokit.Tests/Clients/RepositoryForksClientTests.cs
- Octokit.Tests/Octokit.Tests.csproj
- Octokit.Tests/Reactive/ObservableRepositoryForksClientTests.cs
- Octokit/Clients/IRepositoryForksClient.cs
- Octokit/Clients/RepositoryForksClient.cs
> Add ApiOptions overloads to methods on I(Observable)RepositoryForksClient

- Octokit.Reactive/Clients/IObservableRepositoriesClient.cs
- Octokit.Reactive/Clients/ObservableRepositoriesClient.cs
- Octokit.Tests.Integration/Clients/RepositoriesClientTests.cs
- Octokit.Tests/Clients/RepositoriesClientTests.cs
- Octokit.Tests/Reactive/ObservableRepositoriesClientTests.cs
- Octokit/Clients/IRepositoriesClient.cs
- Octokit/Clients/RepositoriesClient.cs
Fixes #1171 
For each of these entries:
- add overload to both clients
- implement
- update impacted unit tests
- add new integration tests wherever possible
- ~~[ ] `Task<IReadOnlyList<RepositoryLanguage>> GetAllLanguages(String owner, String name)`~~
- ~~[ ] `Task<IReadOnlyList<Repository>> GetAllPublic()`~~ moved to #1340
- ~~[ ] `Task<IReadOnlyList<Repository>> GetAllPublic(PublicRepositoryRequest request)`~~ moved to #1340
> Add ApiOptions overloads to I(Observable)RepositoriesClient

- .travis.yml
Travis is currently in an interesting spot where `latest` means it'll use Mono **4.4.0** when building and testing on OS X, and **4.2.3** when building and testing on Linux.
Unfortunately this means the OS X builds are exhibiting some strange behaviour:
- a [wall of Chinese text](https://twitter.com/shiftkey/status/742500043769274369) in the `BuildMono` step
- `* Assertion at metadata.c:3643, condition 'ptr' not met` when running the PCL tests
Example build output: https://travis-ci.org/octokit/octokit.net/jobs/137385011
I found the flag to force a specific version of Mono for both platforms, and that seems to do the trick here.
@dampir @ErikSchierboom @shaggygi @alfhenrik @maddin2016 I think you're all encountering this on your PRs, feel free to merge `master` or cherry-pick this commit …
> lock to an earlier version of mono

- docs/extensibility.md
This should make the usage of `ApiOptions` a bit clearer...
> add some examples to pagination docs

- Octokit.Tests.Integration/Clients/PullRequestsClientTests.cs
- Octokit.Tests.Integration/Clients/RepositoriesClientTests.cs
- Octokit.Tests.Integration/Clients/RepositoryContentsClientTests.cs
- Octokit.Tests.Integration/Clients/RepositoryHooksClientTests.cs
- Octokit.Tests.Integration/Reactive/ObservableEventsClientTests.cs
- ReleaseNotes.md
- SolutionInfo.cs
> v0.20 - Probably Australian

- Octokit.Reactive/Clients/ObservableIssueCommentsClient.cs
- Octokit.Tests.Integration/Clients/IssueCommentsClientTests.cs
- Octokit.Tests.Integration/Octokit.Tests.Integration.csproj
- Octokit.Tests.Integration/Reactive/ObservableIssueCommentsClientTests.cs
- Octokit.Tests/Clients/IssueCommentsClientTests.cs
- Octokit.Tests/Reactive/ObservableIssueCommentsClientTests.cs
- Octokit/Clients/IssueCommentsClient.cs
- Octokit/Models/Response/IssueComment.cs
- Octokit/Models/Response/IssueCommentReactions.cs
- Octokit/Models/Response/ReactionSummary.cs
- Octokit/Octokit-Mono.csproj
- Octokit/Octokit-MonoAndroid.csproj
- Octokit/Octokit-Monotouch.csproj
- Octokit/Octokit-Portable.csproj
- Octokit/Octokit-netcore45.csproj
- Octokit/Octokit.csproj
> Include reactions on issue comments

- Octokit.Reactive/Clients/IObservableRepositoryContentsClient.cs
- Octokit.Reactive/Clients/ObservableRepositoryContentsClient.cs
- Octokit.Tests.Integration/Clients/RepositoryContentsClientTests.cs
- Octokit.Tests/Clients/RepositoryContentsClientTests.cs
- Octokit.Tests/Octokit.Tests.csproj
- Octokit.Tests/Reactive/ObservableRepositoryContentsClientTests.cs
- Octokit/Clients/IRepositoryContentsClient.cs
- Octokit/Clients/RepositoryContentsClient.cs
As part of my work on #1120 I've added new overloads on I(Observable)RepositoryContentsClient to get access by repository id.
There is some divergence between XML documentation of methods in IRepositoryContentsClient and IObservableRepositoryContentsClient. So I've decided 
I've added new integration tests that use …
> Add repositoryId overloads to methods on I(Observable)RepositoryContentsClient

- Octokit.Reactive/Clients/IObservableRepositoryDeployKeysClient.cs
- Octokit.Reactive/Clients/ObservableRepositoryDeployKeysClient.cs
- Octokit.Tests.Integration/Clients/RepositoryDeployKeysClientTests.cs
- Octokit.Tests/Clients/RepositoryDeployKeysClientTests.cs
- Octokit.Tests/Reactive/ObservableRepositoryDeployKeysClientTests.cs
- Octokit/Clients/IRepositoryDeployKeysClient.cs
- Octokit/Clients/RepositoryDeployKeysClient.cs
As part of my work on #1120 I've added new overloads on I(Observable)RepositoryDeployKeysClient to get access by repository id.
There is some divergence between XML documentation of methods in IRepositoryDeployKeysClient and IObservableRepositoryDeployKeysClient. So I've decided 
I've added new integration tests that use …
> Add repositoryId overloads to methods on I(Observable)RepositoryDeployKeysClient

- Octokit.Reactive/Clients/IObservableRepositoriesClient.cs
- Octokit.Reactive/Clients/ObservableRepositoriesClient.cs
- Octokit.Tests.Integration/Clients/RepositoriesClientTests.cs
- Octokit.Tests/Clients/RepositoriesClientTests.cs
- Octokit.Tests/Reactive/ObservableRepositoriesClientTests.cs
- Octokit/Clients/IRepositoriesClient.cs
- Octokit/Clients/RepositoriesClient.cs
As part of my work on #1120 I've added new overloads on I(Observable)RepositoriesClient to get access by repository id.
> Add repositoryId overloads to methods on I(Observable)RepositoriesClient

- Octokit.Reactive/Clients/IObservableMergingClient.cs
- Octokit.Reactive/Clients/ObservableMergingClient.cs
- Octokit.Tests.Integration/Clients/MergingClientTests.cs
- Octokit.Tests/Clients/MergingClientTests.cs
- Octokit.Tests/Octokit.Tests.csproj
- Octokit.Tests/Reactive/ObservableMergingClientTests.cs
- Octokit/Clients/IMergingClient.cs
- Octokit/Clients/MergingClient.cs
As part of my work on #1120 I've added new overloads on I(Observable)MergingClient to get access by repository id.
There is some divergence between XML documentation of methods in IMergingClient and IObservableMergingClient. So I've decided 
I've added new integration tests that use repositoryId to work with repo that is just …
> Add repositoryId overloads to methods on I(Observable)MergingClient

- Octokit.Reactive/Clients/IObservableReferencesClient.cs
- Octokit.Reactive/Clients/ObservableReferencesClient.cs
- Octokit.Tests.Integration/Clients/ReferencesClientTests.cs
- Octokit.Tests/Clients/ReferencesClientTests.cs
- Octokit.Tests/Octokit.Tests.csproj
- Octokit.Tests/Reactive/ObservableReferencesClientTests.cs
- Octokit/Clients/IReferencesClient.cs
- Octokit/Clients/ReferencesClient.cs
As part of my work on #1120 I've added new overloads on I(Observable)ReferencesClient to get access by repository id.
There is some divergence between XML documentation of methods in IReferencesClient and IObservableReferencesClient. So I've decided 
I've added new integration tests that use repositoryId to work with repo that …
> Add repositoryId overloads to methods on I(Observable)ReferencesClient

- Octokit.Reactive/Clients/IObservableMilestonesClient.cs
- Octokit.Reactive/Clients/ObservableMilestonesClient.cs
- Octokit.Tests.Integration/Clients/MilestonesClientTests.cs
- Octokit.Tests/Clients/MilestonesClientTests.cs
- Octokit.Tests/Reactive/ObservableMilestonesClientTests.cs
- Octokit/Clients/IMilestonesClient.cs
- Octokit/Clients/MilestonesClient.cs
As part of my work on #1120 I've added new overloads on I(Observable)MilestonesClient to get access by repository id.
> Add repositoryId overloads to methods on I(Observable)MilestonesClient

- .travis.yml
- Octokit.Reactive/Clients/IObservableEventsClient.cs
- Octokit.Reactive/Clients/ObservableEventsClient.cs
- Octokit.Tests.Integration/Clients/EventsClientTests.cs
- Octokit.Tests/Clients/EventsClientTests.cs
- Octokit.Tests/Reactive/ObservableEventsClientTests.cs
- Octokit/Clients/EventsClient.cs
- Octokit/Clients/IEventsClient.cs
As part of my work on #1120 I've added new overloads on I(Observable)EventsClient to get access by repository id.
There is some divergence between XML documentation of methods in IEventsClient and IObservableEventsClient. So I've decided 
I've added new integration tests that use repositoryId to work with repo that is just a …
> Add repositoryId overloads to methods on I(Observable)EventsClient

- CustomDictionary.xml
- Octokit.Tests.Integration/Clients/CommitsClientTests.cs
- Octokit.Tests/Clients/CommitsClientTests.cs
- Octokit/Clients/CommitsClient.cs
- Octokit/Helpers/AcceptHeaders.cs
- Octokit/Models/Response/Commit.cs
- Octokit/Models/Response/Verification.cs
- Octokit/Octokit-Mono.csproj
- Octokit/Octokit-MonoAndroid.csproj
- Octokit/Octokit-Monotouch.csproj
- Octokit/Octokit-Portable.csproj
- Octokit/Octokit-netcore45.csproj
- Octokit/Octokit.csproj
Fixes #1254  
Hi @ryangribble @shiftkey  could you plz review this code :smiley: Regarding Integration test i am little confused where should i put this method, is it fine here in `CommitsClientTests` ? And what do you think of this integration test, right now this test is passing on repository which is of my test account. Is it fine here to hard code(string literals) repository parameter? Your feedback on this is much needed so that we can make improvement to this.
> Updated git data commit response with signature verification object

- Octokit.Reactive/Clients/IObservableNotificationsClient.cs
- Octokit.Reactive/Clients/ObservableNotificationsClient.cs
- Octokit.Tests/Clients/NotificationsClientTests.cs
- Octokit.Tests/Reactive/ObservableNotificationsClientTests.cs
- Octokit/Clients/INotificationsClient.cs
- Octokit/Clients/NotificationsClient.cs
As part of my work on #1120 I've added new overloads on I(Observable)NotificationsClient to get access by repository id.
I've skipped this item becuase of #1333
> Add repositoryId overloads to methods on I(Observable)NotificationsClient

- Octokit.Reactive/Clients/IObservableRepositoryCommitsClients.cs
- Octokit.Reactive/Clients/ObservableRepositoryCommitsClients.cs
- Octokit.Tests.Integration/Clients/RepositoryCommitsClientTests.cs
- Octokit.Tests/Clients/RespositoryCommitsClientTests.cs
- Octokit.Tests/Octokit.Tests.csproj
- Octokit.Tests/Reactive/ObservableRespositoryCommitsClientTests.cs
- Octokit/Clients/IRepositoryCommitsClient.cs
- Octokit/Clients/RepositoryCommitsClient.cs
As part of my work on #1120 I've added new overloads on I(Observable)RepositoryCommitsClient to get access by repository id.
There is some divergence between XML documentation of methods in IRepositoryCommitsClient and IObservableRepositoryCommitsClient. So I've decided 
I've added new integration tests that use repositoryId …
> Add repositoryId overloads to methods on I(Observable)RepositoryCommitsClient

- Octokit.Reactive/Clients/IObservableRepositoryHooksClient.cs
- Octokit.Reactive/Clients/ObservableRepositoryHooksClient.cs
- Octokit.Tests.Integration/Clients/RepositoryHooksClientTests.cs
- Octokit.Tests.Integration/fixtures/RepositoriesHooksFixture.cs
- Octokit.Tests/Clients/RepositoryHooksClientTest.cs
- Octokit.Tests/Reactive/ObservableRepositoryHooksClientTests.cs
- Octokit/Clients/IRepositoryHooksClient.cs
- Octokit/Clients/RepositoryHooksClient.cs
As part of my work on #1120 I've added new overloads on I(Observable)RepositoryHooksClient to get access by repository id.
There is some divergence between XML documentation of methods in IRepositoryHooksClient and IObservableRepositoryHooksClient. So I've decided 
I've added new integration tests that use repositoryId to work …
> Add repositoryId overloads to methods on I(Observable)RepositoryHooksClient

- .travis.yml
- Octokit.Reactive/Clients/IObservableIssuesEventsClient.cs
- Octokit.Reactive/Clients/ObservableIssuesEventsClient.cs
- Octokit.Tests.Integration/Clients/IssuesEventsClientTests.cs
- Octokit.Tests/Clients/IssuesEventsClientTests.cs
- Octokit.Tests/Reactive/ObservableIssuesEventsClientTests.cs
- Octokit/Clients/IIssuesEventsClient.cs
- Octokit/Clients/IssuesEventsClient.cs
As part of my work on #1120 I've added new overloads on I(Observable)IssuesEventsClient to get access by repository id.
There is some divergence between XML documentation of methods in IIssuesEventsClient and IObservableIssuesEventsClient. So I've decided 
I've added new integration tests that use repositoryId to work with …
> Add repositoryId overloads to methods on I(Observable)IssuesEventsClient 

- Octokit.Reactive/Clients/IObservableStarredClient.cs
- Octokit.Reactive/Clients/ObservableStarredClient.cs
- Octokit.Tests.Integration/Clients/StarredClientTests.cs
- Octokit.Tests/Clients/StarredClientTests.cs
- Octokit.Tests/Reactive/ObservableStarredClientTests.cs
- Octokit/Clients/IStarredClient.cs
- Octokit/Clients/StarredClient.cs
As part of my work on #1120 I've added new overloads on I(Observable)StarredClient to get access by repository id.
There is some divergence between XML documentation of methods in IStarredClient and IObservableStarredClient. So I've decided 
I've added new integration tests that use repositoryId to work with repo that is just …
> Add repositoryId overloads to methods on I(Observable)StarredClient

- Octokit.Reactive/Clients/IObservableIssueCommentReactionsClient.cs
- Octokit.Reactive/Clients/ObservableIssueCommentReactionsClient.cs
- Octokit.Tests.Integration/Clients/IssueCommentReactionsClientTests.cs
- Octokit.Tests/Clients/IssueCommentReactionsClientTests.cs
- Octokit.Tests/Reactive/ObservableIssueCommentReactionsClientTests.cs
- Octokit/Clients/IIssueCommentReactionsClient.cs
- Octokit/Clients/IssueCommentReactionsClient.cs
- Octokit/Helpers/ApiUrls.cs
As part of my work on #1120 I've added new overloads on I(Observable)IssueCommentReactionsClient to get access by repository id.
There is some divergence between XML documentation of methods in IIssueCommentReactionsClient and IObservableIssueCommentReactionsClient. So I've decided 
I've added new integration tests that use …
> Add repositoryId overloads to methods on I(Observable)IssueCommentReactionsClient

- Octokit.Reactive/Clients/IObservablePullRequestReviewCommentsClient.cs
- Octokit.Reactive/Clients/ObservablePullRequestReviewCommentsClient.cs
- Octokit.Tests.Integration/Clients/PullRequestReviewCommentsClientTests.cs
- Octokit.Tests/Clients/PullRequestReviewCommentsClientTests.cs
- Octokit.Tests/Reactive/ObservablePullRequestReviewCommentsClientTests.cs
- Octokit/Clients/IPullRequestReviewCommentsClient.cs
- Octokit/Clients/PullRequestReviewCommentsClient.cs
As part of my work on #1120 I've added new overloads on I(Observable)PullRequestReviewCommentsClient to get access by repository id.
> Add repositoryId overloads to methods on I(Observable)PullRequestReviewCommentsClient

- Octokit.Reactive/Clients/IObservableIssuesLabelsClient.cs
- Octokit.Reactive/Clients/ObservableIssuesLabelsClient.cs
- Octokit.Tests.Integration/Clients/IssuesLabelsClientTests.cs
- Octokit.Tests/Clients/IssuesLabelsClientTests.cs
- Octokit.Tests/Reactive/ObservableIssuesLabelsClientTests.cs
- Octokit/Clients/IIssuesLabelsClient.cs
- Octokit/Clients/IssuesLabelsClient.cs
As part of my work on #1120 I've added new overloads on I(Observable)IssuesLabelsClient to get access by repository id.
> Add repositoryId overloads to methods on I(Observable)IssuesLabelsClient

- .travis.yml
- Octokit.Reactive/Clients/IObservableWatchedClient.cs
- Octokit.Reactive/Clients/ObservableWatchedClient.cs
- Octokit.Tests.Integration/Clients/WatchedClientTests.cs
- Octokit.Tests/Clients/WatchedClientTests.cs
- Octokit.Tests/Reactive/ObservableWatchedClientTests.cs
- Octokit/Clients/IWatchedClient.cs
- Octokit/Clients/WatchedClient.cs
- Octokit/Models/Request/NewSubscription.cs
As part of my work on #1120 I've added new overloads on I(Observable)WatchedClient to get access by repository id.
There is some divergence between XML documentation of methods in IWatchedClient and IObservableWatchedClient. So I've decided 
I've added new integration tests that use repositoryId to work with repo that is just …
> Add repositoryId overloads to methods on I(Observable)WatchedClient

- Octokit.Reactive/Clients/IObservableDeploymentStatusClient.cs
- Octokit.Reactive/Clients/ObservableDeploymentStatusClient.cs
- Octokit.Tests.Integration/Clients/DeploymentStatusClientTests.cs
- Octokit.Tests/Clients/DeploymentStatusClientTests.cs
- Octokit.Tests/Reactive/ObservableDeploymentStatusClientTests.cs
- Octokit/Clients/DeploymentStatusClient.cs
- Octokit/Clients/IDeploymentStatusClient.cs
As part of my work on #1120 I've added new overloads on I(Observable)DeploymentStatusClient to get access by repository id.
There is some divergence between XML documentation of methods in IDeploymentStatusClient and IObservableDeploymentStatusClient. So I've decided 
I've added new integration tests that use repositoryId to …
> Add repositoryId overloads to methods on I(Observable)DeploymentStatusClient

- Octokit.Reactive/Clients/IObservableIssueReactionsClient.cs
- Octokit.Reactive/Clients/ObservableIssueReactionsClient.cs
- Octokit.Tests.Integration/Clients/IssueReactionsClientTests.cs
- Octokit.Tests/Clients/IssueReactionsClientTests.cs
- Octokit.Tests/Reactive/ObservableIssueReactionsClientTests.cs
- Octokit/Clients/IIssueReactionsClient.cs
- Octokit/Clients/IssueReactionsClient.cs
- Octokit/Helpers/ApiUrls.cs
As part of my work on #1120 I've added new overloads on I(Observable)IssueReactionsClient to get access by repository id.
There is some divergence between XML documentation of methods in IIssueReactionsClient and IObservableIssueReactionsClient. So I've decided 
I've added new integration tests that use repositoryId to work …
> Add repositoryId overloads to methods on I(Observable)IssueReactionsClient

- Octokit.Reactive/Clients/IObservablePullRequestReviewCommentReactionsClient.cs
- Octokit.Reactive/Clients/ObservablePullRequestReviewCommentReactionsClient.cs
- Octokit.Tests.Integration/Clients/PullRequestReviewCommentReactionsClientTests.cs
- Octokit.Tests/Clients/PullRequestReviewCommentReactionsClientTests.cs
- Octokit.Tests/Reactive/ObservablePullRequestReviewCommentReactionsClientTests.cs
- Octokit/Clients/IPullRequestReviewCommentReactionsClient.cs
- Octokit/Clients/PullRequestReviewCommentReactionsClient.cs
- Octokit/Helpers/ApiUrls.cs
As part of my work on #1120 I've added new overloads on I(Observable)PullRequestReviewCommentReactionsClient  to get access by repository id.
There is some divergence between XML documentation of methods in IPullRequestReviewCommentReactionsClient  and IObservablePullRequestReviewCommentReactionsClient . So I've decided 
I've …
> Add repositoryId overloads to methods on I(Observable)PullRequestReviewCommentReactionsClient 

- Octokit.Reactive/Clients/IObservablePullRequestsClient.cs
- Octokit.Reactive/Clients/ObservablePullRequestsClient.cs
- Octokit.Tests.Integration/Clients/PullRequestsClientTests.cs
- Octokit.Tests/Clients/PullRequestsClientTests.cs
- Octokit.Tests/Reactive/ObservablePullRequestsClientTests.cs
- Octokit/Clients/IPullRequestsClient.cs
- Octokit/Clients/PullRequestsClient.cs
As part of my work on #1120 I've added new overloads on I(Observable)PullRequestsClient to get access by repository id.
> Add repositoryId overloads to methods on I(Observable)PullRequestsClient

- Octokit.Reactive/Clients/IObservableRepoCollaboratorsClient.cs
- Octokit.Reactive/Clients/ObservableRepoCollaboratorsClient.cs
- Octokit.Tests.Integration/Clients/RepositoryCollaboratorClientTests.cs
- Octokit.Tests/Clients/RepoCollaboratorsClientTests.cs
- Octokit.Tests/Reactive/ObservableRepoCollaboratorsClientTests.cs
- Octokit/Clients/IRepoCollaboratorsClient.cs
- Octokit/Clients/RepoCollaboratorsClient.cs
- Octokit/Helpers/ApiUrls.cs
_This PR created instead of #1305 (I've renamed branch :smile: )_
As part of my work on #1120 I've added new overloads on I(Observable)RepoCollaboratorsClient to get access by repository id.
I've found out that there is the pair (owner, name) is used to identify repository. But some clients use pair (owner, repo) and it's some type of inconsistency.
So I've decided to fix these cases during my work on #1120.
There is some divergence between XML documentation of methods in IRepoCollaboratorsClient and IObservableRepoCollaboratorsClient. So I've decided 
I've added …
> Add repositoryId overloads to methods on I(Observable)RepoCollaboratorsClient

- Octokit.Tests.Conventions/Exception/MissingPublicParameterlessCtorException.cs
- Octokit.Tests.Conventions/ModelTests.cs
- Octokit.Tests.Conventions/Octokit.Tests.Conventions.csproj
- Octokit/Models/Response/PunchCard.cs
- Octokit/Models/Response/RepositoryLanguage.cs
Fixes #1413
`PunchCard` and `RepositoryLanguage` classes were missing the `ctor` and failing this test.  Technically they don't actually need it since they are not being deserialized from json, but populated from basic data types but in the interest of consistency and ease of testing I've added the `ctor` to these 2 classes
> Add convention test to ensure all response models have a public parameterless ctor

- Octokit.Reactive/Clients/IObservableCommitCommentReactionsClient.cs
- Octokit.Reactive/Clients/ObservableCommitCommentReactionsClient.cs
- Octokit.Tests.Integration/Clients/CommitCommentReactionsClientTests.cs
- Octokit.Tests/Clients/CommitCommentReactionsClientTests.cs
- Octokit.Tests/Reactive/ObservableCommitCommentReactionsClientTests.cs
- Octokit/Clients/CommitCommentReactionsClient.cs
- Octokit/Clients/ICommitCommentReactionsClient.cs
- Octokit/Helpers/ApiUrls.cs
As part of my work on #1120 I've added new overloads on I(Observable)CommitCommentReactionsClient to get access by repository id.
There is some divergence between XML documentation of methods in ICommitCommentReactionsClient and IObservableCommitCommentReactionsClient. So I've decided 
I've added new integration tests that use …
> Add repositoryId overloads to methods on I(Observable)CommitCommentReactionsClient

- Octokit.Reactive/Clients/IObservableIssuesClient.cs
- Octokit.Reactive/Clients/ObservableIssuesClient.cs
- Octokit.Tests.Integration/Clients/IssuesClientTests.cs
- Octokit.Tests/Clients/IssuesClientTests.cs
- Octokit.Tests/Reactive/ObservableIssuesClientTests.cs
- Octokit/Clients/IIssuesClient.cs
- Octokit/Clients/IssuesClient.cs
As part of my work on #1120 I've added new overloads on I(Observable)IssuesClient to get access by repository id.
There is some divergence between XML documentation of methods in IIssuesClient and IObservableIssuesClient. So I've decided 
I've added new integration tests that use repositoryId to work with repo that is just a …
> Add repositoryId overloads to methods on I(Observable)IssuesClient

- Octokit.Reactive/Clients/IObservableCommitsClient.cs
- Octokit.Reactive/Clients/ObservableCommitsClient.cs
- Octokit.Tests.Integration/Clients/CommitsClientTests.cs
- Octokit.Tests/Clients/CommitsClientTests.cs
- Octokit.Tests/Reactive/ObservableCommitsClientTests.cs
- Octokit/Clients/CommitsClient.cs
- Octokit/Clients/ICommitsClient.cs
As part of my work on #1120 I've added new overloads on I(Observable)CommitsClient to get access by repository id.
There is some divergence between XML documentation of methods in ICommitsClient and IObservableCommitsClient. So I've decided 
I've added new integration tests that use repositoryId to work with repo that is just …
> Add repositoryId overloads to methods on I(Observable)CommitsClient

- .travis.yml
- Octokit.Reactive/Clients/IObservableTagsClient.cs
- Octokit.Reactive/Clients/ObservableTagsClient.cs
- Octokit.Tests.Integration/Clients/TagsClientTests.cs
- Octokit.Tests.Integration/Octokit.Tests.Integration.csproj
- Octokit.Tests/Clients/TagsClientTests.cs
- Octokit.Tests/Octokit.Tests.csproj
- Octokit.Tests/Reactive/ObservableTagsClientTests.cs
- Octokit/Clients/ITagsClient.cs
- Octokit/Clients/TagsClient.cs
As part of my work on #1120 I've added new overloads on I(Observable)TagsClient to get access by repository id.
There is some divergence between XML documentation of methods in ITagsClient and IObservableTagsClient. So I've decided 
I've added new integration tests that use repositoryId to work with repo that is just a full …
> Add repositoryId overloads to methods on I(Observable)TagsClient

- .travis.yml
- Octokit.Reactive/Clients/IObservableBlobsClient.cs
- Octokit.Reactive/Clients/ObservableBlobClient.cs
- Octokit.Tests.Integration/Clients/BlobClientTests.cs
- Octokit.Tests/Clients/BlobClientTests.cs
- Octokit.Tests/Reactive/ObservableBlobClientTests.cs
- Octokit/Clients/BlobsClient.cs
- Octokit/Clients/IBlobsClient.cs
As part of my work on #1120 I've added new overloads on I(Observable)BlobsClient to get access by repository id.
There is some divergence between XML documentation of methods in IBlobsClient and IObservableBlobsClient. So I've decided 
I've added new integration tests that use repositoryId to work with repo that is just a full …
> Add repositoryId overloads to methods on I(Observable)BlobsClient

- .travis.yml
- Octokit.Reactive/Clients/IObservableRepositoryPagesClient.cs
- Octokit.Reactive/Clients/ObservableRepositoryPagesClient.cs
- Octokit.Tests.Integration/Clients/RepositoryPagesClientTests.cs
- Octokit.Tests/Clients/RepositoryPagesClientTests.cs
- Octokit.Tests/Reactive/ObservableRepositoryPagesClientTests.cs
- Octokit/Clients/IRepositoryPagesClient.cs
- Octokit/Clients/RepositoryPagesClient.cs
As part of my work on #1120 I've added new overloads on I(Observable)RepositoryPagesClient to get access by repository id.
There is some divergence between XML documentation of methods in IRepositoryPagesClient and IObservableRepositoryPagesClient. So I've decided 
I've added only one new integration test for now because of …
> Add repositoryId overloads to methods on I(Observable)RepositoryPagesClient

- Octokit.Tests.Integration/Clients/TagsClientTests.cs
- Octokit.Tests/Clients/TagsClientTests.cs
- Octokit/Clients/TagsClient.cs
- Octokit/Models/Response/GitTag.cs
Fixes #1256 
Updated `GitTag` Response class.
Updated `TagsClient` Class with new Accept Header.
Added Integration Test.
> Updated Git Data Tag With Signature Verification

- Octokit.Reactive/Clients/IObservableRepositoryForksClient.cs
- Octokit.Reactive/Clients/ObservableRepositoryForksClient.cs
- Octokit.Tests.Integration/Clients/RepositoryForksClientTests.cs
- Octokit.Tests/Clients/RepositoryForksClientTests.cs
- Octokit.Tests/Reactive/ObservableRepositoryForksClientTests.cs
- Octokit/Clients/IRepositoryForksClient.cs
- Octokit/Clients/RepositoryForksClient.cs
As part of my work on #1120 I've added new overloads on I(Observable)RepositoryForksClient to get access by repository id.
There is some divergence between XML documentation of methods in IRepositoryForksClient and IObservableRepositoryForksClient. So I've decided 
I've added new integration tests that use repositoryId to work …
> Add repositoryId overloads to methods on I(Observable)RepositoryForksClient

- Octokit.Reactive/Clients/IObservableCommitStatusClient.cs
- Octokit.Reactive/Clients/ObservableCommitStatusClient.cs
- Octokit.Tests.Integration/Clients/CommitStatusClientTests.cs
- Octokit.Tests/Clients/CommitStatusClientTests.cs
- Octokit.Tests/Octokit.Tests.csproj
- Octokit.Tests/Reactive/ObservableCommitStatusClientTests.cs
- Octokit/Clients/CommitStatusClient.cs
- Octokit/Clients/ICommitStatusClient.cs
As part of my work on #1120 I've added new overloads on I(Observable)CommitStatusClient to get access by repository id.
There is some divergence between XML documentation of methods in ICommitStatusClient and IObservableCommitStatusClient. So I've decided 
I've added new integration tests that use repositoryId to work with …
> Add repositoryId overloads to methods on I(Observable)CommitStatusClient

- Octokit.Tests.Integration/Clients/SearchClientTests.cs
- Octokit/Helpers/StringExtensions.cs
Fixes #1406
I've kept the failing test around redirected repositories, but I'm not sure when the backend fix will land for the search APIs.
cc @dsplaisted, who found the fix originally
> search repos with underscore in name

- Octokit.Reactive/Clients/IObservableRepositoryPagesClient.cs
- Octokit.Reactive/Clients/ObservableRepositoryPagesClient.cs
- Octokit.Tests/Clients/RepositoryPagesClientTests.cs
- Octokit.Tests/Reactive/ObservableRepositoryPagesClientTests.cs
- Octokit/Clients/IRepositoryPagesClient.cs
- Octokit/Clients/RepositoryPagesClient.cs
- Octokit/Helpers/AcceptHeaders.cs
- Octokit/Models/Response/Page.cs
> GitHub Pages Preview API Enhancements 

- Octokit.Reactive/Clients/IObservableRepositoriesClient.cs
- Octokit.Reactive/Clients/ObservableRepositoriesClient.cs
- Octokit/Clients/IRepositoriesClient.cs
- Octokit/Clients/RepositoriesClient.cs
- Octokit/Models/Request/BranchUpdate.cs
- Octokit/Models/Response/Branch.cs
- Octokit/Models/Response/BranchProtection.cs
Protected Branches Preview API has had pretty large scale (breaking) changes made (see #1407).  During the preview period both the new and old implementations are available but once preview period ends, support for the older implementation will be removed.
I have started working on the new implementation, but incase that doesn't make the next release this PR will at the very least give some heads up to users of the first preview implementation, that it is not going to be supported by GitHub API at some point in the future
> Flag obsolete warnings for initial Protected Branch API preview functionality

- Octokit.Reactive/Clients/IObservableIssueTimelineClient.cs
- Octokit.Reactive/Clients/IObservableIssuesClient.cs
- Octokit.Reactive/Clients/ObservableIssueTimelineClient.cs
- Octokit.Reactive/Clients/ObservableIssuesClient.cs
- Octokit.Reactive/Octokit.Reactive-Mono.csproj
- Octokit.Reactive/Octokit.Reactive-MonoAndroid.csproj
- Octokit.Reactive/Octokit.Reactive-Monotouch.csproj
- Octokit.Reactive/Octokit.Reactive.csproj
- Octokit.Tests.Integration/Clients/IssueTimelineClientTests.cs
- Octokit.Tests.Integration/Octokit.Tests.Integration.csproj
- Octokit.Tests.Integration/Reactive/ObservableIssueTimelineClientTests.cs
- Octokit.Tests/Clients/IssueTimelineClientTests.cs
- Octokit.Tests/Octokit.Tests.csproj
- Octokit.Tests/Reactive/ObservableIssueTimelineClientTests.cs
- Octokit/Clients/IIssueTimelineClient.cs
- Octokit/Clients/IIssuesClient.cs
- Octokit/Clients/IssueTimelineClient.cs
- Octokit/Clients/IssuesClient.cs
- Octokit/Helpers/AcceptHeaders.cs
- Octokit/Helpers/ApiUrls.cs
- Octokit/Models/Response/EventInfo.cs
- Octokit/Models/Response/RenameInfo.cs
- Octokit/Models/Response/SourceInfo.cs
- Octokit/Models/Response/TimelineEventInfo.cs
- Octokit/Octokit-Mono.csproj
- Octokit/Octokit-MonoAndroid.csproj
- Octokit/Octokit-Monotouch.csproj
- Octokit/Octokit-Portable.csproj
- Octokit/Octokit-netcore45.csproj
- Octokit/Octokit.csproj
Adding the Issue Timeline [API](https://developer.github.com/v3/issues/timeline/) client as it is now in preview (and we have a need for it for an internal project).
Fixes #1436
> Implement Issue Timeline preview API

- Octokit.Tests/Models/OrganizationTests.cs
- Octokit.Tests/Octokit.Tests.csproj
- Octokit/Models/Response/Account.cs
Make Collaborators, DiskUsage and PrivateGists properties nullable as they may be returned as null when fetching an organization of which the user is a member by not an owner.
> Fix issue #1446: Organization can fail deserialization when user is not an org owner.:

- Octokit.Tests.Integration/Clients/PullRequestsClientTests.cs
- Octokit/Models/Request/PullRequestUpdate.cs
Fixes #1449 
Added new `base` property on `PullRequestUpdate`
Updated existing `PullRequestClientTests.CanUpdate()` and `PullRequestClientTests.CanUpdateWithRepositoryId()` tests to change the base branch and assert the result
> Support changing PullRequest base branch

- Octokit.Reactive/Clients/IObservableRepositoryBranchesClient.cs
- Octokit.Reactive/Clients/ObservableRepositoryBranchesClient.cs
- Octokit.Tests.Integration/Clients/RepositoryBranchesClientTests.cs
- Octokit.Tests.Integration/Helpers/OrganizationRepositoryWithTeamContext.cs
- Octokit.Tests.Integration/Helpers/RepositoryContext.cs
- Octokit.Tests.Integration/Octokit.Tests.Integration.csproj
- Octokit.Tests/Clients/RepositoryBranchesClientTests.cs
- Octokit.Tests/Reactive/ObservableRepositoryBranchesClientTests.cs
- Octokit/Clients/IRepositoryBranchesClient.cs
- Octokit/Clients/RepositoryBranchesClient.cs
- Octokit/Helpers/ApiUrls.cs
- Octokit/Models/Request/BranchProtectionUpdate.cs
- Octokit/Models/Request/BranchUpdate.cs
- Octokit/Models/Response/Branch.cs
- Octokit/Models/Response/BranchProtection.cs
- Octokit/Octokit-Mono.csproj
- Octokit/Octokit-MonoAndroid.csproj
- Octokit/Octokit-Monotouch.csproj
- Octokit/Octokit-Portable.csproj
- Octokit/Octokit-netcore45.csproj
- Octokit/Octokit.csproj
Closes #1407 
The updates to Protected Branches preview API added a significant number of new endpoints allowing granularity in setting each segment of the branch protection settings separately.  
For an MVP (Minimum Viable Product) approach, this PR implements only the top level methods, which will enable octokit.net users to manage all aspects of BranchProtection from that top level.  If there is need/desire, the other more granular methods can be added in separate PRs
This PR implements the following methods:
``` csharp
Task<BranchProtectionSettings> GetBranchProtection(string owner, string name, string branch);
Task<BranchProtectionSettings> GetBranchProtection(int repositoryId, string branch);
Task<BranchProtectionSettings> UpdateBranchProtection(string owner, string name, string …
```
> Protected Branches updates - main methods

- Octokit.Reactive/Clients/IObservableRepositoriesClient.cs
- Octokit.Reactive/Clients/IObservableRepositoryBranchesClient.cs
- Octokit.Reactive/Clients/ObservableRepositoriesClient.cs
- Octokit.Reactive/Clients/ObservableRepositoryBranchesClient.cs
- Octokit/Clients/IRepositoriesClient.cs
- Octokit/Clients/IRepositoryBranchesClient.cs
- Octokit/Clients/RepositoriesClient.cs
- Octokit/Clients/RepositoryBranchesClient.cs
- Octokit/Models/Request/BranchUpdate.cs
- Octokit/Models/Response/Branch.cs
- Octokit/Models/Response/BranchProtection.cs
- fix a few places previuosly missed 
- reword to direct users to the new equivalent branch protection methods
> Fix obsolete warnings for branch protection changes

- Octokit.Reactive/Clients/IObservableUsersClient.cs
- Octokit.Reactive/Clients/ObservableMiscellaneousClient.cs
- Octokit.Reactive/Clients/ObservableUsersClient.cs
- Octokit/Clients/IUsersClient.cs
- Octokit/Clients/UsersClient.cs
- Octokit/Helpers/ApiExtensions.cs
- Octokit/Helpers/ApiUrls.cs
- Octokit/Http/ApiConnection.cs
- Octokit/Http/IApiConnection.cs
- Octokit/Models/Request/SearchIssuesRequest.cs
- Octokit/Models/Request/SearchRepositoriesRequest.cs
- Octokit/Models/Response/CompareResult.cs
As per the normal process this PR removes any `[Obsolete]` items that have been obsolete for at least 2 releases
- Remove previously obsoleted UsersClient.Keys property
- Remove previously obsoleted IConnection.GetRedirect and IApiConnectio
- Remove previously obsoleted IssueTypeQualifier.PR enum value
- Remove previously obsoleted mis-spelled Language enum values
- Remove previously obsoleted ObservableMiscellaneousClient ctor
- Remove previously obsoleted CompareResult.MergedBaseCommit property
- Remove previously obsoleted ApiUrls.Blob method
> Spring cleaning

- .gitignore
- .travis.yml
- Octokit.Core.sln
- Octokit.Next.Tests/CalculatorTests.cs
- Octokit.Next.Tests/Octokit.Next.Tests.xproj
- Octokit.Next.Tests/Properties/AssemblyInfo.cs
- Octokit.Next.Tests/project.json
- Octokit.Next/Calculator.cs
- Octokit.Next/Octokit.Next.xproj
- Octokit.Next/Properties/AssemblyInfo.cs
- Octokit.Next/project.json
- appveyor.yml
- build.cmd
- build.fsx
- build.sh
First step of #1419.
It looks like AppVeyor has the dotnet CLI installed in the image so no need to download it.  
Also, that's really as simple as it gets. Maybe you wanted something more ... realistic.
Made some comments in the F# code where I'm really not sure if that's The Way To Do Things.
> Get a .NET Core project to build in AppVeyor and Travis

- Octokit.Tests.Integration/Clients/PullRequestsClientTests.cs
- Octokit/Models/Request/MergePullRequest.cs
Fixes #1474 
Add `MergeMethod` property to `MergePullRequest` request object
Added integration tests for Merge, Squash and Rebase options
Obsoleted previous `Squash` bool parameter - also tested that this property does still work if specified (and also that if the new MergeMethod property is specified, it overrides anything specified by the Squash boolean).  Therefore it is safe to leave this there for the time being, however marking it obsolete means we can remove it in a couple of releases
> Add MergeMethod property to PR merge request

- Octokit.Tests.Integration/Clients/RepositoriesClientTests.cs
- Octokit.Tests.Integration/Reactive/ObservableRepositoriesClientTests.cs
- Octokit.Tests/Clients/RepositoriesClientTests.cs
- Octokit.Tests/Reactive/ObservableRepositoriesClientTests.cs
- Octokit/Models/Request/PublicRepositoryRequest.cs
We changed all repositoryId parameters from `int` to `long` in #1445 and missed this one.
The `ctor` on `PublicRepositoryRequest` takes a "since" parameter of type `int`.
If anyone is passing in a `repository.Id` (now a `long`) into this `ctor` it will result in a compilation error.
This PR adds a new `ctor` to PublicRepositoryRequest taking "since" parameter as a `long`, and obsoletes the old `ctor`.  I thought about simpl keeping the `int` `ctor` around indefinitely but I think in general we want to encourage/inform users that `repositoryId` (and any related uses, such as the "Since" parameter) are now `long` across the board, so I decided to start the process of removing the old `int` parameter via obsoletion.
Also updated any tests that use the `ctor` to use the new one instead...
> Change PublicRepositoryRequest ctor to take long for "since" parameter

- Octokit/Clients/Enterprise/EnterpriseProbe.cs
- Octokit/Clients/MigrationsClient.cs
- Octokit/Clients/PullRequestsClient.cs
- Octokit/Clients/RepoCollaboratorsClient.cs
- Octokit/Clients/StatisticsClient.cs
- Octokit/Http/HttpClientAdapter.cs
Adding missing ConfigureAwait + put on single line await &
ConfigureAwait
Fixes #1483
> Fixing Async Deadlock

- Octokit.Tests.Integration/Clients/RepositoriesClientTests.cs
- Octokit.Tests/Clients/RepositoriesClientTests.cs
- Octokit.Tests/Reactive/ObservableRepositoriesClientTests.cs
- Octokit/Clients/RepositoriesClient.cs
- Octokit/Models/Request/NewRepository.cs
- Octokit/Models/Request/RepositoryUpdate.cs
- Octokit/Models/Response/Repository.cs
Fixes #1475 
(confirmed no other methods like GetAllForCurrent, GetAllPublic, GetAllForOrg return the new fields even when accepts header is provided, so only the individual Get Repository call needs to be implemented)
(support confirmed this was a documentation error and Create Repository call does not support these parameters)
I've had to contact GitHub support as the new fields aren't actually being returned but I'm pretty sure everything is correct on my side...
> Add repository settings to configure PR merge methods

- Octokit.Tests.Integration/Clients/GitHubClientTests.cs
- Octokit.Tests.Integration/Clients/IssuesEventsClientTests.cs
- Octokit.Tests.Integration/Clients/PullRequestsClientTests.cs
- Octokit.Tests.Integration/Clients/RepositoryTrafficClientTests.cs
- Octokit.Tests.Integration/Reactive/ObservableEventsClientTests.cs
- ReleaseNotes.md
- SolutionInfo.cs
Aiming to ship this **Thursday 6 October** AEST. Running through the test suite today/tomorrow.
> Release 0.23 - Thumbs Up

- Octokit/Models/Response/Milestone.cs
Adding missing Milestone fields as per #1358
> Missing Milestone fields

- Octokit/Exceptions/ApiException.cs
- Octokit/Exceptions/RateLimitExceededException.cs
- Octokit/Exceptions/RepositoryExistsException.cs
- Octokit/Exceptions/RepositoryFormatException.cs
- Octokit/Exceptions/RepositoryWebHookConfigException.cs
- Octokit/Exceptions/TwoFactorAuthorizationException.cs
- Octokit/Exceptions/TwoFactorChallengeFailedException.cs
- Octokit/Http/RateLimit.cs
> Add missing `SecurityCritical` attribute

- Octokit.Reactive/Clients/IObservableEventsClient.cs
- Octokit.Reactive/Clients/ObservableEventsClient.cs
- Octokit.Tests.Integration/Reactive/ObservableEventsClientTests.cs
- Octokit.Tests/Clients/EventsClientTests.cs
- Octokit.Tests/Reactive/ObservableEventsClientTests.cs
- Octokit/Clients/EventsClient.cs
- Octokit/Clients/IEventsClient.cs
#1251 threw me for a loop for a bit.
It turns out this API deals in `IssueEvent` not `Activity`.
> Correcting return type in ObservableEventsClient

- Octokit.Tests.Integration/Clients/RepositoryContentsClientTests.cs
- Octokit.Tests/Clients/RepositoryContentsClientTests.cs
- Octokit.Tests/Reactive/ObservableRepositoryContentsClientTests.cs
- Octokit/Models/Request/CreateFileRequest.cs
Fixes #1143.
Since 1.0 has not been reached yet, I made the fix minimal and as I think the method should have been originally, but there is a breaking change.
If you want to mitigate the breaking change I propose three ways:
1. `Content` contains base64 content. Breaking change on `Content.Get()`. Could add corresponding ctors with bool if convert to base64.
2. Insert base class `Base64CreateFileRequest` with a virtual `Content` property wich contains base64 content. `CreateFileRequest` overrides it and provides decoded content.
3. Add `SerializeIgnore` and `SerializeName` attributes, add first on `Content` and second on new property `Base64Content`. When set, `Content` convert value to base64 and set `Base64Content`.
> Allow base64 content for create/update file

- Octokit.Reactive/Clients/IObservablePullRequestsClient.cs
- Octokit.Reactive/Clients/ObservablePullRequestReviewCommentsClient.cs
- Octokit.Reactive/Clients/ObservablePullRequestsClient.cs
- Octokit.Tests.Integration/Clients/PullRequestReviewCommentReactionsClientTests.cs
- Octokit.Tests.Integration/Clients/PullRequestReviewCommentsClientTests.cs
- Octokit.Tests/Reactive/ObservablePullRequestReviewCommentsClientTests.cs
- Octokit/Clients/IPullRequestsClient.cs
- Octokit/Clients/PullRequestsClient.cs
Fixes  #1511  
Change references of Comment to ReviewComment based on the API change
> [WIP] Rename Comment to ReviewComment

- docs/getting-started.md
Supports #1142. 
If you'd like to break this PR up at all to get some of the basic info in, let me know and I'll switch it up.
> Add ApiInfo Rate limiting description to Getting Started

- Octokit.Reactive/Clients/IObservableIssueCommentsClient.cs
- Octokit.Reactive/Clients/ObservableIssueCommentsClient.cs
- Octokit.Tests/Clients/IssueCommentsClientTests.cs
- Octokit.Tests/Reactive/ObservableIssueCommentsClientTests.cs
- Octokit/Clients/IIssueCommentsClient.cs
- Octokit/Clients/IssueCommentsClient.cs
- Octokit/Models/Request/IssueCommentRequest.cs
- Octokit/Models/Response/IssueComment.cs
- Octokit/Octokit-Mono.csproj
- Octokit/Octokit-MonoAndroid.csproj
- Octokit/Octokit-Monotouch.csproj
- Octokit/Octokit-Portable.csproj
- Octokit/Octokit-netcore45.csproj
- Octokit/Octokit.csproj
Original Issue : https://github.com/octokit/octokit.net/issues/1500
Hi,
I added 4 methods to `IssueCommentsClient.cs`.
But there are two duplicated options which named `IssueCommentSort` and `PullRequestReviewCommentSort`. I think these types can be merged like a `SortDirection` option.
Thanks.
> Fix IssueCommentClient #1500

- CODE_OF_CONDUCT.md
- README.md
If you're not familiar with it, the [Contributor Covenant](http://contributor-covenant.org/) is a good starting point for communities to identify the values they uphold, as well as what happens when conflicts arise.
Opening this up to start a discussion on what should be in it.
- ~~[ ] discussion about things to add/change/remove~~
- ~~[ ] introduce preamble which is Octokit-specific~~
> introduce Code of Conduct

- Octokit.Tests/Exceptions/AbuseExceptionTests.cs
- Octokit.Tests/Http/ConnectionTests.cs
- Octokit.Tests/Octokit.Tests.csproj
- Octokit/Exceptions/AbuseException.cs
- Octokit/Http/Connection.cs
- Octokit/Octokit-Mono.csproj
- Octokit/Octokit-MonoAndroid.csproj
- Octokit/Octokit-Monotouch.csproj
- Octokit/Octokit-Portable.csproj
- Octokit/Octokit-netcore45.csproj
- Octokit/Octokit.csproj
Resolves #1527.
This aims to Add and `AbuseException` that inherits from `ForbiddenException`. 
This exception will be thrown in place of the `ForbiddenException` when an abuse condition occurs. 
Additionally, the `AbuseException` will contain the `Retry-After` header field as an `int`.
> Introduce AbuseException

- Octokit/Models/Response/EventInfo.cs
Fixes Issue #1502.
Updates the EventInfo list to the latest values published in [GitHub API](https://developer.github.com/v3/issues/events/), plus an undocumented one we stumbled across.
PR #1504 is a much better long-term solution, but in the mean time this is blocking us from parsing Git diffs using OctoKit.  Thought we'd share the fix.
> Add Missing Event Types

- Octokit.Tests.Integration/Clients/PullRequestsClientTests.cs
- Octokit/Models/Response/Issue.cs
- Octokit/Models/Response/PullRequest.cs
added the Id property for PullRequest model
> add Id for PullRequest.cs

- Octokit/Models/Response/Repository.cs
As discussed in #1470 this PR adds back the `SubscribersCount` property on `Repository` which is the number of "watchers".  This field was removed in the past however it does contain the correct value and would avoid additional API calls to the `WatchedClient` to retrieve this info.
Also added some other fields that are missing in octokit.net such as `Size` and `HasPages`
Fixes #1470
> Add missing fields to Repository class - HasPages, SubscribersCount, Size

- Octokit.Tests/Http/ConnectionTests.cs
- Octokit/Exceptions/ApiException.cs
Resolves #1529.
If an API Error is returned and the message is empty, the default error message is not shown, and instead an empty string is shown.
##Fix
Per discussion on #1529, we'll resolve this by modifying ApiErrorMessageSafe to return null when an empty or whitespace string is provided.
> Update ApiErrorMessageSafe to return null for empty and whitespace strings

- Octokit/Models/Response/AccountType.cs
The GitHub API is apparently now returning "Bot" account types.  This was causing a deserialization exception when encountering repositories that had a "bot" user (perhaps related to the new API integrations features) performing actions.  Example here: https://github.com/depfutest/devfu/issues/2
> Add new AccountType "Bot" to prevent deserialization errors

- GitVersion.yml
Closes #1554.
Right now we use GitVersion with the default settings.
`master`, by default, uses the [Continuous Delivery](https://gitversion.readthedocs.io/en/latest/reference/continuous-delivery/) mode which generates the same version for all the commits until we tag the repo with that version.
Since we might want to publish pre-release packages in the future, we could take advantage of the other mode named [Continuous Deployment](https://gitversion.readthedocs.io/en/latest/reference/continuous-deployment/). This mode generates a new version for each commit. To avoid the version going through the roof, a pre-release tag is forced with this mode. By default, the tag for `master` is `ci`. As we used the `alpha` one for the pre-release NuGet package, I thought we might use the same.
Also, …
> add GitVersion configuration file

- .travis.yml
- Octokit/Models/Response/RepositoryTrafficClone.cs
- Octokit/Models/Response/RepositoryTrafficView.cs
- appveyor.yml
Fixes #1558.
The API used to send times as number of seconds from Unix epoch time.
This has changed and is now ISO 8601.
> React to change in the way the RepositoryTraffic API communicates time

- Octokit.Tests.Integration/Clients/RepositoriesClientTests.cs
- Octokit.Tests/Clients/RepositoriesClientTests.cs
- Octokit.Tests/Models/RepositoryUpdateTests.cs
- Octokit.Tests/Reactive/ObservableRepositoriesClientTests.cs
- Octokit/Models/Request/RepositoryUpdate.cs
This is a PR to remove obsoleted paramless constructor of RepositoryUpdate, it is related to issue #1568
> Remove obsoleted repository update constructor of RepositoryUpdate

- Octokit.Tests.Integration/Clients/IssueTimelineClientTests.cs
- Octokit.Tests.Integration/Reactive/ObservableIssueTimelineClientTests.cs
- Octokit/Models/Response/EventInfo.cs
Fixes #1559 
Fixes #1525
This fix adds 3 more undocumented event types in the TimeLine API: `linecommented` `commitcommented` and `reviewed`
Also added an integration test that will hopefully help with identifying more missing values in the future, it now runs against the most recent 20 closed PRs and 20 open issues in a heavy activity repository.  
I picked [Microsoft/vscode](https://github.com/Microsoft/vscode) 😀 the theory being that it's a very active repository, and the most recent activity is more likely to have new event types in their timeline/event stream.
The strategy seemed to work, as I discovered 2 extra event types that hadn't been reported by users as causing a crash yet 😸 
In the short term, we will still throw an exception whenever we encounter an event type not …
> Fix Issue Timeline exceptions by adding new EventInfoState values

- docs/releases.md
Fixes #1565 by updating `ReleaseClient` code samples to `client.Repository.Release` instead of previously `client.Release`
> Update ReleaseClient code samples in documentation

- Octokit.Reactive/Octokit.Reactive.csproj
- Octokit/Octokit.csproj
- appveyor.yml
- build.ps1
- build.sh
- build/Context.cs
- build/Lifetime.cs
- build/Tasks/Build.cs
- build/Tasks/Default.cs
- build/Tasks/Package.cs
- build/Tasks/TestSourceLink.cs
- build/Utilities/CakeExtensions.cs
For our 2 library projects,
- Set PDB option to embedded
- add sourcelink MSBuild tools (should run automatically)
- add sourcelink test MSBuild tool (should verify the sourcelink worked ok)
> Add sourcelink support

- Octokit.Tests/Clients/RepoCollaboratorsClientTests.cs
- Octokit/Clients/RepoCollaboratorsClient.cs
- appveyor.yml
Fixes #1575
This PR removes the "swallowing" of exceptions in the overloaded `RepoCollaboratorsClient.Add` method making it possible to know what went wrong in case of an exception happening.
> Surface exceptions in RepoCollaboratorsClient.Add method

- Octokit.Tests/Http/ApiInfoTests.cs
- Octokit/Http/ApiInfo.cs
Fixes #1509 
`ApiInfo.Clone()` previously returned `null` if any of the child properties of the object to clone were `null`.  
I encountered a situation where there was no ETag header in an API response, which caused the "Last Api Info" object to be `null` due to this logic.
With this change, the `Clone()` method will clone whatever fields do exist, which means we should now be correctly providing the "Last Api Info" in more cases.
> Cloning ApiInfo object should work when some fields are null

- samples/linqpad-samples/1-introducing-octokit.linq
- samples/linqpad-samples/10-search-issues.linq
- samples/linqpad-samples/2-releases.linq
- samples/linqpad-samples/3-browse-repositories.linq
- samples/linqpad-samples/4-observable-browse-repositories.linq
- samples/linqpad-samples/5-interact-with-git-database.linq
- samples/linqpad-samples/6-create-repository.linq
- samples/linqpad-samples/7-search-for-repos.linq
- samples/linqpad-samples/8-gists.linq
- samples/linqpad-samples/9-issues.linq
This resolves #1592 - LINQPad doesn't understand how to restore this unlisted package and it's not actually needed in the samples.
> Remove Rx-Main dependency from samples

- Octokit/Models/Response/EventInfo.cs
The problem described in PR #1536 / Issue #1502 cropped up again.  Apparently GitHub has added more event types.  
This change incorporates all of the states in the [GitHub API](https://developer.github.com/v3/issues/events/) plus some undocumented ones we encountered during prior testing.  
I put them in the order that they're listed in the GitHub API so you can easily skim the list and compare.
> Adding RemovedFromProject and other missing EventInfoState types.

- Octokit.Reactive/Clients/IObservableRepositoryBranchesClient.cs
- Octokit.Reactive/Clients/ObservableRepositoryBranchesClient.cs
- Octokit.Tests.Integration/Clients/RepositoryBranchesClientTests.cs
- Octokit.Tests.Integration/Helpers/OrganizationRepositoryWithTeamContext.cs
- Octokit.Tests/Clients/RepositoryBranchesClientTests.cs
- Octokit.Tests/Reactive/ObservableRepositoryBranchesClientTests.cs
- Octokit/Clients/IRepositoryBranchesClient.cs
- Octokit/Clients/RepositoryBranchesClient.cs
- Octokit/Helpers/ApiUrls.cs
- Octokit/Models/Request/BranchProtectionUpdate.cs
- Octokit/Models/Response/BranchProtection.cs
This replaces the `IncludeAdmins` property on sub-classes.
Fixes #1597 
TODO:
Breaking changes:
- `public BranchProtectionSettingsUpdate(BranchProtectionRequiredStatusChecksUpdate requiredStatusChecks, BranchProtectionPushRestrictionsUpdate restrictions)` ctor is now `public BranchProtectionSettingsUpdate(BranchProtectionRequiredStatusChecksUpdate requiredStatusChecks, BranchProtectionPushRestrictionsUpdate restrictions, bool enforceAdmins)`
> Add BranchProtection.EnforceAdmins object

- docs/releases.md
This is a small fix to the create release section in the documentation. It should be ReleaseNew not ReleaseUpdate when creating a release.
> ReleaseUpdate should be NewRelease in create release section

- Octokit.Tests.Integration/Clients/AuthorizationClientTests.cs
- Octokit.Tests.Integration/Clients/PullRequestReviewCommentsClientTests.cs
- Octokit.Tests.Integration/Clients/ReleasesClientTests.cs
- Octokit.Tests.Integration/Clients/UserGpgKeysClientTests.cs
- Octokit.Tests/Clients/RepositoriesClientTests.cs
- Octokit.Tests/Clients/TeamsClientTests.cs
- Octokit.Tests/Http/RedirectHandlerTests.cs
- Octokit.Tests/Reactive/ObservableRepositoryCommentsClientTests.cs
- Octokit.Tests/Reactive/ObservableRepositoryCommitsClientTests.cs
- Octokit.Tests/Reactive/ObservableRepositoryPagesClientTests.cs
- Octokit.Tests/Reactive/ObservableTeamsClientTests.cs
- Octokit/Clients/TeamsClient.cs
I found a number of tests that were checking for Null/empty string on parameters, that were always passing due to not `await`ing the `Assert.ThrowsAsync()` call
This PR fixes them up (and fixes one place where an assertion was actually missing that the test was never finding 😀 )
> Fix async tests

- Octokit.Reactive/Clients/IObservableRepoCollaboratorsClient.cs
- Octokit.Reactive/Clients/ObservableRepoCollaboratorsClient.cs
- Octokit.Tests.Integration/Clients/RepositoryCollaboratorClientTests.cs
- Octokit.Tests.Integration/Reactive/ObservableRepositoryCollaboratorClientTests.cs
- Octokit.Tests/Clients/RepoCollaboratorsClientTests.cs
- Octokit.Tests/Reactive/ObservableRepoCollaboratorsClientTests.cs
- Octokit/Clients/IRepoCollaboratorsClient.cs
- Octokit/Clients/RepoCollaboratorsClient.cs
- Octokit/Helpers/AcceptHeaders.cs
- Octokit/Helpers/ApiUrls.cs
- Octokit/Models/Response/CollaboratorPermission.cs
- Octokit/Models/Response/CollaboratorPermissions.cs
- Octokit/Models/Response/PermissionLevel.cs
> Organization membership preview API changes - Review user permission

- Octokit.Tests.Conventions/ClientConstructorTests.cs
- Octokit.Tests.Conventions/ModelTests.cs
- Octokit.Tests.Conventions/Octokit.Tests.Conventions.csproj
- Octokit.Tests.Conventions/PaginationTests.cs
- Octokit.Tests.Conventions/SyncObservableClients.cs
- Octokit.Tests.Conventions/xunit.runner.json
- Octokit.Tests/Octokit.Tests.csproj
- Octokit.Tests/xunit.runner.json
- Octokit/Octokit.csproj
- build/Context.cs
- build/Tasks/ConventionTests.cs
- build/Tasks/UnitTests.cs
Fixes #1634 
One funny thing is that running tests with `dotnet test` against `net452` is *very* slow on my machine:
- ~4 seconds for `netcoreapp1.0`
- more than 2 minutes for `net452`
I want to see if the same thing happens on the build server.
If it does, I trialled using `dotnet xunit` and it was much faster, so that could be a workaround, but we'd have to change the Cake build script, and I don't if there's a wrapper for `dotnet xunit` already since it's pretty early days.
> Fix broken JSON deserialization in .NET 4.5

- Octokit.Tests/Helpers/UriExtensionsTests.cs
- Octokit/Helpers/UriExtensions.cs
While investigating why pagination didn't seem to be working on #1639 I discovered a bug in the `Uri.ApplyParameters()` extension method.
When the passed in `Uri` is a relative type and already includes query parameters, the resulting `Uri` generated by this function contains the existing parameters then an additional `?` character followed by the actual set of existing+new parameters.  
This was resulting in the pagination parameters being ignored by the upstream API 
(note the 2 occurrences of `?` and both the "existing" and "new+existing" parameter sets present):
Actual: `orgs/testorg/outside_collaborators?filter=all?per_page=1&page=1&filter=all`
Expected: `orgs/testorg/outside_collaborators?per_page=1&page=1&filter=all`
Unit tests have been extended to cover relative `Uri`'s, which …
> Fix Uri.ApplyParameters() to handle relative Uri's that have existing parameters

- Octokit.Reactive/Clients/IObservableOrganizationOutsideCollaboratorsClient.cs
- Octokit.Reactive/Clients/ObservableOrganizationOutsideCollaboratorsClient.cs
- Octokit.Tests.Integration/Clients/OrganizationOutsideCollaboratorsClientTests.cs
- Octokit.Tests.Integration/Reactive/ObservableOrganizationOutsideCollaboratorsClientTests.cs
- Octokit.Tests/Clients/OrganizationOutsideCollaboratorsClientTests.cs
- Octokit.Tests/Reactive/ObservableOrganizationOutsideCollaboratorsClientTests.cs
- Octokit/Clients/IOrganizationOutsideCollaboratorsClient.cs
- Octokit/Clients/OrganizationOutsideCollaboratorsClient.cs
It appeared as though this API endpoint didnt support pagination, so `ApiOptions` overloads were dropped from the implementation in #1639 
After GitHub support confirmed pagination should be in place on this endpoint, some debugging revealed 
a bug in octokit (#1649 ) which was causing invalid Uri's that was affecting this endpoint (as it uses a query parameter to specify the filter in the `Uri`)
Once that fix is merged, pagination works OK, so this PR (re)implements the pagination support for the `GetAll()` outside collaborators function and associated integration tests
CC @alfhenrik
> Implement pagination on Organization Outside Collaborators Client GetAll() method

- LICENSE.txt
- Octokit.Tests.Conventions/Octokit.Tests.Conventions.csproj
- Octokit.Tests.Conventions/Properties/AssemblyInfo.cs
- Octokit.Tests.Integration/Octokit.Tests.Integration.csproj
- Octokit.Tests.Integration/Properties/AssemblyInfo.cs
- Octokit.Tests/Octokit.Tests.csproj
- Octokit.Tests/Properties/AssemblyInfo.cs
- README.md
- build/Build.csproj
- build/Context.cs
- build/Tasks/IntegrationTests.cs
- build/Tasks/Package.cs
- build/Tasks/Restore.cs
- docs/shipping-releases.md
- Update README and shipping-releases info as they are a bit out of date
- Update year/copyright info on assemblies
- Update cake.frosting package to latest version for better dotnet msbuild tooling support
- Update xunit packages to latest version (fixes CodeLens display of nested test classes in VS2017 - also requires VS2017 15.3 update)
> General updates

- Octokit.Tests/Clients/RepositoriesClientTests.cs
- Octokit.Tests/Clients/RespositoryCommitsClientTests.cs
- Octokit/Clients/RepositoryCommitsClient.cs
- Octokit/Helpers/AcceptHeaders.cs
While running integration tests prepping for a release, I found that the `client.Repository.Commit.GetSha1()` call was returning `null` rather than the expected `string` sha1.
This turned out to be a situation where when the API went from preview to official ([announced here](https://developer.github.com/changes/2016-04-12-commit-reference-sha-api-is-now-official/)], the old preview header is no longer able to be used (despite the blog post saying it is!).
I contacted GitHub support who informed me that the blog post was incorrect in saying the preview header would still work - unlike normal API previews where the accepts header just enables additional/changed json response fields, this particular API call actually had an entirely new media type response (a string SHA1 rather than a json …
> Fix RepositoryCommitsClient.GetSha1 API call after preview period ended

- ReleaseNotes.md
We need to get #1523 shipped prior to the Branch Protection API Preview period ending on the 1st September
Given it's hot on the heels of v0.25 I have only run the integration tests for `RepositoryBranchesClient` and `ObservableRepositoryBranchesClient` and will aim to ship tomorrow.
> Release v0.26 - In the Nick of Time

- Octokit.Reactive/Clients/IObservableRepositoryBranchesClient.cs
- Octokit.Reactive/Clients/IObservableRepositoryTrafficClient.cs
- Octokit.Reactive/Clients/ObservableRepositoryBranchesClient.cs
- Octokit.Reactive/Clients/ObservableRepositoryTrafficClient.cs
- Octokit.Tests.Conventions/Exception/ApiOptionsMissingException.cs
- Octokit.Tests.Conventions/PaginationTests.cs
- Octokit.Tests.Integration/Clients/RepositoryBranchesClientTests.cs
- Octokit.Tests.Integration/Clients/RepositoryTrafficClientTests.cs
- Octokit.Tests/Clients/RepositoryBranchesClientTests.cs
- Octokit.Tests/Clients/RepositoryTrafficClientTests.cs
- Octokit.Tests/Reactive/ObservableRepositoryBranchesClientTests.cs
- Octokit.Tests/Reactive/ObservableRepositoryTrafficClientTests.cs
- Octokit/Clients/ICommitCommentReactionsClient.cs
- Octokit/Clients/IIssueCommentReactionsClient.cs
- Octokit/Clients/IIssueReactionsClient.cs
- Octokit/Clients/IMigrationsClient.cs
- Octokit/Clients/IMiscellaneousClient.cs
- Octokit/Clients/IOrganizationsClient.cs
- Octokit/Clients/IPullRequestReviewCommentReactionsClient.cs
- Octokit/Clients/IReferencesClient.cs
- Octokit/Clients/IRepositoriesClient.cs
- Octokit/Clients/IRepositoryBranchesClient.cs
- Octokit/Clients/IRepositoryContentsClient.cs
- Octokit/Clients/IRepositoryInvitationsClient.cs
- Octokit/Clients/IRepositoryTrafficClient.cs
- Octokit/Clients/RepositoryBranchesClient.cs
- Octokit/Clients/RepositoryTrafficClient.cs
- Octokit/Helpers/ExcludeFromPaginationApiOptionsConventionTestAttribute.cs
- Octokit/Helpers/ExcludeFromPaginationConventionTest.cs
- Octokit/Helpers/ExcludeFromPaginationNamingConventionTest.cs
Unskip and tweak the existing pagination tests so we can use them to enforce pagination conventions going forward
- ApiOptions overload pagination implemtation
For items that failed tests, probed upstream API and flagged the method as either requiring pagination implementation or API not supporting pagination.  Issues will be raised for each client/method where pagination needs to be implemented
- GetAll naming for methods returning `IReadonlyList<T>`
Renamed offending methods in `RepositoryTrafficClient` and `RepositoryBranchesClient` and flagged old ones as `[Obsolete]` so they can be removed in the future
> Enable pagination convention tests

- Octokit.Tests.Integration/Clients/TeamsClientTests.cs
- Octokit/Models/Request/NewTeam.cs
- Octokit/Models/Request/UpdateTeam.cs
- Octokit/Models/Response/Team.cs
Fixes #1675 
- Add `TeamPrivacy` enum (Closed, Secret)
- Add `Description` and `Privacy` fields to `Team` response object
- Add `Privacy` and `Maintainers` fields to `NewTeam` request object
- Add `Description` and `Privacy` field to `UpdateTeam` request object
NOTE: `Permission` field on `NewTeam` request has been changed to a nullable type, eg  `Permission? Permission`, since it is optional and should not be sent to the API when the consumer has not set a value.
Ensured new fields are exercised in integration tests
> Add missing fields to Team response, and NewTeam/UpdateTeam requests

- Octokit.Reactive/Octokit.Reactive.csproj
- Octokit/Octokit.csproj
Fixes #1673 
That post by Nate McMaster has saved my bacon a few times now: http://www.natemcmaster.com/blog/2017/01/19/project-json-to-csproj/#other-common-build-options
I think we lost the documentation files when we moved from the `project.json` project system to the new `.csproj` one.
I tested by running the `Package` build task and the XML files ended up in the `.nupkg`s which I suppose will fix this.
> Enable generation of XML doc files

- Octokit.Tests.Integration/Clients/SearchClientTests.cs
- Octokit.Tests/Clients/SearchClientTests.cs
- Octokit/Models/Request/SearchRepositoriesRequest.cs
Fixes #1677 
The forks qualifier should be `fork:true` or `fork:only` and was incorrectly being set to the enum member `.ToString()` rather than the decorated `[Parameter()]` values.
- Changed the `MergedQualifiers` function to use the decorated `[Parameter]` attribute value for the enum members
- Changed the values to lowercase for consistency
- Added unit and integration tests for both Forks values (Include and Only)
> Fix SearchRepository forks qualifier

- Octokit.Reactive/Clients/IObservableTeamsClient.cs
- Octokit.Reactive/Clients/ObservableTeamsClient.cs
- Octokit.Tests.Integration/Clients/TeamsClientTests.cs
- Octokit.Tests.Integration/Helpers/ObservableGithubClientExtensions.cs
- Octokit.Tests.Integration/Reactive/Enterprise/ObservableEnterpriseLdapClientTests.cs
- Octokit.Tests.Integration/Reactive/ObservableTeamsClientTests.cs
- Octokit.Tests/Clients/TeamsClientTests.cs
- Octokit.Tests/Reactive/ObservableTeamsClientTests.cs
- Octokit/Clients/ITeamsClient.cs
- Octokit/Clients/TeamsClient.cs
- Octokit/Models/Request/TeamMembersRequest.cs
- Octokit/Models/Request/UpdateTeamMembership.cs
- Octokit/Models/Response/MembershipState.cs
- Octokit/Models/Response/TeamMembership.cs
- Octokit/Models/Response/TeamMembershipDetails.cs
Fixes #1676 
- Implement `TeamsClient.AddOrEditMembership` taking a request parameter to indicate the `role` of the member to be added/updated (Member or Maintainer)
- Implement role filter on `TeamsClient.GetAllmembers()` so that the query can be filtered based on the member roles (Member, Maintainer or All)
- Introduce new response type for Team membership which includes the `Role` (Member or Maintainer) and `Status` (Active or Pending) of the membership.
Due to needing to safely deprecate the old `GetMembership` method following our normal deprecation schedule, the new method has been named `GetMembershipDetails` as the method signature was the same except for the return type. 
The `AddMembership` method has been deprecated, replaced with `AddOrEditMembership`
> Implement Team Membership changes

- Octokit.Reactive/Clients/IObservableTeamsClient.cs
- Octokit.Reactive/Clients/ObservableTeamsClient.cs
- Octokit.Tests.Integration/Clients/TeamsClientTests.cs
- Octokit.Tests.Integration/Helpers/GithubClientExtensions.cs
- Octokit.Tests.Integration/Helpers/ObservableGithubClientExtensions.cs
- Octokit.Tests.Integration/Reactive/Enterprise/ObservableEnterpriseLdapClientTests.cs
- Octokit.Tests.Integration/Reactive/ObservableTeamsClientTests.cs
- Octokit.Tests/Clients/TeamsClientTests.cs
- Octokit.Tests/Reactive/ObservableTeamsClientTests.cs
- Octokit/Clients/ITeamsClient.cs
- Octokit/Clients/TeamsClient.cs
- Octokit/Helpers/AcceptHeaders.cs
- Octokit/Helpers/ApiUrls.cs
- Octokit/Models/Request/NewTeam.cs
- Octokit/Models/Request/UpdateTeam.cs
- Octokit/Models/Response/Team.cs
> Implement Nested Teams preview API changes

- Octokit.Reactive/IObservableGitHubClient.cs
- Octokit.Reactive/ObservableGitHubClient.cs
- Octokit.Tests/GitHubClientTests.cs
- Octokit/GitHubClient.cs
- Octokit/Http/Connection.cs
- Octokit/Http/HttpClientAdapter.cs
- Octokit/Http/IConnection.cs
- Octokit/Http/IHttpClient.cs
- Octokit/IGitHubClient.cs
A first attempt to fix the problem describe in #963 by adding a possibility to extend the default timeout value (100s) that is too short to be able to post assets in github release.
Fixes #963
/ cc @ryangribble
> Add possibility to configure GitHubClient timeout (#963)

- docs/http-client.md
This is breaking the layout at http://octokitnet.readthedocs.io/en/latest/http-client/.
> Remove extra space before close ticks.

- Octokit/Models/Response/CommitStatus.cs
I have a (private) repository where GitHub reports statuses with
ids like 4299360515, which fail to deserialize as it doesn't fit
on the int.
There is nothing (I could find) on the GitHub API docs that say
that this status id is limited to an int-sized value.
Fixes #1702
> Prevent overflow exceptions when status id > int.Max

- Octokit.Reactive/IObservableGitHubClient.cs
- Octokit.Reactive/ObservableGitHubClient.cs
- Octokit/IGitHubClient.cs
- ReleaseNotes.md
Aiming to release this ASAP since we are crashing on GitHub `CommitStatus.Id` currently... this is the abridged version of the release checklist 😝
> Release v0.28 - Get to the Chopper!!!

- script/configure-integration-tests.ps1
The warning in configuration script can be easily overlooked. I changed it's color to yellow to make it more visible.
How it looks after the change:
> Change integration tests configuration script test account warning color to yellow.

- Octokit.Reactive/Octokit.Reactive.csproj
- Octokit/Octokit.csproj
Fixes #1712 
AWS Lambda requires "strict" `netcoreapp1.0` support and although we target `netstandard1.1` which is compatible with `netcoreapp1.0`, the dotnet tooling automatically uses the NetStandard.Library metapackage version 1.6.1 (which is more aligned with `netcoreapp1.1`).  I'm pretty sure we are still actually `netcoreapp1.0` compatible (as evidenced by our test assemblies being `netcoreapp1.0`) but due to the way AWS Lambda tools work, they see the metapackage 1.6.1 version and refuse to deploy.
This PR forces the implicit meta package version to 1.6.0 so that the AWS Lambda tools don't complain about a lambda that is referencing octokit.
> Support running in aws lambda by fixing netcoreapp1.1 vs netcoreapp1.0 confusion 

- Octokit.Reactive/Clients/IObservableReferencesClient.cs
- Octokit.Reactive/Clients/ObservableReferencesClient.cs
- Octokit.Tests.Integration/Clients/ReferencesClientTests.cs
- Octokit.Tests/Clients/ReferencesClientTests.cs
- Octokit/Clients/IReferencesClient.cs
- Octokit/Clients/ReferencesClient.cs
Fixes #1664 
- make existing methods call new overload with `ApiOptions.None`
- Adjust for `ApiOptions` parameter
- Add `null`/`""` checks for `ApiOptions` overloads
- `ReturnsCorrectCountOfXWithoutStart`
- `ReturnsCorrectCountOfXWithStart`
- `ReturnsDistinctXBasedOnStartPage`
> Add pagination support to ReferencesClient.

- Octokit.Tests/Clients/OauthClientTests.cs
- Octokit.Tests/Helpers/UriExtensionsTests.cs
- Octokit/Clients/OAuthClient.cs
- Octokit/Helpers/ApiUrls.cs
- Octokit/Helpers/UriExtensions.cs
Fixes #1724 and #1729 
Urls used in the `OAuthClient` are incorrect for GitHub Enterprise instances due to not stripping off the `/api/v3` from the base URL
Changed the `OAuthClient`'s stored `hostAddress` to strip any relative `Uri` from the current `baseAddress` so that it correctly uses the github website Url for OAuth actions.
This fixes the Urls in the 2 OAuthClient functions:
`OAuthClient.GetGitHubLoginUrl()`
`OAuthClient.CreateAcessToken()`
eg for an GitHub Enterprise instance we now will use:
`GitHubClient` `baseAddress`: `https://example.com/api/v3` 
`OAuthClient` `hostAddress`: `https://example.com`
`OAuthClient` Authorize Uri: `https://example.com/login/oauth/authorize`
`OAuthClient` Token Uri: `https://example.com/login/oauth/access_token`
> Fix OAuthClient to work correctly with GitHub Enterprise instances

- Octokit.Tests/Clients/EventsClientTests.cs
- Octokit/Http/SimpleJsonSerializer.cs
- Octokit/Models/Response/ActivityPayloads/StatusEventPayload.cs
Added payload definition for the Status Event message.
> Add support for StatusEventPayload

- Octokit.Tests/SimpleJsonSerializerTests.cs
- Octokit.sln
- Octokit/Models/Response/Account.cs
- Octokit/Models/Response/User.cs
- Octokit/SimpleJson.cs
The other PR got dirty, so I created another one, and did it right this time :-)
> Added support for DateTime serialized as FileTime

- Octokit/Models/Response/PullRequestReviewComment.cs
I added a new column to PullRequestReviewComment model in order to capture a field called pull_request_review_id which is returned by [Github API](https://developer.github.com/v3/pulls/comments/) .
> Add a new column named PullRequestReviewId to PullRequestReviewComment

- Octokit.Reactive/Clients/IObservableReferencesClient.cs
- Octokit.Reactive/Clients/IObservableRepositoryInvitationsClient.cs
- Octokit.Reactive/Clients/ObservableReferencesClient.cs
- Octokit.Reactive/Clients/ObservableRepositoriesClient.cs
- Octokit.Reactive/Clients/ObservableRepositoryInvitationsClient.cs
- Octokit.Tests.Integration/Clients/ReferencesClientTests.cs
- Octokit.Tests.Integration/Clients/RepositoryInvitationsClientTests.cs
- Octokit.Tests/Clients/ReferencesClientTests.cs
- Octokit.Tests/Clients/RepositoryInvitationsClientTests.cs
- Octokit.Tests/Reactive/ObservableRepositoriesClientTests.cs
- Octokit.Tests/Reactive/ObservableRepositoryInvitationsClientTests.cs
- Octokit/Clients/IReferencesClient.cs
- Octokit/Clients/IRepositoryInvitationsClient.cs
- Octokit/Clients/ReferencesClient.cs
- Octokit/Clients/RepositoryInvitationsClient.cs
> Fixes #1586 - Repository license API

- docs/getting-started.md
I added an example and a bit of explanation about `GitHubClient.Miscellaneous.GetRateLimits()`.  #1737
> Improve Rate Limits' Documentation

- Octokit/Clients/Enterprise/EnterpriseProbe.cs
- Octokit/GitHubClient.cs
- Octokit/Http/Connection.cs
- Octokit/Http/ProductHeaderValue.cs
Fixes #1750
* This updates GitHubClient.cs, ProductHeaderValue.cs, Connection.cs, and EnterpriseProbe.cs to reflect proper XML Doc that links to the info on GitHub's Dev Doc on User-Agent required.
* Updates the description to reflect that docs state this is not just a product, but can be your organization name or username as well.
* I am submitting a bug to GitHub.com separately for a UI issue in comparing branches.
* I initially used tabs instead of spaces on my first upload.
* I then commited edits, removing all spaces by using Atom's Whitespace > Tabs to Spaces feature.
* These commits also were mis-aligned on the UI.
* I edited each file manually in the GitHub.com editor (within the browser).
* These commits look fine when you inspect the file, but on compare are misaligned in some …
> Fixes #1750, changing description of productInformation param for clarity

- Octokit.Tests/Models/StringEnumTests.cs
- Octokit/Models/Response/AccountType.cs
While looking into another issue I found that the API responses for account type are `Bot` `User` `Organization` but we had these attributes in lower case on our enum.  This caused some cache misses in the deserializer enum field/attribute dictionary
> Fix AccountType enum Parameter values to match the sentence case used in API responses

- Octokit.Tests.Integration/Octokit.Tests.Integration.csproj
- Octokit/Http/HttpClientAdapter.cs
- Octokit/Octokit.csproj
Fixes #1756 
TLS1.2 will be required to connect to the GitHub API when [GitHub deprecates weak cryptographic algorithms on 22nd February](https://developer.github.com/changes/2018-02-01-weak-crypto-removal-notice/)
.NET Frameworks less than 4.6 do not have TLS1.2 enabled by default, so Octokit will now enable this protocol (on the `net45` target framework build only).
Notes
- `ServicePointManager.SecurityProtocol` is the mechanism used to enable the protocol... which isn't actually available on .NET Core until 2.0 anyway (but we don't need it since TLS1.2 is already enabled in .NET Core anyway)
- Added a `net452` target to the integration test project (bringing it into line with the other multi targeted test projects) in order to manually test that this value was set on .NET 4.5x
> Add TLS1.2 to enabled security protocols (.NET Framework 4.5 only)

- Octokit.Tests/Models/StringEnumTests.cs
- Octokit.Tests/SimpleJsonSerializerTests.cs
- Octokit/Http/SimpleJsonSerializer.cs
- Octokit/Models/Response/StringEnum.cs
- Octokit/SimpleJson.cs
When a nullable `StringEnum<T>?` member was added to a class, the deserializer failed to deserialize "good" values into the field as it tries to do a type conversion to the `Nullable<T>` wrapper.  This change ensures that when deserializing a non empty string value, we use the underlying type of any `Nullable` type.  We already were doing this for regular `enum`s but not `StringEnum<>`s
Added tests for enum, nullable enum, StringEnum and nullable StringEnum to capture the failing state, then proved the fix :+1:
> Deserializer should handle nullable StringEnum<T>

- Octokit.Tests.Conventions/TypeExtensions.cs
- Octokit.Tests.Integration/Clients/PullRequestsClientTests.cs
- Octokit/Models/Response/PullRequest.cs
> Implements PullRequest.MergeableState field

- Octokit.Tests.Integration/Clients/RepositoryInvitationsClientTests.cs
- Octokit/Clients/RepositoriesClient.cs
- Octokit/Helpers/ApiUrls.cs
- Octokit/Http/ProductHeaderValue.cs
- Octokit/Http/SimpleJsonSerializer.cs
- Octokit/Models/Response/ActivityPayloads/StatusEventPayload.cs
- Octokit/Models/Response/PullRequestReviewComment.cs
- ReleaseNotes.md
Aiming to release this ASAP since it will help any .NET 4.5 users when they need to use TLS1.2 from the 22nd Feb...
> Release v0.29 - This Looks Serious (TLS)

- Octokit.Tests/Clients/EventsClientTests.cs
- Octokit/Http/SimpleJsonSerializer.cs
- Octokit/Models/Response/ActivityPayloads/PullRequestReviewEventPayload.cs
Fleshing out the payload models
https://developer.github.com/v3/activity/events/types/#pullrequestreviewevent
CI appears to be erroring
> Adds PullRequestReviewEventPayload

- Octokit.Reactive/Clients/IObservableReleasesClient.cs
- Octokit.Reactive/Clients/ObservableReleasesClient.cs
- Octokit.Tests.Integration/Clients/ReleasesClientTests.cs
- Octokit.Tests.Integration/Reactive/ObservableReleaseClientTests.cs
- Octokit.Tests/Clients/ReleasesClientTests.cs
- Octokit.Tests/Reactive/ObservableReleasesClientTests.cs
- Octokit/Clients/IReleasesClient.cs
- Octokit/Clients/ReleasesClient.cs
- Octokit/Helpers/ApiUrls.cs
This adds the endpoint to retrieve a release by owner, repo, and tag. [https://developer.github.com/v3/repos/releases/#get-a-release-by-tag-name](https://developer.github.com/v3/repos/releases/#get-a-release-by-tag-name)
> Added get release by tag endpoint

- Octokit.Reactive/Clients/IObservableReferencesClient.cs
- Octokit.Reactive/Clients/ObservableReferencesClient.cs
- Octokit/Clients/IReferencesClient.cs
- Octokit/Clients/ReferencesClient.cs
Details the format of the reference parameter
> Clarifies usage of reference in IReferencesClient methods

- Octokit.Reactive/Clients/ObservableRepositoriesClient.cs
- Octokit.Tests/Clients/RepositoriesClientTests.cs
- Octokit.Tests/Clients/RepositoryBranchesClientTests.cs
- Octokit/Clients/RepositoriesClient.cs
- Octokit/Clients/RepositoryBranchesClient.cs
Fixes #1794 
2 tests are failing, but they were red when I forked the repo.
> Add proper accept header to all team calls (Fixes #1794)

- Octokit.Reactive/Clients/IObservableIssuesLabelsClient.cs
- Octokit.Reactive/Clients/IObservableSearchClient.cs
- Octokit.Reactive/Clients/ObservableIssuesLabelsClient.cs
- Octokit.Reactive/Clients/ObservableSearchClient.cs
- Octokit.Tests.Integration/Clients/IssuesLabelsClientTests.cs
- Octokit.Tests.Integration/Clients/SearchClientTests.cs
- Octokit.Tests/Clients/IssuesLabelsClientTests.cs
- Octokit.Tests/Clients/SearchClientTests.cs
- Octokit.Tests/Reactive/ObservableIssuesLabelsClientTests.cs
- Octokit/Clients/IIssuesLabelsClient.cs
- Octokit/Clients/ISearchClient.cs
- Octokit/Clients/IssuesLabelsClient.cs
- Octokit/Clients/SearchClient.cs
- Octokit/Helpers/AcceptHeaders.cs
- Octokit/Helpers/ApiUrls.cs
- Octokit/Models/Request/BaseSearchRequest.cs
- Octokit/Models/Request/LabelUpdate.cs
- Octokit/Models/Request/NewLabel.cs
- Octokit/Models/Request/SearchLabelsRequest.cs
- Octokit/Models/Response/Label.cs
- Octokit/Models/Response/SearchLabelsResult.cs
> Implement improved labels API

- docs/releases.md
1. Remove incorrect usage of await on synchronous method
2. Dispose of stream after use
> Correct upload asset code

- docs/getting-started.md
At first sight, it not obvious that Reset shows time in UTC and I've seen a couple of times folks think it's based on their local timezone. I believe it will be a good addition to current document to mention that the time is UTC.
> Mentioning the reset time is based on UTC standard

- Octokit/Models/Response/EventInfo.cs
Currently, Octokit does not support the comment_deleted event status. As an example, I was unable to get the Event.Value of one of the [VSCode issues](https://api.github.com/repos/Microsoft/vscode/issues/events/1246084209) and i recieved the following error:
> Requested value 'comment_deleted' was not found.
I'm using the latest version, which is 0.30.0
> A missing event state: comment_deleted

- Octokit.Reactive/Octokit.Reactive.csproj
- Octokit/Octokit.csproj
The last release inadvertently ended up with a nuget dependency on `SourceLink.Create.GitHub` which is only used as part of our build process...
Also bumped SourceLink packages to latest versions to keep them up to date
v0.30:
With this change:
> Remove runtime dependency on SourceLink.Create.GitHub

- Octokit.Reactive/Clients/IObservableRepositoriesClient.cs
- Octokit.Reactive/Clients/ObservableRepositoriesClient.cs
- Octokit.Tests.Integration/Clients/RepositoriesClientTests.cs
- Octokit.Tests/Clients/RepositoriesClientTests.cs
- Octokit.Tests/Models/RepositoryTransferTest.cs
- Octokit.Tests/Reactive/ObservableRepositoriesClientTests.cs
- Octokit/Clients/IRepositoriesClient.cs
- Octokit/Clients/RepositoriesClient.cs
- Octokit/Helpers/AcceptHeaders.cs
- Octokit/Helpers/ApiUrls.cs
- Octokit/Helpers/Ensure.cs
- Octokit/Models/Request/RepositoryTransfer.cs
Pull request addressing #1718 
---
Points of concern:
- I'm not sure if I'm the one supposed to implement and/or run the integration tests, but if it is me then I have no idea of what to do. Could someone please point me in the right direction?
- Unit tests were all successful, but I'm not sure they've covered everything they were supposed to.
---
Edit: Updated "to do" list in replies
Edit 2: Update main "to do" list
> [WIP] Fixes #1718 Implement Repository Transfer functionality

- Octokit.Tests.Integration/Clients/RepositoriesClientTests.cs
- Octokit/Clients/RepositoriesClient.cs
Fixes #1820 
This endpoint is a bit "special" as it returns an object hash which we deserialize as a `Dictionary<string, long>` and then convert into a `ReadOnlyList`.  When no languages exist, the API returns `null` which then throws an exception in our conversion process.
This fix handles this situation by returning an empty list.
> Fix exception in RepositoriesClient.GetAllLanguages() when no languages exist

- Octokit.Reactive/Clients/IObservableProjectCardsClient.cs
- Octokit.Reactive/Clients/ObservableProjectCardsClient.cs
- Octokit.Tests.Integration/Clients/ProjectCardsClientTests.cs
- Octokit.Tests.Integration/Reactive/ObservableProjectCardsClientTests.cs
- Octokit.Tests/Clients/ProjectCardsClientTests.cs
- Octokit.Tests/Models/ProjectCardRequestTests.cs
- Octokit.Tests/Reactive/ObservableProjectCardsClientTests.cs
- Octokit/Clients/IProjectCardsClient.cs
- Octokit/Clients/ProjectCardsClient.cs
- Octokit/Models/Request/ProjectCardRequest.cs
- Octokit/Models/Request/ProjectCardUpdate.cs
- Octokit/Models/Response/ProjectCard.cs
- appveyor.yml
As per [this recent blog](https://developer.github.com/changes/2018-06-27-project-card-archiving/), Project Cards can now be archived/unarchived
- Add `Archived` field to `ProjectCard` response
- Add `Archived` field to `ProjectCardUpdate` request
- Add `ProjectCardRequest` request, to allow filtering Project Cards by `archive_state`
> Implement new Project Card archiving

- docs/github-apps.md
In implementing this, I found that `appClient.GetCurrent()` (etc.) don't work.
Appears that all the GitHub Apps methods were moved into a subclass called `GitHubApps`, so that `appClient.GitHubApps.GetCurrent()` etc does work. 
Could also be written by adding the `.GitHubApps` onto the end of the `appClient` constructor; not sure which would be better from a documentation standpoint.
Anyway, took me a while to figure it out, thought that updated docs might help others.
> Docs: appClient - add GitHubApps subclass to method calls

- Octokit.Reactive/Clients/IObservableCheckSuitesClient.cs
- Octokit.Reactive/Clients/ObservableCheckSuitesClient.cs
- Octokit.Tests.Integration/Clients/CheckRunsClientTests.cs
- Octokit.Tests.Integration/Clients/CheckSuitesClientTests.cs
- Octokit.Tests.Integration/Reactive/ObservableCheckRunsClientTests.cs
- Octokit.Tests.Integration/Reactive/ObservableCheckSuitesClientTests.cs
- Octokit.Tests/Clients/CheckSuitesClientTests.cs
- Octokit.Tests/Clients/ProjectCardsClientTests.cs
- Octokit.Tests/Reactive/ObservableCheckSuitesClientTests.cs
- Octokit.Tests/Reactive/ObservableProjectCardsClientTests.cs
- Octokit/Clients/CheckSuitesClient.cs
- Octokit/Clients/ICheckSuitesClient.cs
- Octokit/Helpers/ApiUrls.cs
- Octokit/Models/Common/CheckStatus.cs
- Octokit/Models/Request/CheckSuiteTriggerRequest.cs
- Octokit/Models/Request/NewCheckRunAnnotation.cs
- Octokit/Models/Response/CheckRunAnnotation.cs
Fixes #1856 
Attempt to handle both old and new annotations models so we can support github.com and GHE 2.14
> Implement changes to Checks API for Annotations models and re-request endpoint

- Octokit.Tests/Reactive/ObservableIssuesLabelsClientTests.cs
- Octokit/Http/ApiConnection.cs
- Octokit/Http/IApiConnection.cs
Fixes #1865 
`IIssueLabelsClient.RemoveFromIssue()` was incorrectly passing an accept header to the body parameter of the delete call.  Recent upstream api changes seem to have occured where this previously ignored situation is now being rejected as the body can't be parsed as valid json.  Also the preview functionality for label emojis/descriptions wouldnt have been working on this call due to the accept header not being passed correctly.
This PR fixes the issue by adding an overload for `ApiConnection.Delete<T>(Uri uri, string accepts)` that takes a Uri and accept header, but no body, which the existing code in `RemoveFromIssue()` will now use instead of `ApiConnection.Delete<T>(Uri uri, object data)`
> Fix `IIssueLabelsClient.RemoveFromIssue()`

- docs/search.md
The existing repo names are based on a very old version of .NET Core.
> Updating to more recent repo names

- Octokit/Models/Common/AuthorAssociation.cs
- Octokit/Models/Response/IssueComment.cs
- Octokit/Models/Response/PullRequestReview.cs
- Octokit/Models/Response/PullRequestReviewComment.cs
It seems that GitHub has recently added a new field called _[author_association](https://developer.github.com/v4/enum/commentauthorassociation/)_ to comment related response models such as[ Issue Comments](https://api.github.com/repos/dotnet/coreclr/issues/17920/comments), [Pull Request Review Comments](https://api.github.com/repos/dotnet/corefx/pulls/154/comments), and[ Pull Request Reviewers](https://api.github.com/repos/dotnet/corefx/pulls/11694/reviews
). This field shows how an author is related to a repo.
The proposed change adds a new enum named AuthorAssociate, changes constructors in affected models, and lastly adds a new attribute called AuthorAssociate to related models.
> Add Author Association for comments related models

- build/Build.csproj
- build/Tasks/Clean.cs
- build/nuget.config
* Uses Cake.Core & Cake.Common 0.31.0 ( read more about improvements at https://cakebuild.net/blog/2018/12/cake-v0.31.0-released )
* 0.31.0 is on NuGet.org so nuget.config no longer needed
* GetDirectories with predicate  is now obsolete, replaced by GlobberSettings
> Update to Cake.Frosting 0.31.0

- Octokit.Tests/Clients/OauthClientTests.cs
- Octokit/Models/Request/OauthLoginRequest.cs
* Adds support for 'login' parameter
* Adds support for 'allow_signup' parameter
Closes #1918
> Adds missing OAuth login request parameters

- .travis.yml
- Octokit.Reactive/Octokit.Reactive.csproj
- Octokit.Tests.Conventions/Octokit.Tests.Conventions.csproj
- Octokit.Tests.Integration/Octokit.Tests.Integration.csproj
- Octokit.Tests/Octokit.Tests.csproj
- Octokit/Octokit.csproj
- build.sh
- build/Context.cs
- build/Lifetime.cs
- build/Tasks/Build.cs
- build/Tasks/FormatCode.cs
- build/Tasks/Package.cs
- build/Utilities/BuildVersion.cs
This enables building via cake on linux without requiring adjustments on
other platforms, fixes #1745
> Enable building on linux without project file changes

- Octokit.Tests/Clients/EventsClientTests.cs
- Octokit/Http/SimpleJsonSerializer.cs
- Octokit/Models/Response/ActivityPayloads/CreateEventPayload.cs
- Octokit/Models/Response/ActivityPayloads/DeleteEventPayload.cs
- Octokit/Models/Response/RefType.cs
Hello, I tried to do the same as was done in #1732 
Please tell me if anything is missing.
Cheers
> Add support for CreateEventPayload and DeleteEvent payload (#1646)

- Octokit/Models/Response/EventInfo.cs
Fixes https://github.com/octokit/octokit.net/issues/1939
> Handle event ids greater than int32.maxvalue

- docs/demos/exploring-pull-requests.md
> adding example for creating PR from fork

- Octokit.Reactive/Clients/IObservableCommitCommentReactionsClient.cs
- Octokit.Reactive/Clients/IObservableIssueCommentReactionsClient.cs
- Octokit.Reactive/Clients/IObservableIssueReactionsClient.cs
- Octokit.Reactive/Clients/IObservablePullRequestReviewCommentReactionsClient.cs
- Octokit.Reactive/Clients/ObservableCommitCommentReactionsClient.cs
- Octokit.Reactive/Clients/ObservableIssueCommentReactionsClient.cs
- Octokit.Reactive/Clients/ObservableIssueReactionsClient.cs
- Octokit.Reactive/Clients/ObservablePullRequestReviewCommentReactionsClient.cs
- Octokit.Tests.Integration/Clients/CommitCommentReactionsClientTests.cs
- Octokit.Tests.Integration/Clients/IssueCommentReactionsClientTests.cs
- Octokit.Tests.Integration/Clients/IssueReactionsClientTests.cs
- Octokit.Tests.Integration/Clients/PullRequestReviewCommentReactionsClientTests.cs
- Octokit.Tests/Clients/CommitCommentReactionsClientTests.cs
- Octokit.Tests/Clients/IssueCommentReactionsClientTests.cs
- Octokit.Tests/Clients/IssueReactionsClientTests.cs
- Octokit.Tests/Clients/PullRequestReviewCommentReactionsClientTests.cs
- Octokit.Tests/Reactive/ObservableCommitCommentReactionsClientTests.cs
- Octokit.Tests/Reactive/ObservableIssueCommentReactionsClientTests.cs
- Octokit.Tests/Reactive/ObservableIssueReactionsClientTests.cs
- Octokit.Tests/Reactive/ObservablePullRequestReviewCommentReactionsClientTests.cs
- Octokit/Clients/CommitCommentReactionsClient.cs
- Octokit/Clients/ICommitCommentReactionsClient.cs
- Octokit/Clients/IIssueCommentReactionsClient.cs
- Octokit/Clients/IIssueReactionsClient.cs
- Octokit/Clients/IPullRequestReviewCommentReactionsClient.cs
- Octokit/Clients/IssueCommentReactionsClient.cs
- Octokit/Clients/IssueReactionsClient.cs
- Octokit/Clients/PullRequestReviewCommentReactionsClient.cs
> Pagination support to Reactions Clients

- Octokit/Http/HttpClientAdapter.cs
Fixes #1914
Don't touch SecurityProtocol when current value is the new SystemDefault added in .NET 4.7
Added comment to explain what we are doing
> Don't apply Tls1.2 workaround when .NET 4.7 SystemDefault is set

- Octokit.Tests/Clients/SearchClientTests.cs
- Octokit/Models/Request/SearchRepositoriesRequest.cs
Hi @ryangribble please let me know what you think.
> DateRange does not include time #1904

- Octokit.Tests/Clients/SearchClientTests.cs
- Octokit.Tests/Models/SearchRepositoryRequestTests.cs
- Octokit/Models/Request/SearchRepositoriesRequest.cs
The language was being directly converted to a string through `ToString()` instead of using the value in the `ParameterAttribute`.
> Correctly support language filter in repo search

- Octokit/Models/Response/PullRequestReview.cs
Field isnt shown in responses on the developer docs site, however poking the API shows it IS present in the json response payload and is thus populated successfully with this change
> Add SubmittedAt field to PullRequestReview

- GitVersion.yml
- build/Build.csproj
- build/Context.cs
- build/Lifetime.cs
- build/Utilities/BuildVersion.cs
- build/Utilities/GitVersionRunner.cs
- build/Utilities/ToolInstaller.cs
- tools/gitversion_wrapper.sh
Update build to use latest released version of Cake:Frosting (0.34.1 which uses same version of Cake.Core/Common).
> (build) Updated Cake.Frosting to version 0.34.1

- Octokit.Reactive/Clients/IObservableRepositoriesClient.cs
- Octokit.Reactive/Clients/IObservableStatisticsClient.cs
- Octokit.Reactive/Clients/ObservableRepositoriesClient.cs
- Octokit.Reactive/Clients/ObservableStatisticsClient.cs
- Octokit/Clients/IRepositoriesClient.cs
- Octokit/Clients/IStatisticsClient.cs
- Octokit/Clients/RepositoriesClient.cs
- Octokit/Clients/StatisticsClient.cs
I had to add the warning to the `Statistics` property as well on the `*RepositoriesClient` otherwise the warning won't show up in intellisense when you do `github.Repositories.Statistics`
Fixes #1814
> Add a warning to the statistics client about caching

- Octokit.Tests/Clients/SearchClientTests.cs
- Octokit.Tests/Models/SearchIssuesRequestTests.cs
- Octokit/Models/Request/SearchRepositoriesRequest.cs
Fixes #1972
I was cleaning up some tests and stumbled upon this issue, and I think the fix here is to simply drop the space, as @catmorgan pointed out.
> fix timezone offset handling

- .travis.yml
This might help with #1991 which is currently failing on macOS only due to something that looks like https://github.com/dotnet/corefx/issues/13309 (definitely fixed in 3.0)
> update travis to use a recent .NET Core version when testing

- Octokit.Reactive/Octokit.Reactive.csproj
- Octokit.Tests.Conventions/Octokit.Tests.Conventions.csproj
- Octokit.Tests.Integration/Octokit.Tests.Integration.csproj
- Octokit.Tests/Octokit.Tests.csproj
- Octokit/Octokit.csproj
Related to #1817 and #1994, my plan is:
- add a `net46` target and confirm tests all work fine locally on that platform (where feasible)
- ship a `net46` binary alongside a `net45` binary for at least one release
- land #1994 and bump us to the newer `System.Reactive`, which requires dropping `net45`
- ship another update to our newer `System.Reactive` and a newer minimum of `net46`
> add net46 build output to package

- .gitignore
- Octokit/Models/Response/Milestone.cs
Not sure if I should add/update any tests to check for the existence of the `ID` property?
Fixes octokit/octokit.net#1970
> Add missing ID property to Milestone

- Octokit.Reactive/Clients/IObservableIssueCommentsClient.cs
- Octokit.Reactive/Clients/ObservableIssueCommentsClient.cs
- Octokit.Tests/Clients/IssueCommentsClientTests.cs
- Octokit.Tests/Reactive/ObservableIssueCommentsClientTests.cs
- Octokit/Clients/IIssueCommentsClient.cs
- Octokit/Clients/IssueCommentsClient.cs
I noticed that `IObservable<IssueComment> GetAllForIssue(long repositoryId, int number, ApiOptions otpions)` didn't specify `AcceptHeaders.ReactionsPreview` so I added this as part of my changes.
Fixes octokit/octokit.net#1960
> Add ability to specify 'since' request parameter to issue comments

- Octokit.Reactive/Clients/ObservablePullRequestsClient.cs
- Octokit.Tests.Integration/Clients/PullRequestsClientTests.cs
- Octokit.Tests/Clients/PullRequestsClientTests.cs
- Octokit.Tests/Reactive/ObservablePullRequestsClientTests.cs
- Octokit/Clients/PullRequestsClient.cs
- Octokit/Helpers/AcceptHeaders.cs
- Octokit/Models/Request/NewPullRequest.cs
- Octokit/Models/Response/PullRequest.cs
Fixes octokit/octokit.net#1945
> Implement Draft Pull Requests

- Octokit.Tests.Integration/Helpers/ObservableGithubClientExtensions.cs
- Octokit.Tests.Integration/Reactive/Enterprise/ObservableEnterpriseManagementConsoleTests.cs
These tests were originally in #1415 but are useful for #2010
> backport tests into main project

- Octokit.Tests/Http/ApiConnectionTests.cs
- Octokit.Tests/Models/SearchIssuesRequestTests.cs
Recent Travis builds on Linux seem to now have `System.Range` available, which clashes with our `Octokit.Range` type:
```
Models/SearchIssuesRequestTests.cs(187,32): error CS0104: 'Range' is an ambiguous reference between 'Octokit.Range' and 'System.Range' [/home/travis/build/octokit/octokit.net/Octokit.Tests/Octokit.Tests.csproj]
```
This should disambiguate it without impacting the other builds.
Oh, and the second commit is to tidy up the last xUnit warning (by opting in and skipping the test with a warning).
> address new Travis build warning

- Octokit.Reactive/Clients/ObservableIssueCommentReactionsClient.cs
- Octokit.Reactive/Clients/ObservableIssueReactionsClient.cs
- Octokit.Reactive/Clients/ObservableMigrationsClient.cs
- Octokit.Reactive/Clients/ObservablePullRequestReviewCommentReactionsClient.cs
- Octokit.Tests.Integration/Clients/CommitCommentReactionsClientTests.cs
- Octokit.Tests.Integration/Clients/IssueReactionsClientTests.cs
- Octokit.Tests.Integration/Clients/MigrationsClientTests.cs
- Octokit.Tests.Integration/Clients/PullRequestsClientTests.cs
- Octokit.Tests.Integration/Helpers/GitHubAppsTestAttribute.cs
- Octokit.Tests.Integration/Helpers/MaintenanceModeContext.cs
- Octokit.Tests/Clients/IssueCommentReactionsClientTests.cs
- Octokit.Tests/Clients/IssueCommentsClientTests.cs
- Octokit.Tests/Clients/IssueReactionsClientTests.cs
- Octokit.Tests/Reactive/ObservableIssueCommentsClientTests.cs
- Octokit.Tests/Reactive/ObservableIssueReactionsClientTests.cs
- Octokit/Clients/IssueCommentReactionsClient.cs
- Octokit/Clients/IssueCommentsClient.cs
- Octokit/Clients/PullRequestReviewCommentReactionsClient.cs
- Octokit/Clients/PullRequestsClient.cs
- Octokit/Models/Request/NewPullRequest.cs
- Octokit/Models/Request/SearchRepositoriesRequest.cs
- Octokit/Models/Response/Milestone.cs
- Octokit/Models/Response/PullRequest.cs
- build/Context.cs
- build/Lifetime.cs
- build/Tasks/Build.cs
- build/Tasks/FormatCode.cs
Back in the day I added [`shiftkey/Octokit.CodeFormatter`](https://github.com/shiftkey/Octokit.CodeFormatter) to this project, but that predates the global tools support for .NET Core. I had a look around today before I took a shot at updating it and found [`dotnet-format`](https://github.com/dotnet/format) has shipped, so I'm going to retire that in favour of this.
This PR now adds in the `FormatCode` step as a local build (so devs can run `./build.ps1` or `./build.sh` and have their code tidied up for free) and tidies up what is currently on `master`.
> migrate to dotnet-format tool

- Octokit.Tests/Clients/SearchClientTests.cs
- Octokit/Models/Request/SearchCodeRequest.cs
- docs/search.md
Modifies `SearchCodeRequest.Extension` to be a list for filtering by `x` number of extensions. Helps reduce the number of required API calls.
Question: Is there an open issue to support the negation of qualifiers (`-extension:{0}`)? I couldn't find one.
> add support for multiple extension filters

- Octokit/Models/Response/EventInfo.cs
Fixes https://github.com/octokit/octokit.net/issues/2023
Fixes https://github.com/octokit/octokit.net/issues/2025
> Add missing issue event types

- build/Build.csproj
- build/Tasks/CodeCoverage.cs
- build/Tasks/FormatCode.cs
* Cake.Frosting 0.35.0
* Cake.Coverlet 2.3.4
* Cake.Codecov 0.7.0
* Codecov 1.7.2
* Make dotnet-format execution more robust (currently can fail if not installed globally)
> (build) Update to Cake 0.35.0, update dependencies and improve dotnet-format execution.

- Octokit.Tests/Clients/SearchClientTests.cs
- Octokit.Tests/Models/SearchIssuesRequestExclusionsTests.cs
- Octokit.Tests/Models/SearchIssuesRequestTests.cs
- Octokit.Tests/Models/SearchRepositoryRequestTests.cs
- Octokit/Models/Request/SearchCodeRequest.cs
- Octokit/Models/Request/SearchIssuesRequest.cs
- Octokit/Models/Request/SearchIssuesRequestExclusions.cs
- Octokit/Models/Request/SearchRepositoriesRequest.cs
- Octokit/Models/Request/SearchUsersRequest.cs
> fix language with spaces giving wrong results [#1607]

- Octokit.Reactive/Clients/IObservableRepoCollaboratorsClient.cs
- Octokit.Reactive/Clients/ObservableRepoCollaboratorsClient.cs
- Octokit.Tests/Clients/RepoCollaboratorsClientTests.cs
- Octokit.Tests/Reactive/ObservableRepoCollaboratorsClientTests.cs
- Octokit/Clients/IRepoCollaboratorsClient.cs
- Octokit/Clients/RepoCollaboratorsClient.cs
- Octokit/Models/Request/RepositoryCollaboratorListRequest.cs
Also adds support for the `Nested Teams` preview API
Fixes #2036
> Expose affiliation parameter when listing collaborators

- Octokit.Reactive/Clients/IObservableIssuesEventsClient.cs
- Octokit.Reactive/Clients/ObservableIssuesEventsClient.cs
- Octokit.Tests.Integration/Clients/IssuesEventsClientTests.cs
- Octokit/Clients/IIssuesEventsClient.cs
- Octokit/Clients/IssuesEventsClient.cs
- Octokit/Helpers/ApiUrls.cs
- Octokit/Models/Response/IssueEvent.cs
This PR fixes issues #1979 and #2031 (stack overflow when attempting to retrieve events on issues due to large ID numbers) and replaces the seemingly-abandoned PR #2037.
In addition to changing the types of the relevant field and parameters, the names of the parameters have also been updated (from `number` to `eventId`) to better reflect what's expected to be passed.
> Update IssueEvent ID field from int to long

- Octokit.Reactive/Octokit.Reactive.csproj
- Octokit.Tests.Conventions/Octokit.Tests.Conventions.csproj
- Octokit.Tests.Integration/Octokit.Tests.Integration.csproj
- Octokit.Tests/Octokit.Tests.csproj
- Octokit/Octokit.csproj
Looking to review some of the infrastructure things because how I build and cut Octokit releases currently is very fiddly.
This PR starts us off with reducing our dependency on Mono for builds by adding the `Microsoft.NETFramework.ReferenceAssemblies` package. 
This shouldn't affect our CI builds but I've tested locally on Ubuntu without Mono and (combined with some other small PRs) should get us to a good place.
> add reference assemblies

- Octokit.Reactive/Octokit.Reactive.csproj
- Octokit.Tests.Integration/Octokit.Tests.Integration.csproj
- Octokit/Octokit.csproj
- build/Lifetime.cs
Following on from #2064 
Not sure why some of these dependencies aren't being detected by Dependabot, but for building and linking on Linux without Mono these upgrades are useful.
The change from `SourceLink.Create.GitHub` to `SourceLink.Create.CommandLine` was recommended in https://github.com/ctaggart/SourceLink/issues/321#issuecomment-373508013 due to problems raised previously with this project (the switch didn't happen earlier because it seemed to be an intermittent issue).
> upgrade sourcelink tools and GitVersion

- .github/workflows/netcore.yml
This PR revives #2015 now I have a better grasp on why it was failing locally:
> get CI running on Actions, redux

- .github/workflows/netcore.yml
- README.md
There's a release or two planned before #2055 which increases the minimum supported platforms, and I realise there's some prominent places on the README that list the versions.
These will need to be refreshed when we drop support for older platforms :soon: .
> tidy up the mentions of the supported platforms

- Octokit.Reactive/Octokit.Reactive.csproj
- Octokit.Tests.Conventions/Octokit.Tests.Conventions.csproj
- Octokit.Tests.Integration/Octokit.Tests.Integration.csproj
- Octokit.Tests/Octokit.Tests.csproj
- Octokit/Octokit.csproj
- build/Context.cs
- build/Lifetime.cs
- build/Tasks/Build.cs
- build/Tasks/Package.cs
This was a vestige of the days when we needed Mono to target the classic NetFX targets, and shouldn't be needed now.
> strip CoreOnly usages from codebase as they are no longer needed

- Octokit.Reactive/Octokit.Reactive.csproj
- Octokit/Octokit.csproj
I want to do away with the use of `DotNetCliToolReference` inside here (there's a kludge that I'll explain when we get to it) and for now it looks like `Microsoft.SourceLink.*` are the current ways to achieve this (with some options that I might look into later).
For now, I just want to confirm this works and passes `sourcelink test` for each build.
> switch to Microsoft.SourceLink.GitHub package to perform linking

- build/Context.cs
```
Context.cs(11,19): warning CS0108: 'Context.Configuration' hides inherited member 'CakeContextAdapter.Configuration'. Use the new keyword if hiding was intended. [/Users/shiftkey/src/octokit.net/build/Build.csproj]
```
> we can ignore that this clashes with something it inherits

- Octokit/Models/Common/CheckStatus.cs
Hello!
There is currently an undocumented check suite conclusion ("skipped") that exists in the wild (see https://github.community/t5/GitHub-API-Development-and/Is-quot-skipped-quot-now-a-valid-check-suite-conclusion/m-p/43980#M3900) that causes this library to throw an exception while attempting to load check suites with that conclusion. Since I can't seem to get an answer as to whether or not this has been added to the Checks API, I'm assuming that it has and that this is a documentation deficiency. I'm therefore submitting this trivial PR to add it. Unfortunately I don't think that I was able to run all of the tests (I'm not on Windows) - hope that's okay.
Additionally, do you have any plans to release another version soon? In addition to this issue, I would love to have access to the …
> Add the undocumented (but used) check suite conclusion "skipped"

- Octokit/Models/Common/CheckStatus.cs
Hey Dotnet SDK team 👋 
I work on the team which maintains checks at GitHub and I wanted to add this conclusion ahead of release. This check conclusion will be fully documented on release.
I would also like to note that we could add new check/status states at any time, since adding states would be an additive change. The client-side logic should reflect this in some way so that new states don't break integrators systems.
> Add `stale` check conclusion

- Octokit/Models/Common/CheckStatus.cs
- build/Context.cs
- build/Lifetime.cs
- build/Tasks/FormatCode.cs
I'm still digging into why `FormatCode` decides to insert some stray CR characters on Windows, but for now I'm making this optional rather than always running for local builds.
> move formatting code to optional flag

- Octokit.Tests/Clients/SearchClientTests.cs
- Octokit.Tests/Models/SearchIssuesRequestTests.cs
- Octokit/Models/Request/SearchIssuesRequest.cs
Fixes #2044 
Hello,
I went with the easy way, double quote all labels. It will save us the check (whether the label has spaces or not) since having quotes on normal labels doesn't change anything.
I changed the test to include a test case `label 2` and tested it separately on this repository.
> Double quote issue labels in search API

- Octokit.Tests.Integration/Clients/SearchClientTests.cs
- Octokit.Tests/Clients/SearchClientTests.cs
- Octokit/Models/Request/SearchRepositoriesRequest.cs
> ensure datetime offset is encoded correctly for search APIs

- Octokit/Models/Response/EventInfo.cs
Hello!
Recently, I have started to use this library and I have faced with issue that loading of events for some issues fail because of unrecognized events.
Unfortunately, I didn't find these events in the list of events in [GitHub API](https://developer.github.com/v3/issues/events/) page (it looks like it is pretty outdated) so I can't guarantee that my list is full. But I just added events that I have found in my repo so if you have the full list, please let me know
> Add new events to the EventInfoState enum

- Octokit.Reactive/Clients/IObservableIssuesEventsClient.cs
- Octokit.Reactive/Clients/ObservableIssuesEventsClient.cs
- Octokit.Tests/Clients/IssueTimelineClientTests.cs
- Octokit.Tests/Clients/IssuesEventsClientTests.cs
- Octokit.Tests/Reactive/ObservableIssuesEventsClientTests.cs
- Octokit/Clients/IIssuesEventsClient.cs
- Octokit/Clients/IssueTimelineClient.cs
- Octokit/Clients/IssuesEventsClient.cs
- Octokit/Helpers/AcceptHeaders.cs
- Octokit/Models/Response/IssueEvent.cs
- Octokit/Models/Response/IssueEventProjectCard.cs
- Octokit/Models/Response/TimelineEventInfo.cs
- Octokit/Octokit.csproj
Hello!
I have faced with issue that Event model doesn't contain `project_card` property that is important for all events that are related to GitHub boards (Projects).
For example, for event `added_to_project`, it contains the name of column where issue is added.
For event `moved_columns_in_project`, it contains the previous and new column names.
This PR includes the following changes:
1) Change `EventInfo` model to `IssueEvent` (please see note below for details)
2) Add model `IssueEventProjectCard` accordingly to [GitHub API description](https://developer.github.com/v3/issues/events/#attributes)
3) Add header `IssueEventsApiPreview = "application/vnd.github.starfox-preview"` that is needed to get `project_card` value
4) Update tests
5) Update `Octokit.Reactive` with the same changes …
> Add ProjectCard attribute to events model

- Octokit/Models/Response/ActivityPayloads/PushWebhookCommit.cs
- Octokit/Models/Response/ActivityPayloads/PushWebhookCommitter.cs
- Octokit/Models/Response/ActivityPayloads/PushWebhookPayload.cs
> Updated models to match actual data structures transmitted by GitHub.

- Octokit.Tests.Integration/Clients/RepositoryContentsClientTests.cs
- Octokit/Clients/RepositoryContentsClient.cs
Supersedes #1956
🎩@SimonCropp for the failing test
> improve handling of GetAllContentsByRef where root path is requested

- Octokit.Reactive/Clients/ObservableReferencesClient.cs
- Octokit.Tests.Integration/Clients/ReferencesClientTests.cs
- Octokit.Tests/Clients/ReferencesClientTests.cs
- Octokit/Clients/IReferencesClient.cs
- Octokit/Clients/ReferencesClient.cs
- Octokit/Helpers/ApiUrls.cs
> Allow fully qualified or short references to be used to generate "reference" Uri

- Octokit.Reactive/Clients/IObservableMiscellaneousClient.cs
- Octokit.Reactive/Clients/ObservableMiscellaneousClient.cs
- Octokit.Tests.Integration/Clients/MiscellaneousClientTests.cs
- Octokit.Tests/Clients/MiscellaneousClientTests.cs
- Octokit.Tests/Reactive/ObservableMiscellaneousClientTests.cs
- Octokit/Clients/IMiscellaneousClient.cs
- Octokit/Clients/MiscellaneousClient.cs
- Octokit/GitHubClient.cs
- Octokit/Helpers/ApiUrls.cs
Fixes #1663 
-  [x] make existing methods call new overload with `ApiOptions.None`
-  [x] Adjust for `ApiOptions` parameter
-  [x] Add `null`/`""` checks for `ApiOptions` overloads
> Update MiscellaneousClient to ApiClient approach and add pagination support to GetAllLicenses.

- Octokit.Tests.Integration/Clients/DeploymentStatusClientTests.cs
- Octokit.Tests/Clients/DeploymentStatusClientTests.cs
- Octokit/Clients/DeploymentStatusClient.cs
- Octokit/Helpers/AcceptHeaders.cs
- Octokit/Models/Request/NewDeploymentStatus.cs
- Octokit/Models/Response/DeploymentStatus.cs
https://developer.github.com/changes/2018-10-16-deployments-environments-states-and-auto-inactive-updates/
https://developer.github.com/v3/previews/#deployment-statuses
> Implement Deployment Statuses Preview

- Octokit.Tests/Clients/AuthorizationsClientTests.cs
- Octokit/Clients/AuthorizationsClient.cs
- Octokit/Helpers/ApiUrls.Authorizations.cs
Per ['Deprecating OAuth Application API'](https://developer.github.com/changes/2020-02-14-deprecating-oauth-app-endpoint/)
the HTTP API endpoints called by CheckApplicationAuthentication,
ResetApplicationAuthentication and RevokeApplicationAuthentication are
being deprecated.
This PR updates those APIs to call the new HTTP API endpoints as
documented at the above link.
Amend CheckApplicationAuthentication, ResetApplicationAuthentication and
RevokeApplicationAuthentication to create an object containing the OAuth
access token and to call the single arg version of
ApiUrls.ApplicationAuthorization. The object is used as the request
body.
Amend CheckApplicationAuthentication to use POST.
Amend ResetApplicationAuthentication to use PATCH.
Remove the two arg version of …
> Update OAuth Token operations to new APIs

- Octokit.Tests/Clients/AuthorizationsClientTests.cs
Minor improvements to a couple of tests in
TheGetOrCreateApplicationAuthenticationMethod to verify the interesting
piece of the request object. This brings these tests into line with
recent changes to tests in TheCheckApplicationAuthenticationMethod
et.al.
> Minor improvements to authorization tests

- Octokit/Models/Response/PullRequest.cs
> added Octokit.PullRequest.RequestedTeams property

- Octokit.Tests/Clients/GitHubAppInstallationsClientTests.cs
- Octokit.Tests/Reactive/ObservableGitHubAppInstallationsClientTests.cs
- Octokit/Clients/GitHubAppInstallationsClient.cs
- Octokit/Clients/GitHubAppsClient.cs
A follow-up from #2128 for a case that wasn't caught by our conventions, because it was created in the `Octokit.Clients` namespace rather than the root `Octokit` namespace.
This updates the namespace and adds the necessary route attributes to get the build passing again.
> move GitHubAppInstallationsClient into root namespace

- Octokit.Tests.Integration/Clients/ReleasesClientTests.cs
They were using [Fact] instead of [IntegrationTest] so they would run and fail if no credentials are supplied.
> Mark ReleasesClientTests.TheCreateReleasesMethod tests as integration

- Octokit.Reactive/Clients/IObservablePullRequestReviewRequestsClient.cs
- Octokit.Reactive/Clients/ObservablePullRequestReviewRequestsClient.cs
- Octokit.Tests.Integration/Clients/PullRequestReviewRequestsClientTests.cs
- Octokit.Tests/Clients/PullRequestReviewRequestsClientTests.cs
- Octokit.Tests/Reactive/ObservablePullRequestReviewRequestsClientTests.cs
- Octokit/Clients/IPullRequestReviewRequestsClient.cs
- Octokit/Clients/PullRequestReviewRequestsClient.cs
- Octokit/Helpers/AcceptHeaders.cs
- Octokit/Models/Request/PullRequestReviewRequest.cs
- Octokit/Models/Response/RequestedReviews.cs
Resolves #2122
This is a breaking change in several ways due to changes the API made while under preview:
- requesting teams is now supported, so the response and requests payload had to change
- pagination is no longer supported, so those overloads have been removed
To use the new API there are two static constructors to differentiate between "request users" and "request teams":
```c#
// request specific collaborators
var collaborators = new List<string> { "shiftkey", "ryangribble" };
var requestCollaborators = PullRequestReviewRequest.ForReviewers(collaborators);
// request specific teams
var teams = new List<string> { "frontend-reviewers", "backend-reviewers" };
var requestTeams = PullRequestReviewRequest.ForTeamReviewers(teams);
// request a mixture of both
var requestBothGroups = new …
```
> Graduate review requests to what eventually shipped

- Octokit.Tests/SimpleJsonSerializerTests.cs
- Octokit/Http/SimpleJsonSerializer.cs
- Octokit/Models/Response/Team.cs
Resolves #2052
To aid with testing this PR, you can add a `NuGet.config` file to the root of your project that adds our beta packages feed:
```
<configuration>
<packageSources>
<add key="nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />
<add key="Octokit beta" value=" https://ci.appveyor.com/nuget/octokit-net" />
</packageSources>
</configuration>
```
Then, switch your version to the beta release just published, currently `0.45.0-fix-teams-deseri0005`, and try to verify the fix. I'm still working to try and reproduce this on my side, but I have an idea of where it's lurking...
> bugfix: improve fallback when StringEnum encounters null value

- Octokit.Tests/Clients/AssigneesClientTests.cs
- Octokit.Tests/Clients/AuthorizationsClientTests.cs
- Octokit.Tests/Clients/FollowersClientTests.cs
- Octokit.Tests/Clients/GistsClientTests.cs
- Octokit.Tests/Clients/OrganizationMembersClientTests.cs
- Octokit.Tests/Clients/RepoCollaboratorsClientTests.cs
- Octokit.Tests/Clients/StarredClientTests.cs
- Octokit.Tests/Clients/WatchedClientTests.cs
- Octokit.Tests/GitHubClientTests.cs
- Octokit.Tests/Helpers/NSubstituteExtensions.cs
- Octokit.Tests/Helpers/TaskHelper.cs
- Octokit.Tests/Models/ReadOnlyPagedCollectionTests.cs
- Octokit.Tests/Reactive/ObservableIssuesClientTests.cs
- Octokit.Tests/Reactive/ObservableMilestonesClientTests.cs
- Octokit.Tests/Reactive/ObservablePullRequestReviewCommentsClientTests.cs
- Octokit.Tests/Reactive/ObservablePullRequestReviewsClientTests.cs
- Octokit.Tests/Reactive/ObservablePullRequestsClientTests.cs
- Octokit.Tests/Reactive/ObservableRepositoriesClientTests.cs
`Task.Factory.StartNew` is from a time before we had the ability to wrap a result in a `Task`, and as part of simplifying tests to be able to refactor the internals I decided to drop these usages.
You may also note the `TestSetup.GetApiResponse` helper function - that helps eliminate repetitive code and make the tests more readable.
> remove all usages of TaskFactory in test suite

- Octokit.Tests/Clients/EventsClientTests.cs
- Octokit/Http/SimpleJsonSerializer.cs
- Octokit/Models/Response/ActivityPayloads/ReleaseEventPayload.cs
> Add support for ReleaseEvent payload

- docs/github-apps.md
They don't render on https://octokitnet.readthedocs.io/en/latest/github-apps/
> Replace emojis with Unicode characters

- Octokit.Tests/Clients/Enterprise/EnterpriseProbeTests.cs
- Octokit.Tests/Exceptions/AbuseExceptionTests.cs
- Octokit.Tests/Http/ApiInfoParserTests.cs
- Octokit/Clients/Enterprise/EnterpriseProbe.cs
- Octokit/Exceptions/AbuseException.cs
- Octokit/Helpers/ConcurrentCache.cs
- Octokit/Http/ApiInfoParser.cs
- Octokit/Http/RateLimit.cs
Related to #2161 but probably not the full fix, given we pass around a dictionary and lookup by key, rather than following the HTTP spec and supporting case insensitive headers.
I chatted with some others inside GitHub and they reminded me about [RFC 2616, section 4.2](https://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.2):
> Each header field consists of a name followed by a colon (":") and the field value. **Field names are case-insensitive.**
I'd love to get to a place where we can leverage `HttpResponseHeaders` but we are very tightly coupled to `IResponse` in the internals, and it's this component that manages the headers as a dictionary:
https://github.com/octokit/octokit.net/blob/a25863f2289050fdfb091ba1ff2808cd1218d7e1/Octokit/Http/IResponse.cs#L32-L35
The setup is here, …
> handle case insensitive headers when parsing for API rate limiting

- Octokit.Reactive/Clients/IObservableRepositoryContentsClient.cs
- Octokit.Reactive/Clients/ObservableRepositoryContentsClient.cs
- Octokit.Tests/Clients/RepositoryContentsClientTests.cs
- Octokit.Tests/Reactive/ObservableRepositoryContentsClientTests.cs
- Octokit/Clients/IRepositoryContentsClient.cs
- Octokit/Clients/RepositoryContentsClient.cs
- Octokit/Helpers/AcceptHeaders.cs
- Octokit/Helpers/ApiUrls.cs
- Octokit/Http/ApiConnection.cs
- Octokit/Http/Connection.cs
- Octokit/Http/HttpClientAdapter.cs
- Octokit/Http/IApiConnection.cs
- Octokit/Http/IConnection.cs
This allows to spare a little over 100ms in my tests on small files vs using the `GetAllContentsByRef` API.
Fixes #1651
> Add support to get raw file content as byte[]

- Octokit.Tests/Models/CheckRunEventTests.cs
- Octokit/Models/Response/ActivityPayloads/CheckRunEventPayload.cs
- Octokit/Models/Response/CheckRunRequestedAction.cs
This PR closes #2195. It adds support for handling the ```requested_action``` field when present on Check Run event payloads. This field is documented in the developer docs, but wasn't exposed in Octokit for .NET:
https://developer.github.com/webhooks/event-payloads/#check_run
> Deserialize requested_action field on check_run events.

- Octokit.Tests/GitHubClientTests.cs
- Octokit/Clients/ChecksClient.cs
The `ChecksClient` constructor originally took a concrete `ApiConnection` object as an argument. This PR changes the constructor to match all other clients in the library that take an `IApiConnection` argument.
This PR also adds a unit test theory, that asserts that all clients nested under `GitHubClient` follow this behaviour.
The assertion ensures
* All client interfaces have a publically visible concrete implementation type
* The Implementation type has a publically visible constructor that takes either `IConnection` or `IApiConnection` as its single argument.
> ChecksClient constructor should take interface arguments

- Octokit.Tests.Integration/Clients/ProjectCardsClientTests.cs
- Octokit/Models/Request/NewProjectCard.cs
The v3 GitHub API [now supports adding Pull Requests as project cards](https://developer.github.com/v3/projects/cards/#create-a-project-card), which was disabled when support for project cards was initially added to OctoKit. This PR reintroduces support for PRs as cards, including a new integration test.
> Add support for creating project cards from pull requests

- Octokit.Tests.Integration/Clients/RepositoriesClientTests.cs
- Octokit/Models/Response/Repository.cs
> Update Repository to include WatchersCount

- Octokit.Tests/Exceptions/RateLimitExceededExceptionTests.cs
- Octokit.Tests/Http/ApiInfoParserTests.cs
- Octokit/Exceptions/RateLimitExceededException.cs
- Octokit/Http/ApiInfo.cs
- Octokit/Http/ApiInfoParser.cs
- Octokit/Http/HttpClientAdapter.cs
* Adds new read-only property `ServerTimeDifference` of type `TimeSpan` to the `ApiInfo` class. An optional argument is added to the existing contructor.
* The `HttpClientAdapter` will inject a synthetic header named `X-Octokit-ReceivedDate` into the response headers providing an RFC1123 date-time-string specifying the time as obsoverved locally on the client when the response was received. The synthetic header name is added as a publically visible constant on the `ApiInfoParser` class.
* Adds a new instance method `GetRetryAfterTimeSpan` to `RateLimitExceededException` that allows clients to obtain the amount of time to wait until the RateLimit-Window resets.
In some scenarios it is useful to be able to calculate the appearent difference between the clock on a client computer and the …
> Add Server Time Difference to ApiInfo

- docs/demos/exploring-pull-requests.md
- docs/getting-started.md
- docs/index.md
- docs/issues.md
Documentation was still refering to files on the master branch
> Fix documentation: change all master branch references to main

- Octokit/Clients/ICheckSuitesClient.cs
- Octokit/Clients/IRepositoryInvitationsClient.cs
- Octokit/Clients/MigrationsClient.cs
- Octokit/Clients/RepositoryInvitationsClient.cs
- Octokit/Clients/UserGpgKeysClient.cs
- Octokit/Clients/UserKeysClient.cs
- Octokit/Exceptions/RateLimitExceededException.cs
- Octokit/Helpers/ApiExtensions.cs
- Octokit/Helpers/ApiUrls.cs
- Octokit/Http/ApiConnection.cs
- Octokit/Http/ApiInfo.cs
- Octokit/Http/HttpClientAdapter.cs
- Octokit/Http/Response.cs
- Octokit/Models/Request/IssueUpdate.cs
- Octokit/Models/Request/NewArbitraryMarkDown.cs
- Octokit/Models/Request/NewRepository.cs
- Octokit/Models/Request/NewTreeItem.cs
- Octokit/Models/Request/SearchRepositoriesRequest.cs
- Octokit/Models/Response/Account.cs
- Octokit/Models/Response/Author.cs
- Octokit/Models/Response/CheckRun.cs
- Octokit/Models/Response/CheckSuite.cs
- Octokit/Models/Response/PullRequest.cs
- Octokit/Models/Response/UserRenameResponse.cs
- Octokit/Models/Response/Verification.cs
- Octokit/SimpleJson.cs
Ironically the commit message has grammar errors :(
> Spellcheck round 2

- Octokit.Tests/Models/SearchRepositoryRequestTests.cs
- Octokit/Models/Request/SearchRepositoriesRequest.cs
Search Repositories by license is supported by github api:
https://help.github.com/articles/searching-repositories#search-by-license
Currently only a list of licenses is supported as stated in : 
https://docs.github.com/en/free-pro-team@latest/github/creating-cloning-and-archiving-repositories/licensing-a-repository#searching-github-by-license-type.
But using GitHub search I was able to find more licenses types keys.
https://github.com/search/advanced
This PR, adds all licenses found right now on GitHub.
One of the issues found while developing is that Octokit.License class does exist, while Octokit.Langues exist inside SearchRepositoriesRequest.cs and is also used on different classes I think we should move it later, for this PR I named the enum that has the licenses as : …
> Add license to repository search

- .github/workflows/netcore.yml
- appveyor.yml
- build/Build.csproj
- build/Lifetime.cs
- build/Program.cs
This PR updates Cake Frosting to 1.0 and addresses breaking changes introduced with that release.
**Additional**
* Pinned coverlet version as latest not compact with 3.1
* Updated GitVersion as previous not compatible with GitHub actions
* Updated GitHub actions setup .NET to supported version
> (build) Updated Cake Frosting to version 1.0.0

- README.md
And bring the command line example up to the modern age!
> Update the README to link to NuGet

- CONTRIBUTING.md
The previous link redirected to https://github.com/octokit/octokit.net/issues?q=label%3Aup-for-grabs, which would also show closed issues; the new link only shows open issues.
> Update 'up-for-grabs' link in CONSTRIBUTING.md

- Octokit.Tests.Integration/Clients/RepositoriesClientTests.cs
- Octokit/Models/Request/NewRepository.cs
- Octokit/Models/Request/RepositoryUpdate.cs
- Octokit/Models/Response/Repository.cs
Hello, hopefully this is a simple change, I just wanted to add the `DeleteBranchOnMerge`option when creating or updating repositories. This is supported by the [Github v3 API](https://docs.github.com/en/free-pro-team@latest/rest/reference/repos#create-an-organization-repository). 
I couldn't find any open issues for it to link to (should I create one?). 
I've added all the tests I think I need to, but I haven't run the integration tests (I assume you have some CI setup to run these but if not let me know and I'll go through the pain of setting them up).
This is my first time contributing so please tell me if I've done anything incorrectly. I did read the contributions guide but I didn't see the point in adding a checklist as this is such a simple change.
> [Ready for review] Add DeleteBranchOnMerge option for repositories

- Octokit.Tests/Models/PullRequestCommitTests.cs
- Octokit/Models/Response/PullRequestCommit.cs
PullRequestCommit Author and Committer fields were mistakenly typed with
Committer when they should be of type User.
Previously the types of properties were:
* `PullRequestCommit.Author/Committer`: `Committer`
* `Commit.Author/Committer`: `Committer`
Correct types should be:
* `PullRequestCommit.Author/Committer`: `User`
* `Commit.Author/Committer`: `Committer`
These fields always fail to deserialize in the API calls but produce no
errors, only objects with default values.
> Fix property types in PullRequestCommit

- Octokit/Models/Response/Organization.cs
Organizations do not have some properties from https://developer.github.com/v3/orgs/ like description. Add missed properties for correct result parsing.
> feat: add missed props for organization

- Octokit/Models/Request/SearchIssuesRequest.cs
Allows you to search for issues with no project.
> Add "project" to the IssueNoMetadataQualifier

- Octokit.Reactive/Clients/IObservableReleasesClient.cs
- Octokit.Reactive/Clients/ObservableReleasesClient.cs
- Octokit.Tests/Clients/ReleasesClientTests.cs
- Octokit/Clients/IReleasesClient.cs
- Octokit/Clients/ReleasesClient.cs
- Octokit/Http/ApiConnection.cs
- Octokit/Http/Connection.cs
- Octokit/Http/IApiConnection.cs
- Octokit/Http/IConnection.cs
Small spike for #1840 
Added an optional cancellation token to `IReleasesClient.UploadAsset(...)`.
To make it easier to continue this work, I did the same for all the `Post` methods in `IApiConnection` and `IConnection` as well.
> Add cancellation token support for release assets uploading

- Octokit.Tests/Models/DeploymentTests.cs
- Octokit/Models/Request/NewDeployment.cs
When serializing the `NewDeployment` type, the `Payload` is serialized as an escaped string because JSON.NET doesn't know it's meant to be JSON.
This causes a problem when you call the API because the Payload is supposed to be a JSON dictionary that's just part of the overall payload. It's not supposed to be an escaped string.
That's why the JSON deserializer fails on it. Not only that, any deployments created using the current Octokit.net will create an invalid payload.
This PR fixes it by changing the type of `Payload` to a dictionary. THIS IS A BREAKING CHANGE, but the old behavior was broken so it forces a new correct behavior.
Fixes #2250
> Change Payload to a Dictionary<string, string>

- Octokit.Tests/Clients/RepositoriesClientTests.cs
- Octokit.Tests/Models/RepositoryRequestTests.cs
- Octokit/Clients/RepositoriesClient.cs
- Octokit/Helpers/AcceptHeaders.cs
- Octokit/Models/Request/NewRepository.cs
- Octokit/Models/Request/RepositoryRequest.cs
- Octokit/Models/Request/RepositoryUpdate.cs
- Octokit/Models/Response/Repository.cs
> preview support for repository visibility

- .github/workflows/netcore.yml
- .github/workflows/publish.yml
- global.json
.NET 5 is fine for building projects that target older versions of .NET. This also should fix the AppVeyor build which fails because the latest `coverlet.console` only supports .NET 5.
> Move the build to .net 5

- Octokit/Helpers/ReferenceExtensions.cs
- README.md
- ReleaseNotes.md
Also deprecates an overload on `ReferenceExtensions.CreateBranch` that was hard-coded to `master`.
Closes #2263
> cleanup some mentions of master branch in codebase

- README.md
Just happened to notice while browsing. After the conversion to the `main` branch, some text and old links remained.
> fix(docs): master --> main text in README

- Octokit.Reactive/Clients/IObservableOauthClient.cs
- Octokit.Reactive/Clients/ObservableOauthClient.cs
- Octokit.Tests/Clients/OauthClientTests.cs
- Octokit/Clients/IOAuthClient.cs
- Octokit/Clients/OAuthClient.cs
- Octokit/Helpers/ApiUrls.cs
- Octokit/Models/Request/OauthDeviceFlowRequest.cs
- Octokit/Models/Request/OauthTokenRequestForDeviceFlow.cs
- Octokit/Models/Response/OauthDeviceFlowResponse.cs
- Octokit/Models/Response/OauthToken.cs
Adds support for the Device flow authentication pattern: https://docs.github.com/en/developers/apps/authorizing-oauth-apps#device-flow 
Resolves #2308
Usage:
```
var github = new GitHubClient(new ProductHeaderValue("test"));
string clientId = "<clientId>";
var request = new OauthDeviceFlowRequest(clientId);
request.Scopes.Add("repo");
var deviceFlowResponse = await github.Oauth.InitiateDeviceFlow(request);
Console.WriteLine(deviceFlowResponse.UserCode);
OpenWebPage(deviceFlowResponse.VerificationUri);
var token = await github.Oauth.CreateAccessTokenForDeviceFlow(clientId, deviceFlowResponse);
Console.WriteLine(token.AccessToken);
```
> Adding support for the Device Flow Oauth authentication pattern

- .github/stale.yml
We are in need of some house cleaning to get us back to a good "supported" state.  This will activate the stalebot to help us parse through any issues that are either no longer relevant, need to be rethought, or are not able to be addressed.  
Note:  It's not that these issues are not important or useful.  We simply need a clear starting point to begin actively introducing improvements and changes into this SDK.  If anyone feels like the issues that are marked as stale from the bot still need to be opened they can label them with the `pinned` and `followup-needed` labels with some details on the current state of things so that it will not auto close. That way we can have a closer look at the issue and see what we need to do to get it resolved.
> Creates the config file for stalebot to help us clean up old/inactive issues

- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
- .devcontainer/setup.sh
- .vscode/tasks.json
This adds a simple Codespaces configuration, `.devcontainer/devcontainer.json`, to the project.
It uses v3.1 of the .NET Core SDK from Docker Hub, installs Python 3 and `mkdocs` to support building the docs and includes useful VS Code extensions for working on the project.
I also improve the Visual Studio Code tasks definitions (`.vscode/ tasks.json`), adding pre-defined tasks for running unit and convention tests and building the docs.
Codespaces magic means that, when you build the docs, the port will automatically be opened so you can view the docs in real time at `localhost:4000`.
> Configure the project for GitHub Codespaces

- .vscode/tasks.json
This fixes the Visual Studio Code tasks configuration file (`.vscode/tasks.json`), which somehow got corrupted, meaning that it was no longer valid and didn't work.
> Fix the Visual Studio Code tasks configuration file

- .vscode/settings.json
This adds explicit configuration to `.vscode/settings.json` so we use two spaces for indentation, rather than relying on the user's own settings or automatic detection. It also fixes the indentation of the settings file itself 😂 😓
> Explicitly configure identation settings for VSCode

- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
- .devcontainer/setup.sh
This switches our Codespaces setup to use a more standard one based on the official `microsoft/vscode-dev-containers` configuration.
> Use the official Codespaces template configuration, rather than something homegrown

- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
- .vscode/settings.json
These changes are needed so that when working on code spaces and on OmniSharp server will properly start - https://github.com/OmniSharp/omnisharp-vscode#requirements
> Dev container rework to support OmniSharp changes

- Octokit.Reactive/Clients/IObservableRepositoriesClient.cs
- Octokit.Reactive/Clients/ObservableRepositoriesClient.cs
- Octokit.Tests.Integration/Clients/RepositoriesClientTests.cs
- Octokit.Tests.Integration/Helpers/GithubClientExtensions.cs
- Octokit.Tests/Clients/RepositoriesClientTests.cs
- Octokit/Clients/IRepositoriesClient.cs
- Octokit/Clients/RepositoriesClient.cs
- Octokit/Helpers/AcceptHeaders.cs
- Octokit/Helpers/ApiUrls.cs
- Octokit/Models/Request/NewRepository.cs
- Octokit/Models/Request/NewRepositoryFromTemplate.cs
Fixes [#2148](https://github.com/octokit/octokit.net/issues/2148)
Adding the ability to create repositories from a template. Most code borrowed from FrediKats PR 2187 but with fixed tests. Baptiste preview tag added to all repository endpoints mentioned in the GitHub Api documentation.
Further testing and IObservable code added to satisfy tests.
> Support for IsTemplate and Create Template from Repository

- docs/getting-started.md
I was just curious to know about that `ProductHeaderValue` type and found references in this file. However the links were not 404's but also not what was originally intended. I didn't check the whole file, just these two URLs.
> fix: links into github documentation

- Octokit/Models/Request/Permission.cs
Added the following permissions maintain and triage based on the GitHub documentation
https://docs.github.com/en/rest/reference/teams#add-or-update-team-repository-permissions
> Update permissions based on GitHub documentation

- Octokit.Tests/Models/DeploymentTests.cs
- Octokit/Models/Request/NewDeployment.cs
- Octokit/Models/Response/Deployment.cs
- Changed `NewDeployment` Task property to `string`
- Added `string Task` property to `Deployment` response
- Updated tests
Changes here align the project to the intended usage based on the documentation linked below.
> The task parameter is used by the deployment system to allow different execution paths. In the web world this might be `deploy:migrations` to run schema changes on the system. In the compiled world this could be a flag to compile an application with debugging enabled.
https://docs.github.com/en/rest/reference/deployments#create-a-deployment
Fixes #2412
> Deployment task is arbitrary string value

- Octokit/Models/Response/GitHubApp.cs
> Adds the slug field to the GitHubApp response object

- Octokit/Models/Request/NewRepository.cs
> Adding squash title to NewRepository

- Octokit/Clients/IOrganizationsClient.cs
- Octokit/Clients/OrganizationsClient.cs
> Update organizations-related `GetAllForUser` method docs to make it clear that only public memberships are returned

- Octokit.Tests.Integration/Clients/RepositoryContentsClientTests.cs
- Octokit/Helpers/ApiUrls.cs
Fixes #2390 
Fixes #2243 
Trimming trailing slashes from user passed paths that appear before query string parameters
> Trimming trailing slashes from user passed paths

- Octokit.Tests/Exceptions/ApiExceptionTests.cs
- Octokit/Exceptions/ApiException.cs
When we receive an ApiException and the ContentType is null, if we try to log the message (or otherwise call the ToString method), we're throwing an NullReferenceException because HttpResponseBodySafe is accessing ContentType without checking if it's null.
> Fix null reference access when ContentType is null

- Octokit/Models/Response/Repository.cs
Subscribers_count shows the actual watchers_count. Many people think they are retrieving the watchers_count, but are actually retrieving the stargazers_count...
This is because the GitHub UI is still calling subscribers, "Watchers".
To prevent many others from falling into this trap, a warning should be added to the watchers_count property.
On top of this, subscribers_count is no longer deprecated as far as the GitHub documentation goes.
Fixes #2509
Signed-off-by: Brend Smits <brend.smits@philips.com>
> move deprecation warning from subscribers_count to watchers_count.

- Octokit.Reactive/IObservableGitHubClient.cs
- Octokit.Reactive/ObservableGitHubClient.cs
- Octokit/GitHubClient.cs
- Octokit/Http/Connection.cs
- Octokit/Http/IConnection.cs
- Octokit/Http/IHttpClient.cs
- Octokit/IGitHubClient.cs
updating code docs to reflect what SetConnectionTimeout does. Fixes #2506
> [WIP] update code docs for SetRequestTimeout

- Octokit.Reactive/Octokit.Reactive.csproj
- Octokit.Tests.Integration/Clients/RepositoriesClientTests.cs
- Octokit.Tests/Clients/RepositoriesClientTests.cs
- Octokit.Tests/Reactive/ObservableRepositoriesClientTests.cs
- Octokit/Models/Request/RepositoryUpdate.cs
- Octokit/Octokit.csproj
- build/Context.cs
- build/Lifetime.cs
- build/Tasks/Build.cs
- build/Tasks/ConventionTests.cs
- build/Tasks/IntegrationTests.cs
- build/Tasks/Package.cs
- build/Tasks/Restore.cs
- build/Tasks/UnitTests.cs
- build/Tasks/ValidateLINQPadSamples.cs
- build/Utilities/ToolInstaller.cs
Fixes: https://github.com/octokit/octokit.net/issues/2500
Already covered by the explanation via @JamieMagee - this needs to be done so we can move forward with the framework and innovate using the new APIs and assemblies.
Highlights from the [issue](https://github.com/octokit/octokit.net/issues/2500) description:
> .NET Framework 4.6 (and 4.6.1) went out of support on April 26, 2022. Continuing to publish Octokit for this target adds a support burden.
> .NET standard 2.0 covers .NET Framework 4.6.2 already.
> Supporting a single target framework, .NET standard 2.0, would simplify maintenance of this project while supporting all target frameworks currently supported upstream.
For reference, these are the supported versions going forward
.NET implementation | Version support
-- | --
.NET …
> Drop support for .NET 4.6

- Octokit.Tests/Clients/RepositoriesClientTests.cs
- Octokit.Tests/Clients/RepositoryBranchesClientTests.cs
- Octokit/Clients/RepositoriesClient.cs
- Octokit/Clients/RepositoryBranchesClient.cs
> Fixing issues with two factor authentication overload and certain endpoints

- Octokit.Reactive/Clients/IObservableIssuesClient.cs
- Octokit.Reactive/Clients/ObservableIssuesClient.cs
- Octokit.Tests.Integration/Clients/IssuesClientTests.cs
- Octokit.Tests/Models/IssueTest.cs
- Octokit/Clients/IIssuesClient.cs
- Octokit/Clients/IssuesClient.cs
- Octokit/Models/Common/LockReason.cs
- Octokit/Models/Response/Issue.cs
Added LockReason enum, added activelockreason property to Issue class. 
Fixes issue #2248
> add active lock reason to issue

- Octokit.Reactive/Clients/IObservableReactionsClient.cs
- Octokit.Reactive/Clients/ObservableReactionsClient.cs
- Octokit.Tests.Integration/Clients/RepositoriesClientTests.cs
- Octokit.Tests/Clients/ReactionsClientTests.cs
- Octokit.Tests/Exceptions/ApiExceptionTests.cs
- Octokit.Tests/Reactive/ObservableReactionsClientTests.cs
- Octokit/Clients/IReactionsClient.cs
- Octokit/Clients/ReactionsClient.cs
- Octokit/Exceptions/ApiException.cs
- Octokit/Helpers/ApiUrls.cs
- Octokit/Models/Response/Repository.cs
I tried to also work out why the net462 tests fail on binary deserialization, but I couldn't. One for another time.
> Fixing a number of warnings for a cleaner build

- Octokit.AsyncPaginationExtension/Extensions.cs
- Octokit.AsyncPaginationExtension/IPaginatedList.cs
- Octokit.AsyncPaginationExtension/LazyList.cs
- Octokit.AsyncPaginationExtension/Octokit.AsyncPaginationExtension.csproj
- Octokit.AsyncPaginationExtension/PaginatedList.cs
- Octokit.Tests/AsyncEnumerableExtensionTests.cs
- Octokit.Tests/Octokit.Tests.csproj
- Octokit.sln
Compared to my original design draft I've decided to opt for a slightly more complex approach involving a class dedicated to providing both sequential as well as random access. It caches everything to make multiple enumerations (that possibly all don't iterate to the very end, saving resources) faster. Ultimately the cost to this should be minimal, as cacheless sequential access likely allocates the same amount of memory, just freeing it immediately afterwards.
I've written a script to generate the Extensions.cs file as it is basically just a bunch of boilerplate.
Here it is in its entirety:
```cs
using System.Text.RegularExpressions;
var root = args.ElementAtOrDefault(0);
while (root == null) {
Console.WriteLine("Please enter the octokit project folder:");
root = Console.ReadLine();
}
if …
```
> Add AsyncPaginationExtensions

- Octokit.Tests/Clients/UsersClientTests.cs
- Octokit.Tests/Exceptions/ApiExceptionTests.cs
- Octokit.Tests/Exceptions/ApiValidationExceptionTests.cs
- Octokit.Tests/Exceptions/RateLimitExceededExceptionTests.cs
- Octokit.Tests/Helpers/BindaryFormatterHelpers.cs
- Octokit.Tests/Http/RateLimitTests.cs
Also removed the need to have binary formatter tests run only in framework as it also works on netcoreapp3.1.
#2496
> Fixing the use of the binary formatter in net461 so all unit tests now pass.

- Octokit.Reactive/Clients/IObservableOrganizationMembersClient.cs
- Octokit.Reactive/Clients/ObservableOrganizationMembersClient.cs
- Octokit.Tests.Integration/Clients/OrganizationMembersClientTests.cs
- Octokit/Clients/IOrganizationMembersClient.cs
- Octokit/Clients/OrganizationMembersClient.cs
- Octokit/Helpers/ApiUrls.cs
close #2531 
ref to https://docs.github.com/en/rest/orgs/members#list-failed-organization-invitations
> feat: implement getting failed org invites

- .devcontainer/Dockerfile
- .github/workflows/netcore.yml
- .github/workflows/publish.yml
- .vscode/launch.json
- Octokit.AsyncPaginationExtension/Extensions.cs
- Octokit.AsyncPaginationExtension/Octokit.AsyncPaginationExtension.csproj
- Octokit.Generators/AsyncPaginationExtensionsGenerator.cs
- Octokit.Generators/Generator.cs
- Octokit.Generators/Octokit.Generators.csproj
- Octokit.Generators/README.md
- Octokit.sln
Fixes: https://github.com/octokit/octokit.net/issues/2534
This PR intends to add an iteration 0 for code generation. The initial generator was sourced from the work @Saalvage did when adding the [AsyncPaginationExtensions](https://github.com/octokit/octokit.net/pull/2516).
This PR:
Note: The existing test coverage for the extensions is still intact, and I intentionally left testing off of the generations project because:
1. It was redundant to test the generated extensions
2. This project is effectively a prototype for code generation and is proven through compiling the source it has generated
> Add generators project for source generation

- Octokit.Tests.Integration/Clients/OrganizationClientTests.cs
- Octokit/Models/Response/Plan.cs
Unable to test Enterprise options however.
fixes #2405
> Adding seats and filled seats to plan response.

- Octokit.Reactive/Clients/IObservableIssuesClient.cs
- Octokit.Reactive/Clients/IObservableLockUnlockClient.cs
- Octokit.Reactive/Clients/IObservablePullRequestsClient.cs
- Octokit.Reactive/Clients/ObservableIssuesClient.cs
- Octokit.Reactive/Clients/ObservableLockUnlockClient.cs
- Octokit.Reactive/Clients/ObservablePullRequestsClient.cs
- Octokit.Tests.Integration/Clients/IssuesClientTests.cs
- Octokit.Tests.Integration/Clients/IssuesEventsClientTests.cs
- Octokit.Tests.Integration/Clients/PullRequestsClientTests.cs
- Octokit.Tests.Integration/Reactive/ObservableIssuesClientTests.cs
- Octokit.Tests/Clients/IssuesClientTests.cs
- Octokit.Tests/Reactive/ObservableIssuesClientTests.cs
- Octokit/Clients/IIssuesClient.cs
- Octokit/Clients/ILockUnlockClient.cs
- Octokit/Clients/IPullRequestsClient.cs
- Octokit/Clients/IssuesClient.cs
- Octokit/Clients/LockUnlockClient.cs
- Octokit/Clients/PullRequestsClient.cs
- Octokit/Models/Response/PullRequest.cs
- docs/issues.md
add active lock reason to PR. 
Since every pull request is an issue and the lock and unlock are on the IIssuesClient, updates the docs to reflect the design.
Fixes #2248
> add active lock reason to PR

- Octokit.Reactive/Clients/IObservablePullRequestsClient.cs
- Octokit.Reactive/Clients/ObservablePullRequestsClient.cs
- Octokit.Tests/Clients/PullRequestsClientTests.cs
- Octokit.Tests/Reactive/ObservablePullRequestsClientTests.cs
- Octokit/Clients/IPullRequestsClient.cs
- Octokit/Clients/PullRequestsClient.cs
This fixes #2552 by allowing you to pass an ApiOptions object to the Files method of PullRequestsClient.
Files can still be called without ApiOptions and will simply pass on ApiOptions.None then.
> Add ability to pass ApiOptions to PullRequestsClient.Files

- Octokit.Reactive/Clients/IObservableRepoCollaboratorsClient.cs
- Octokit.Reactive/Clients/ObservableRepoCollaboratorsClient.cs
- Octokit.Tests/Clients/RepoCollaboratorsClientTests.cs
- Octokit/Clients/IRepoCollaboratorsClient.cs
- Octokit/Clients/RepoCollaboratorsClient.cs
Close #2558 and close #2373 too.
I wrote such a local test:
```csharp
[Fact]
public async Task AddCollaborator_ThrowsNoException()
{
GitHubClient client = new GitHubClient(new ProductHeaderValue("name"))
{
Credentials = new Credentials("token")
};
var response = await client.Repository.Collaborator.Add("owner", "name", "user", new CollaboratorRequest(Permission.Admin));
}
```
There was no exception and response was valid. An old version of this method throws ApiException (this case I have also covered with the corresponding test).
> Fix failure with 201 status code on adding a collaborator

- Octokit.Reactive/Clients/IObservableReleasesClient.cs
- Octokit.Reactive/Clients/ObservableReleasesClient.cs
- Octokit.Tests/Clients/ReleasesClientTests.cs
- Octokit/Clients/IReleasesClient.cs
- Octokit/Clients/ReleasesClient.cs
- Octokit/Models/Request/GenerateReleaseNotesRequest.cs
- Octokit/Models/Response/GeneratedReleaseNotes.cs
- docs/releases.md
This adds support for the .../releases/generate-notes endpoint [here](https://docs.github.com/en/rest/releases/releases#generate-release-notes-content-for-a-release)
This would allow individuals to auto-generate release notes before creating a release. 
No issue was found for this particular topic to reference.
> [Releases]Added support for generating release notes

- Octokit.Reactive/Clients/IObservablePackageVersionsClient.cs
- Octokit.Reactive/Clients/IObservablePackagesClient.cs
- Octokit.Reactive/Clients/ObservablePackageVersionsClient.cs
- Octokit.Reactive/Clients/ObservablePackagesClient.cs
- Octokit.Reactive/IObservableGitHubClient.cs
- Octokit.Reactive/ObservableGitHubClient.cs
- Octokit.Tests.Integration/Clients/PackageVersionTests.cs
- Octokit.Tests.Integration/Clients/PackageVersionsClientTests.cs
- Octokit.Tests.Integration/Clients/PackagesClientTests.cs
- Octokit.Tests.Integration/Clients/PackagesTests.cs
- Octokit.Tests/Clients/PackageVersionsClientTests.cs
- Octokit.Tests/Clients/PackagesClientTests.cs
- Octokit.Tests/Reactive/ObservablePackageVersionsTests.cs
- Octokit.Tests/Reactive/ObservablePackagesTests.cs
- Octokit/Clients/IPackageVersionsClient.cs
- Octokit/Clients/IPackagesClient.cs
- Octokit/Clients/PackageVersionsClient.cs
- Octokit/Clients/PackagesClient.cs
- Octokit/GitHubClient.cs
- Octokit/Helpers/ApiUrls.cs
- Octokit/Helpers/Ensure.cs
- Octokit/Helpers/EnumExtensions.cs
- Octokit/Helpers/ParameterBuilder.cs
- Octokit/IGitHubClient.cs
- Octokit/Models/Common/PackageType.cs
- Octokit/Models/Common/PackageVersionState.cs
- Octokit/Models/Common/PackageVisibility.cs
- Octokit/Models/Response/Package.cs
- Octokit/Models/Response/PackageVersion.cs
> Adding Packages Api

- Octokit.Tests/Clients/MiscellaneousClientTests.cs
- Octokit/Clients/MiscellaneousClient.cs
- Octokit/Http/AssignableExtensions.cs
- Octokit/Http/JsonHttpPipeline.cs
Adding in assignable extensions to allow us to tell whether a type of IDictionary<T1,T2> which allows us to deserialise an object list to a dictionary. Currently if you use IDictionary<T1,T2> it is not recognised as a dictionary type and the body is wrapped as if it were an array of 1 object.
closes #2576
> Fix deserializing of Emoji types

- Octokit.Tests/Clients/MetaClientTests.cs
This came up as a result of a combo merge.  This PR simply adds the new fields to the tests that the related PRs added.
Currently, the mainline build is failing due to the test missing the additional fields.
Related:
https://github.com/octokit/octokit.net/pull/2579
https://github.com/octokit/octokit.net/pull/2574
https://github.com/octokit/octokit.net/pull/2577
> updates tests to include new fields

- Octokit.Tests/Models/CheckSuiteEventTests.cs
- Octokit/Models/Response/ActivityPayloads/ActivityPayload.cs
> Base classes need protected setters, ActivityPayload had privates

- Octokit.Tests/Clients/ReleasesClientTests.cs
- Octokit/Clients/ReleasesClient.cs
- Octokit/Helpers/ApiUrls.cs
- docs/releases.md
Fixes #2589.
I also changed the documentation for `GenerateReleaseNotes`, adding links to relevant GitHub docs, an example of generated text, and clearer example code.
> Use correct methods and URL to generate release notes

- Octokit/Models/Request/NewRelease.cs
- Octokit/Models/Request/ReleaseUpdate.cs
- docs/releases.md
Enable generating release notes during creation of a release.
> Add `NewRelease.GenerateReleaseNotes` property

- Octokit/Models/Request/RepositoryUpdate.cs
- Octokit/Models/Response/Repository.cs
As per https://docs.github.com/en/rest/repos/repos#update-a-repository, there is the following setting:
> `allow_update_branch`  `boolean`
Either `true` to always allow a pull request head branch that is behind its base branch to be updated even if it is not required to be up to date before merging, or false otherwise.
> 
> Default: `false`
> Adding repo allowupdatebranch

- Octokit.Reactive/Clients/IObservableEnvironmentsClient.cs
- Octokit.Reactive/Clients/IObservableRepositoriesClient.cs
- Octokit.Reactive/Clients/IObservableRepositoryDeployEnvironmentsClient.cs
- Octokit.Reactive/Clients/ObservableEnvironmentsClient.cs
- Octokit.Reactive/Clients/ObservableRepositoriesClient.cs
- Octokit.Tests/Clients/EnvironmentsClientTests.cs
- Octokit/Clients/DeploymentEnvironmentsClient.cs
- Octokit/Clients/IRepositoriesClient.cs
- Octokit/Clients/IRepositoryDeployEnvironmentsClient.cs
- Octokit/Clients/RepositoriesClient.cs
- Octokit/Helpers/ApiUrls.cs
- Octokit/Models/Request/ApiOptions.cs
- Octokit/Models/Response/DeploymentEnvironment.cs
- Octokit/Models/Response/DeploymentEnvironmentsResponse.cs
Let's add Environment API support.
https://github.com/octokit/octokit.net/issues/2329
As a 1st step I've implemented GetAll methods for Environments.
> Added Environments API - GetAll list only feature

- Octokit.Tests.Integration/Clients/SearchClientTests.cs
- Octokit.Tests/Models/SearchIssuesRequestTests.cs
- Octokit/Models/Request/SearchIssuesRequest.cs
- docs/search.md
Resolves #2620
----
* No way to filter issues with locked unlocked status
* Use IssueIsQualifier as Locked and Unlocked to filter
* none
----
> add islocked filter to SeachIssuesRequest

- Octokit.Reactive/IObservableGitHubClient.cs
- Octokit.Reactive/ObservableGitHubClient.cs
- Octokit/IGitHubClient.cs
- Octokit/Models/Response/PagesBuild.cs
- Octokit/Models/Response/PullRequestReview.cs
- Octokit/Models/Response/PullRequestReviewComment.cs
- docs/getting-started.md
This doesn't fix a created issue, but rather something that was bothering me for a little while. 
----
* Many instances in comments and docs of GitHub were incorrectly stylized "Github". 
* Instances of "Github" in comments and docs have been fixed to read "GitHub". 
* N/A
----
* N/A
----
> Remove instances of lower-case h

- Octokit/Models/Response/WorkflowRunStatus.cs
Resolves [#2656](https://github.com/octokit/octokit.net/issues/2656)
----
WorkflowRunStatus enum does not contain "pending" value.
* 
WorkflowRunStatus enum contains "pending" value.
* 
* 
----
* N/A
----
> Add pending WorkflowRunStatus

- Octokit.Tests/Models/CollaboratorPermissionResponseTests.cs
- Octokit/Models/Response/CollaboratorPermissionResponse.cs
> Correctly deserialize CollaboratorPermissionResponse

- Octokit/Models/Response/WorkflowRunConclusion.cs
Resolves #2684
----
* The property to get a workflow run conclusion throws an exception when trying to get value of the workflow run with the conclusion of `startup_failure` or `skipped`.
* The property returns the workflow run conclusion correctly and doesn't throw an exception.
* I've mentioned in the original issue that GitHub documentation doesn't include these values as well, so it will be great if you  pass this information internally to the docs team 😄
----
- …
> Add missing workflow run conclusions

- Octokit/Models/Response/PackageVersion.cs
Resolves #2683
The class was already there. It was just not being used in `PackageVersionMetadata`.
From looking at the API it looks like only adding the the property to the model should work.
Example API response with a tag:
```json
"metadata": {
"package_type": "container",
"container": {
"tags": [
"develop"
]
}
}
```
Example API response without a tag:
```json
"metadata": {
"package_type": "container",
"container": {
"tags": []
}
}
```
Example API response for other package type:
```json
"metadata": {
"package_type": "npm"
}
```
----
* No `Container` property is present on `PackageVersionMetadata`
* A `Container` property is present on `PackageVersionMetadata`
* N/A
----
Please see our docs on [breaking changes](https://github.com/octokit/.github/blob/master/community/breaking_changes.m …
> Added missing 'container' property in metadata on a package version.

- Octokit.Tests/Clients/MigrationsClientTests.cs
- Octokit/Clients/MigrationsClient.cs
Resolves #2697
----
* MigrationsClient.DeleteArchive throws an ArgumentException - The value cannot be null or empty. (Parameter 'mediaType') when invoked in an application compiled using .Net 7.0
* MigrationsClient.DeleteArchive succeeds on .Net 7.0.  
* Requires modifying Octokit.Tests/Clients/MigrationsClientTests.cs (any object was required by the test, hence the **new object()** parameter being added to pass the test)
----
* N/A
- …
> Removing empty object paramater in MigrationsClient.DeleteArchive

- Octokit.Reactive/Clients/IObservableActionsSelfHostedRunnerGroupsClient.cs
- Octokit.Reactive/Clients/ObservableActionsSelfHostedRunnerGroupsClient.cs
- Octokit.Tests/Clients/ActionsSelfHostedRunnerGroupsClientTests.cs
- Octokit/Clients/ActionsSelfHostedRunnerGroupsClient.cs
- Octokit/Clients/IActionsSelfHostedRunnerGroupsClient.cs
- Octokit/Helpers/ApiUrls.cs
- Octokit/Models/Response/RunnerGroup.cs
Resolves #2705
----
* Octokit didn't have a method to get a single self-hosted runner group
* That API has been implemented
* I also added a missing property to the model
----
* N/A
API additions
----
> Add method to get a single runner group

- Octokit.Tests/Clients/ActionsSelfHostedRunnersClientTests.cs
- Octokit/Clients/ActionsSelfHostedRunnersClient.cs
- Octokit/Models/Response/Runner.cs
- Octokit/Models/Response/RunnerApplication.cs
- Octokit/Models/Response/RunnerLabel.cs
Resolves #2703
----
* Octokit throws a deserialization error when calling `ListAllRunnerApplicationsForOrganization` in the `ActionsSelfHostedRunnersClient`
* No error is thrown
I fixed the issue by removing the extra `IReadOnlyList` layer since `ApiConnection.GetAll` already returns an `IReadOnlyList`. I also made a few other updates to the`RunnerApplication` model:
* Added a missing property in the model
* Fixed a property that was always null because it had the wrong casing (didn't match the JSON payload).
* Created a new `RunnerLabel` model since the `Label` model is for issue/PR labels and didn't match the properties in the JSON payload
----
If `Yes`, …
> Fix runner application deserialization

- Octokit/Models/Response/Repository.cs
Resolves #2711.
----
* The debugger display string for `Repository` shows `Owner: Octokit.User`.
* The debugger display string for `Repository` shows `Owner: {repository owner login}`.
* N/A
----
* N/A
----
> Improve repo debugger display

- Octokit.Reactive/IObservableCodespacesClient.cs
- Octokit.Reactive/IObservableGitHubClient.cs
- Octokit.Reactive/ObservableCodespacesClient.cs
- Octokit.Reactive/ObservableGitHubClient.cs
- Octokit.Tests.Integration/Clients/CodespacesClientTests.cs
- Octokit.Tests.Integration/Helper.cs
- Octokit.Tests/Clients/CodespacesClientTests.cs
- Octokit/Clients/Codespace.cs
- Octokit/Clients/CodespaceState.cs
- Octokit/Clients/CodespacesClient.cs
- Octokit/Clients/CodespacesCollection.cs
- Octokit/Clients/ICodespacesClient.cs
- Octokit/Clients/Machine.cs
- Octokit/GitHubClient.cs
- Octokit/Helpers/ApiUrls.cs
- Octokit/Http/SimpleJsonSerializer.cs
- Octokit/IGitHubClient.cs
- script/configure-integration-tests.ps1
Resolves #2721 
----
* no codespaces api :)
* adds basic Codespaces API:
* GetAll()
* Get(name)
* GetForRepository(owner, repo)
* Start(name)
* Stop(name)
----
* N/A
----
> Add basic codespaces api

- Octokit/Models/Response/WorkflowJob.cs
Resolves #2724 by making the following fields nullable: `RunnerId, RunnerName, RunnerGroupId, RunnerGroupName` which may be null when the WorkflowJob is coming from a `WorkflowJobEvent` webhook.
----
* Deserializing a WorkflowJob that was received from a `WorkflowJobEvent` webhook would fail if any of the non-nullable fields we're null.
* Deserializing a WorkflowJob that was received from a `WorkflowJobEvent` webhook succeeds even if it has null values for the 4 fields mentioned above.
* See the [webhooks.net/WorkflowJob model](https://github.com/octokit/webhooks.net/blob/main/src/Octokit.Webhooks/Models/WorkflowJobEvent/WorkflowJob.cs) for reference of the model that this _should_ map to.
----
Please see our docs on [breaking changes](https://github.com/octokit/.github/blob/master/communi …
> [BUG] Fix Deserializing WorkflowJob

- Octokit.Reactive/Clients/IObservableTeamsClient.cs
- Octokit.Reactive/Clients/ObservableTeamsClient.cs
- Octokit.Tests.Integration/Clients/TeamsClientTests.cs
- Octokit.Tests/Clients/TeamsClientTests.cs
- Octokit/Clients/ITeamsClient.cs
- Octokit/Clients/TeamsClient.cs
Resolves #2716 
----
Introduces a new method that allows using the API endpoint to [get a team by slug name](
https://docs.github.com/en/rest/teams/teams?apiVersion=2022-11-28#get-a-team-by-name). In certain integration scenarios, other systems might know a team name that's common between systems, but not know the GitHub ID. This allows retrieving a team instance from the API without needing to work out the ID first. 
NA - new feature
New method on Teams Client that supports getting a team by slug name
It's the callers responsibility to provide the appropriately formed team slug name to the method, this PR provides no functionality to achieve that. 
Whilst there are rules for forming the slug (all lower case, spaces replaced by hyphens, special chars removed etc) this is non-deterministic …
> Get Team By Name implementation

- Octokit.Tests/Models/WorkflowJobTests.cs
- Octokit/Models/Response/WorkflowJob.cs
Resolves #2728 by adding a `CreatedAt` field to the `WorkflowJob` model
----
* `WorkflowJob` model would not include data for the `CreatedAt` field
* `WorkflowJob` model does include data for the `CreatedAt` field
* 
----
* N/A
----
> Add CreatedAt to WorkflowJob model

- Octokit/Models/Response/WorkflowJob.cs
Resolves #2733 by making the newly added `CreatedAt` field on the `WorkflowJob` model nullable.
----
* Deserializing calls that return a `WorkflowJob` would fail if running against GHES < 3.9 since the `CreatedAt` field is not provided on older GHES versions.
* Deserializing calls that return a `WorkflowJob` succeed running against GHES < 3.9 since the `CreatedAt` field is nullable and not provided by older GHES versions.
* This is a quick follow-up fix to #2728 -- would be great to get this fix in 🙏 @kfcampbell 
----
* N/A
- Feature/model/API …
> Make `CreatedAt` nullable

- Octokit/Models/Response/WorkflowJobStatus.cs
Resolves #2730 
----
* 
* 
* 
----
* N/A
----
> Add Waiting to WorkflowJobStatus

- Octokit.Tests/Models/DeploymentStatusTests.cs
- Octokit/Models/Response/DeploymentStatus.cs
Resolves #2735 
----
Newly created `DeploymentStatus`es on github.com recently exceeded the limits of a 32-bit signed integer, causing `OverflowException`s to be throw during de-serialization.
The de-serialization no longer throws due to the `DeploymentStatus.Id` field being upgraded to a 64-bit signed integer.
Was this the reason for the GitHub API outages in the past 48 hours? lmao.
~~- [ ] Added the appropriate label for the given change~~ (Not a maintainer)
~~- [ ] No~~
`DeploymentStatus.Id` can no longer be safely assigned to an `Int32`, it's previous type.
- …
> Fix DeploymentStatus IDs Overflowing

- Octokit.Reactive/Clients/IObservableActionsSelfHostedRunnersClient.cs
- Octokit.Reactive/Clients/ObservableActionsSelfHostedRunnersClient.cs
- Octokit.Tests/Clients/ActionsSelfHostedRunnersClientTests.cs
- Octokit/Clients/ActionsSelfHostedRunnersClient.cs
- Octokit/Clients/IActionsSelfHostedRunnersClient.cs
* Resolves #2739 by resolving an exception being thrown by all of the `Delete___Runner` calls
* Passes `CancellationToken cancellationToken = default` to `Create___Token` calls to allow for an optional cancellation token.
----
* Calls to all of the `Delete___Runner` methods would throw an exception caused by passing the wrong kind of `Object` to the underlying `Delete` call. We we're previously passing `ApiOptions` which are the wrong type and not relevant.
* Calls to all of the `Delete___Runner` methods succeed.
* Calls to the `Create__Token` methods allow for passing a `CancellationToken` and still succeed.
* 
----
* N/A
Please …
> Fix ActionsSelfHostedRunnersClient Delete Calls

- Octokit.Reactive/Clients/IObservableOauthClient.cs
- Octokit.Reactive/Clients/ObservableOauthClient.cs
- Octokit.Tests/Clients/OauthClientTests.cs
- Octokit/Clients/IOAuthClient.cs
- Octokit/Clients/OAuthClient.cs
- Octokit/Models/Request/OauthTokenRenewalRequest.cs
- Octokit/Models/Response/OauthToken.cs
Resolves #2731
----
* OAuth Client doesn't support getting the refresh token, nor utilizing it to get a new access token.
* Additionally, it doesn't return information about when the access token expires.
* CreateAccessToken now returns all fields from the returned body, including token expiration, refresh token and refresh token expiration time.
* CreateAccessTokenFromRefreshToken accepts a clientId, clientSecret and refresh token, in order to create a new access token on behalf of the user, the refresh token was created for.
While the endpoint is the same for creating an access token from a response code and for creating an access token based on the refresh token, there are key differences in the expected parameters. When creating based on a refresh token, the grant_type needs to be …
> Support refreshtokens in OAuth flow

- Octokit.Tests.Integration/Clients/ReleasesClientTests.cs
- Octokit/Models/Request/MakeLatestQualifier.cs
- Octokit/Models/Request/NewRelease.cs
- Octokit/Models/Request/ReleaseUpdate.cs
Resolves #2756
----
It is not possible to set make_latest parameter when creating and updating a release
It is possible to set make_latest parameter when creating and updating a release
- [ X ] Tests for the changes have been added (for bug fixes / features)
- [ X ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [ X ] No
----
> [feat]: Support make_latest in create and update release

- Octokit.Tests.Integration/Clients/RepositoryBranchesClientTests.cs
- Octokit/Models/Request/BranchProtectionUpdate.cs
- Octokit/Models/Response/BranchProtection.cs
- Octokit/Octokit.csproj
Resolves #2714
----
* Octokit.net doesn't currently support making branches **read-only**
* I've added **LockBranch** properties to the various branch protection models, next to the existing **EnforceAdmins** properties.
* I've also published a temporary nuget with this functionality to: https://www.nuget.org/packages/Neon.Octokit/6.0.2
* The existing unit tests pass
* I didn't see any related integration unit tests in your repo, but I have verified this in unit tests for our repo using this.
----
I didn't see any related integration unit tests in your repo, but I have verified this in unit tests for our repo using this.
Please add …
> Added support for making branches read-only

- Octokit.Reactive/Clients/ObservableGitHubAppInstallationsClient.cs
- Octokit.Reactive/Clients/ObservableGitHubAppsClient.cs
- Octokit.Reactive/ObservableCodespacesClient.cs
- Octokit.Tests.Integration/Clients/CheckRunsClientTests.cs
- Octokit.Tests.Integration/Clients/CheckSuitesClientTests.cs
- Octokit.Tests.Integration/Clients/GitHubAppInstallationsClientTests.cs
- Octokit.Tests.Integration/Clients/GitHubAppsClientTests.cs
- Octokit.Tests.Integration/Clients/MigrationsClientTests.cs
- Octokit.Tests.Integration/Clients/OrganizationMembersClientTests.cs
- Octokit.Tests.Integration/Clients/ProjectCardsClientTests.cs
- Octokit.Tests.Integration/Clients/ProjectColumnsClientTests.cs
- Octokit.Tests.Integration/Clients/ProjectsClientTests.cs
- Octokit.Tests.Integration/Helpers/EnterpriseUserContext.cs
- Octokit.Tests.Integration/Helpers/GpgKeyContext.cs
- Octokit.Tests.Integration/Helpers/MaintenanceModeContext.cs
- Octokit.Tests.Integration/Helpers/PublicKeyContext.cs
- Octokit.Tests.Integration/Helpers/RepositoryContext.cs
- Octokit.Tests.Integration/Helpers/TeamContext.cs
- Octokit.Tests.Integration/Reactive/ObservableCheckRunsClientTests.cs
- Octokit.Tests.Integration/Reactive/ObservableCheckSuitesClientTests.cs
- Octokit.Tests.Integration/Reactive/ObservableGitHubAppInstallationsClientTests.cs
- Octokit.Tests.Integration/Reactive/ObservableGitHubAppsClientTests.cs
- Octokit.Tests.Integration/Reactive/ObservableProjectCardsClientTests.cs
- Octokit.Tests.Integration/Reactive/ObservableProjectColumnsClientTests.cs
- Octokit.Tests.Integration/Reactive/ObservableProjectsClientTests.cs
- Octokit.Tests.Integration/Reactive/ObservableRepositoryBranchesClientTests.cs
- Octokit.Tests.Integration/Reactive/ObservableRepositoryDeployKeysClientTests.cs
- Octokit/Http/SimpleJsonSerializer.cs
- Octokit/Models/Request/ApiOptions.cs
Resolves #2758
----
No behavior change. The change is purely in the semantics of the code
No behavior change. The change is purely in the semantics of the code
No. All changes are local in the classes they were introduced
> Added `readonly` to fields that are never modified

- Octokit.Tests/Clients/SearchClientTests.cs
- Octokit.Tests/Models/SearchIssuesRequestTests.cs
- Octokit/Models/Request/SearchIssuesRequest.cs
Resolves #2762
----
```cs
request.Labels = new[] { "bug,resolved,help wanted" } // label:"bug,resolved,help wanted"
```
```cs
request.Labels = new[] { "bug,resolved,help wanted" } // label:bug,resolved,"help wanted"
```
----
> fix(SearchIssuesRequest): wrap label in quotes if it contains spaces

- Octokit.Tests.Integration/Clients/GitHubAppsClientTests.cs
- Octokit.Tests/Models/InstallationTests.cs
- Octokit/Models/Response/Installation.cs
- Octokit/Octokit.csproj
Resolves #2777 by adding `suspended_at` and `suspended_by` properties to the `Installation` model. This will allow consumers of the [List GitHub Installations](https://docs.github.com/en/rest/apps/apps?apiVersion=2022-11-28#list-installations-for-the-authenticated-app) API to filter out suspended installations.
----
* Calls to list GitHub App installations would not include the `suspended_at` and `suspended_by` properties.
* Calls to list GitHub App installations will include both the `suspended_at` and `suspended_by` properties.
----
> Add `suspended_at` and `suspended_by` to the `Installation` model

- Octokit.Tests/Helpers/UriExtensionsTests.cs
- Octokit/Helpers/UriExtensions.cs
Resolves #1955, #2602
----
* Following code never returns a list of release and hits API rate limit:
```
var client = new GitHubClient(new ProductHeaderValue("Test"));
var releases = await client.Repository.Release.GetAll("octokit", "octokit.net",
new ApiOptions { StartPage = 1, PageSize = 10, PageCount = 2 });
```
* Looks like any method prefixed with `GetAll*` is affected when called with `ApiOptions.StartPage != null` specified and one of the following is true:
- `ApiOptions.PageCount > 1`
- `ApiOptions.PageCount == null`
* Example code returns 20 releases as expected
----
> [Bug]Fix pagination when ApiOptions.StartPage is explicitly set.

- Octokit/Models/Request/RepositoryUpdate.cs
- Octokit/Models/Response/Repository.cs
Resolves #2772
----
* The WebCommitSignoffRequired and HasDiscussions fields exposed by the REST API are not implemented by octokit.net
* The WebCommitSignoffRequired and HasDiscussions fields will be implemented by octokit.net for the get and update repository objects
----
> [feat] Expose WebCommitSignoffRequired and HasDiscussions for get and update repository objects

- Octokit.Reactive/Clients/IObservableActionsArtifactsClient.cs
- Octokit.Reactive/Clients/ObservableActionsArtifactsClient.cs
- Octokit.Tests/Http/HttpClientAdapterTests.cs
- Octokit.Tests/Models/ArtifactsTests.cs
- Octokit/Caching/CachedResponse.cs
- Octokit/Clients/ActionsArtifactsClient.cs
- Octokit/Clients/IActionsArtifactsClient.cs
- Octokit/Helpers/ApiUrls.cs
- Octokit/Helpers/Ensure.cs
- Octokit/Http/ApiConnection.cs
- Octokit/Http/Connection.cs
- Octokit/Http/HttpClientAdapter.cs
- Octokit/Http/IApiConnection.cs
- Octokit/Http/IConnection.cs
- Octokit/Http/IResponse.cs
- Octokit/Http/Response.cs
- Octokit/Models/Request/ListArtifactsRequest.cs
- Octokit/Models/Response/Artifact.cs
- Octokit/Models/Response/ArtifactWorkflowRun.cs
- Octokit/Models/Response/ListArtifactsResponse.cs
Resolves #2780
----
* The artifacts client isn't usable currently - There are no methods
Methods to interact with the APIs listed here: https://docs.github.com/en/rest/actions/artifacts
----
I couldn't add integration tests as there isn't any API to create artifacts or anything. But I've added a deserialization test. And then I've hooked into the existing HTTP functionality which should already be thoroughly tested.
I also slightly reworked the internal HTTP sending to receive binary file responses as Streams, rather than raw byte arrays. Artifacts could potentially be large file sizes, and loading these directly into a byte array may not be ideal for memory. So …
> [feat]: SDKs for ActionsArtifacts APIs

- Octokit.Reactive/Clients/ObservableStarredClient.cs
- Octokit.Tests.Integration/Clients/StarredClientTests.cs
- Octokit.Tests/Clients/StarredClientTests.cs
- Octokit.Tests/Reactive/ObservableStarredClientTests.cs
- Octokit/Clients/StarredClient.cs
- Octokit/Helpers/AcceptHeaders.cs
Resolves #2784
----
Method returned null data and threw when trying to access user data
* 
User data is populated
* 
----
> [bug]: GetAllStargazersWithTimestamps was not returning timestamps

- build/Lifetime.cs
Update to the latest stable version of [GitVersion.Tool](https://www.nuget.org/packages/GitVersion.Tool/5.12.0#supportedframeworks-body-tab) that supports .NET 6.
Resolves #2790
----
* `build.ps1` fails with `Error: GitVersion: Process returned an error (exit code -2147450730).`
* `build.ps1` successfully compiles and tests Octokit.
----
> [fix] Bump GitVersion.Tool

- Octokit.Tests.Integration/Clients/RepositoriesClientTests.cs
- Octokit/Models/Response/Repository.cs
Resolves #2800
----
There wa sno way to access the archive url field and even if you could just use string concatenation, there's no need for this to not be an option.
Now you can access it through the `Repository.ArchiveUrl` field.
> [feat]: Add archive url to repository info

- Octokit.Reactive/Clients/IObservableRepositoryActionsClient.cs
- Octokit.Reactive/Clients/IObservableRepositoryVariablesClient.cs
- Octokit.Reactive/Clients/ObservableRepositoryActionsClient.cs
- Octokit.Reactive/Clients/ObservableRepositoryVariablesClient.cs
- Octokit.Tests/Clients/RepositoryVariablesClientTests.cs
- Octokit/Clients/IRepositoryActionsClient.cs
- Octokit/Clients/IRepositoryVariablesClient.cs
- Octokit/Clients/RepositoryActionsClient.cs
- Octokit/Clients/RepositoryVariablesClient.cs
- Octokit/Helpers/ApiUrls.cs
- Octokit/Models/Request/Variable.cs
- Octokit/Models/Response/RepositoryVariable.cs
- Octokit/Models/Response/RepositoryVariablesCollection.cs
Resolves #2753
----
No access was provided for repository variables.
Adds the ability to:
- Retrieve repository variables and organization variables assigned to a repository
- Create new repository variables
- Update existing repository variables
- Delete existing repository variables
----
> [feat]: Adding repository variables

- Octokit.Tests/Clients/EventsClientTests.cs
- Octokit/Models/Response/ActivityPayloads/PushEventPayload.cs
Resolves #2720
----
The `PushEventPayload` class was missing the `before`, `distinct_size`, and `push_id` properties documented at https://docs.github.com/en/webhooks-and-events/events/github-event-types#pushevent
Those three properties are added to the `PushEventPayload` class as `DistinctSize`, `PushId`, and `Before`.
----
> [feat]: Adding missing properties to PushEventPayload

- Octokit.Reactive/Clients/IObservableRepositoryBranchesClient.cs
- Octokit.Reactive/Clients/ObservableRepositoryBranchesClient.cs
- Octokit.Tests/Clients/RepositoryBranchesClientTests.cs
- Octokit/Clients/IRepositoryBranchesClient.cs
- Octokit/Clients/RepositoryBranchesClient.cs
- Octokit/Helpers/ApiUrls.cs
- build/Utilities/BuildVersion.cs
Resolves #ISSUE_NUMBER
----
* The RenameBranch method was not available on the RepositoryBranchClient object
* The Rename Branch method has been added to the RepositoryBranchClient object
----
> [feat]: Add RenameBranch method to RepositoryBranchesClient

- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
- .github/workflows/netcore.yml
- .github/workflows/publish.yml
The [.NET 5.0 SDK has been EoL since May 2022 ](https://devblogs.microsoft.com/dotnet/dotnet-5-end-of-support-update/) and should no longer be needed (unless mono requires it), so our tooling here needs to reflect that.
- .net 5.0 SDK is installed when the container gets instantiated using the dev container file
- Supported versions: net5.0, net5.0-windows, net6.0, net6.0-android, net6.0-ios, net6.0-maccatalys, net6.0-macos , net6.0-tvos, net6.0-windows , net7.0 , net7.0-android , net7.0-ios net7.0-ios , net7.0-maccatalyst , net7.0-macos , net7.0-tvos net7.0-tvos , net7.0-windows
- .net 6.0 SDK is the only version installed when the container gets instantiated using the dev container file
- Supported versions: net6.0, net6.0-android, net6.0-ios, net6.0-maccatalys, net6.0-macos , …
> [BREAKING CHANGE]: Removes the .NET 5.0  support

- Octokit.Tests/Http/ConnectionTests.cs
- Octokit/Http/Connection.cs
Fix `NullReferenceException` if raw content was handled as a string rather than a stream by `HttpClientAdapter.BuildResponse()`.
I haven't added a test for this, but have validated that the apps that surfaced this issue are working when using a local build of Octokit including this change. If you can direct me to exactly where you'd like a test for this, I'll add one.
Resolves #2789
----
* A `NullReferenceException` would be thrown.
* The call succeeds.
----
> [fix] Fix handling for Streams in IConnection for raw content

- Octokit.Tests.Integration/Clients/RateLimitClientTests.cs
- Octokit.Tests/Clients/MiscellaneousClientTests.cs
- Octokit.Tests/Clients/RateLimitClientTests.cs
- Octokit/Models/Response/ResourceRateLimit.cs
Resolves #N/A
----
* The rate limit client did not output limits for graph ql
* The rate limit client outputs rate limits for graph ql
----
> [feat]: Output GraphQL rate limit

- Octokit/Models/Request/NewRelease.cs
- docs/releases.md
In this PR, we introduce the support of `discussion_category_name` for new releases:
> `discussion_category_name` `string`
> If specified, a discussion of the specified category is created and linked to the release. The value must be a category that already exists in the repository. For more information, see "[Managing categories for discussions in your repository](https://docs.github.com/discussions/managing-discussions-for-your-community/managing-categories-for-discussions-in-your-repository)."
This parameter was introduced in GitHub REST API 2022-11-28, see https://docs.github.com/en/rest/releases/releases?apiVersion=2022-11-28#create-a-release
Resolves #2746
> [feat] Introduce NewRelease.DiscussionCategoryName, Fixes #2746

- Octokit.Reactive/Clients/IObservableActionsClient.cs
- Octokit.Reactive/Clients/IObservableActionsOidcClient.cs
- Octokit.Reactive/Clients/ObservableActionsClient.cs
- Octokit.Reactive/Clients/ObservableActionsOidcClient.cs
- Octokit.Tests/Clients/ActionsOidcClientTests.cs
- Octokit/Clients/ActionsClient.cs
- Octokit/Clients/ActionsOidcClient.cs
- Octokit/Clients/IActionsClient.cs
- Octokit/Clients/IActionsOidcClient.cs
- Octokit/Helpers/ApiUrls.cs
- Octokit/Models/Common/PackageVersionState.cs
- Octokit/Models/Request/OrganizationOidcSubjectClaimRequest.cs
- Octokit/Models/Request/RepositoryOidcSubjectClaimRequest.cs
- Octokit/Models/Response/OrganizationOidcSubjectClaim.cs
- Octokit/Models/Response/RepositoryOidcSubjectClaim.cs
* Functionality wasn't implemented
* Can get or set OIDC subject claims for an organization or repository
----
> [feat]: Implement Actions OIDC Client

- Octokit.Tests.Integration/Clients/StarredClientTests.cs
- Octokit.Tests/Clients/StarredClientTests.cs
- Octokit/Clients/StarredClient.cs
Resolves #2827
----
`StarredClient.GetAllForCurrentWithTimestamps` and `StarredClient.GetAllForUserWithTimestamps` expect to be returned with the `StarredAt` and `Repo` properties set, but default values are returned.
The `StarredAt` and `Repo` property values are returned with the received values set.
----
> [Fix]: The methods `GetAllForCurrentWithTimestamps` and `GetAllForUserWithTimestamps` did not return timestamps.

- Octokit.Tests.Integration/Clients/RepositoryBranchesClientTests.cs
- Octokit.Tests.Integration/Helpers/OrganizationRepositoryWithTeamContext.cs
- Octokit/Models/Request/BranchProtectionUpdate.cs
- Octokit/Models/Response/BranchProtection.cs
Resolves #2837
----
It was not possible to set the Branch Protection option "Require approval of the most recent reviewable push".
We can now set, update and retrieve the Branch Protection option "Require approval of the most recent reviewable push".
No breaking change as made with defaulting to false, so keeping the current behaviour.
----
> [FEAT] Add support for "Require approval of the most recent reviewable push"

- Octokit.Tests/Models/IssueTest.cs
- Octokit/Models/Response/ReactionSummary.cs
Resolves #2838 
----
It wasn't possible to get the count of eyes or rocket reactions from `ReactionSummary`
* 
`ReactionSummary` now has `Eyes` & `Rocket` properties
*
> [feat] Add Rocket & Eyes reactions to `ReactionSummary`

- Octokit/Models/Response/ActivityPayloads/PushEventPayload.cs
Bug introduced in #2795 Closes #2822
Resolves #2822
----
* Exception on any user activity with a recent PR where it exceeded Int32.maxvalue
* does not exception out
----
long is used elsewhere for ids, the PR just used the wrong datatype.
> Fixes PushId datatype to not overflow (fix user activity exception)

- README.md
Resolves #2851
----
* Outdated **Related Projects** were listed in the `Octokit.net` `README.md` file. 
* The 'Related Projects' section has been removed from the README, making it up-to-date.
* Fixes #2851
----
> [DOCS]: Removed the Related Projects Section from the `README`

- Octokit.Reactive/Clients/IObservableActionsOidcClient.cs
- Octokit.Reactive/Clients/IObservableAutolinksClient.cs
- Octokit.Reactive/Clients/IObservableRepositoriesClient.cs
- Octokit.Reactive/Clients/ObservableAutolinksClient.cs
- Octokit.Reactive/Clients/ObservableRepositoriesClient.cs
- Octokit.Tests/Clients/AutolinksClientTests.cs
- Octokit/Clients/AutolinksClient.cs
- Octokit/Clients/IAutolinksClient.cs
- Octokit/Clients/IRepositoriesClient.cs
- Octokit/Clients/RepositoriesClient.cs
- Octokit/Helpers/ApiUrls.cs
- Octokit/Models/Request/AutolinkRequest.cs
- Octokit/Models/Response/Autolink.cs
Resolves #ISSUE_NUMBER
N/A
----
* The repository Autolinks client isn't implemented
* The repository Autolinks client is implemented
----
> [Feat] Add Repository Autolinks Client

- build.ps1
- build/Context.cs
- build/Lifetime.cs
Resolves #ISSUE_NUMBER
----
* The build.ps1 script would require setup on the machine in order to parse a version number when building the nupkg file.
* A custom version can be forced in by specifying the -ForceVersion parameter
----
> [Feat] Allow build version to be passed in to build.ps1 via command line

- Octokit.Tests.Integration/Helpers/OrganizationRepositoryWithTeamContext.cs
- Octokit.Tests.Integration/Reactive/ObservableRepositoryBranchesClientTests.cs
- Octokit/Models/Request/BranchProtectionUpdate.cs
Resolves  #2855
----
* No `RequiredSignatures` property present for `BranchProtectionSettingsUpdate` type which is supported by GitHub's rest APIs.
* Added `RequiredSignatures` property for the `BranchProtectionSettingsUpdate` type
* Updated all xUnnit tests for the `BranchProtectionSettingsUpdate` type to account for the new property (i.e `RequiredSignatures`)
----
> Fix: Add `RequiredSignatures` to the `BranchProtectionSettingsUpdate` Type

- Octokit.Reactive/Clients/IObservableOrganizationMembersClient.cs
- Octokit.Reactive/Clients/ObservableOrganizationMembersClient.cs
- Octokit.Tests/Clients/OrganizationMembersClientTests.cs
- Octokit.Tests/Reactive/ObservableOrganizationMembersClientTests.cs
- Octokit/Clients/IOrganizationMembersClient.cs
- Octokit/Clients/OrganizationMembersClient.cs
- Octokit/Helpers/ApiUrls.cs
Resolves #2880
----
* You can not cancel invitations.
* You can cancel invitations.
----
> feat: Adds cancel invitation

- .devcontainer/Dockerfile
Currently prebuilds are failing and we might need to move from python3-pip to python3-full which will add build time and a few other variables into our pipeline.  Looking to put in a simple workaround for now (so that codespaces spin up does not cause a huge time delay as well as to fix create code spaces functionally from GitHub.com
> Update Dockerfile to omit mkdocs so that pre-builds will complete successfully

- Octokit.Reactive/Clients/IObservableOrganizationMembersClient.cs
- Octokit.Reactive/Clients/ObservableOrganizationMembersClient.cs
- Octokit.Tests.Integration/Clients/OrganizationMembersClientTests.cs
- Octokit.Tests.Integration/Reactive/ObservableOrganizationMembersClientTests.cs
- Octokit.Tests/Clients/OrganizationMembersClientTests.cs
- Octokit.Tests/Helpers/RandomEmailGenerator.cs
- Octokit.Tests/Models/OrganizationInvitationRequestTests.cs
- Octokit.Tests/Reactive/ObservableOrganizationMembersClientTests.cs
- Octokit/Clients/IOrganizationMembersClient.cs
- Octokit/Clients/OrganizationMembersClient.cs
- Octokit/Helpers/ApiUrls.cs
- Octokit/Models/Request/OrganizationInvitationRequest.cs
- Octokit/Models/Response/OrganizationMembershipInvitation.cs
Resolves [#2894](https://github.com/octokit/octokit.net/issues/2894)
----
* Organization invitations required a GitHub account username
* Organization invitations can be created using an email address or a GitHub user ID
----
> feat: Add create organization invitation via email

- Octokit.Tests/Caching/CachingHttpClientTests.cs
- Octokit/Caching/CachingHttpClient.cs
- Octokit/Helpers/HttpExtensions.cs
Resolves https://github.com/octokit/octokit.net/issues/2876
Apologies if I've filed a bug when it should come under feature/enhancement!
I couldn't find any docs on response caching, but happy to update them if there are any.
----
* If the `CachingHttpClient` received a non-200 and non-304 response from GitHub, it still attempts to update the underlying response cache, resulting in a higher number of subsequent cache misses if `IResponseCache` implementations don't guard for it themselves.
* Only attempts to update the response cache if a 2xx response code is received from GitHub.
* I don't believe this is classed as a breaking change, but it is a change in behaviour that could impact users who rely on it calling the response cache for non-200 responses.
> BREAKING CHANGE (behavior): Modify caching to only attempt to update the response cache if a 2xx response code is received from GitHub

- Octokit/Http/HttpClientAdapter.cs
> fix: Allow `zip` MIME type

- Octokit.Tests/Http/HttpClientAdapterTests.cs
- Octokit/Http/HttpClientAdapter.cs
Fixes #2898 
Sorry, the last one didn't actually solve it because the Content-Type wasn't being set properly by the `System.Net` classes - Probably due to an invalid format.
> fix: "zip" Content-Type resulting in null Stream for Artifacts on Blob Storage

- Octokit.Tests/Http/PaginationTests.cs
- Octokit/Helpers/Pagination.cs
Resolves #2693
* PageCount did not work if the query gets constructed with page number as the first query parameter
* PageCount now works if the query gets constructed with page number as the first query parameter
> Fix #2693 PageCount doesn't work if the query gets constructed with page number as the first query parameter 

- Octokit.Tests/Clients/SearchClientTests.cs
- Octokit.Tests/Models/SearchRepositoryRequestTests.cs
- Octokit/Models/Request/SearchRepositoriesRequest.cs
Resolves #2935
----
* Repository search does not support qualifiers to [search based on repository custom property](https://docs.github.com/en/search-github/searching-on-github/searching-for-repositories#search-based-on-repository-custom-property).
* Adds support for qualifiers to [search based on repository custom properties](https://docs.github.com/en/search-github/searching-on-github/searching-for-repositories#search-based-on-repository-custom-property).
* Updates links for docs in the class/property summaries
----
> [FEAT]: Search based on repository custom property

- Octokit.Reactive/Clients/IObservablePackagesClient.cs
- Octokit.Reactive/Clients/ObservablePackagesClient.cs
- Octokit.Tests/Clients/PackagesClientTests.cs
- Octokit/Clients/IPackagesClient.cs
- Octokit/Clients/PackagesClient.cs
Resolves #2923
----
`PackagesClient.GetAll*` were not able to paginate and the results capped at 30 results
Overload parameter `APIOptions` for `PackagesClient.GetAll*`  
Methods. Extended the Tests for `PackagesClient.GetAll*` to behave the same as `RepositoriesClient.GetAll*`.
----
>  feat: added Missing APIOption overload for PackagesClient.GetAll* #2923

- Octokit/Models/Common/Status.cs
- Octokit/Models/Request/RepositoryUpdate.cs
- Octokit/Models/Request/SecurityAndAnalysisRequest.cs
- Octokit/Models/Response/Repository.cs
- Octokit/Models/Response/SecurityAndAnalysis.cs
Resolves #ISSUE_NUMBER
N/A
----
* Repository get/update did not implement Advanced Security properties
* Repository get/update implements Advanced Security properties
----
> [Feat] Add Advanced Security Properties to Repository Get/Update

- Octokit.Reactive/Clients/IObservableGitHubAppsClient.cs
- Octokit.Reactive/Clients/ObservableGitHubAppsClient.cs
- Octokit.Tests/Clients/GitHubAppsClientTests.cs
- Octokit.Tests/Models/GitHubAppFromManifestTests.cs
- Octokit.Tests/Reactive/ObservableGitHubAppsClientTests.cs
- Octokit/Clients/GitHubAppsClient.cs
- Octokit/Clients/IGitHubAppsClient.cs
- Octokit/Helpers/ApiUrls.cs
- Octokit/Models/Response/GitHubApp.cs
- Octokit/Models/Response/GitHubAppFromManifest.cs
- Octokit/Models/Response/InstallationPermissions.cs
- Resolves #2938
----
* Does not support [Creating a GitHub App from a manifest](https://docs.github.com/en/rest/apps/apps?apiVersion=2022-11-28#create-a-github-app-from-a-manifest). This is the final step when using the [GitHub App Manifest flow](https://docs.github.com/en/apps/sharing-github-apps/registering-a-github-app-from-a-manifest)
* Adds support for [Creating a GitHub App from a manifest](https://docs.github.com/en/rest/apps/apps?apiVersion=2022-11-28#create-a-github-app-from-a-manifest).
* Adds missing InstallationPermissions:
* [`repository_custom_properties`](https://docs.github.com/rest/authentication/permissions-required-for-github-apps#repository-permissions-for-custom-properties)
* [`organization_copilot_seat_management`](https://docs.github.com/rest/authentication/permissi …
> [FEAT]: Create a GitHub App from a manifest

- docs/github-apps.md
This adds a simple code snippet for creating the JWT token required to authenticate GitHub Apps. All dependencies live in the `System` namespace.
- `System.IdentityModel.Tokens.Jwt`
- `System.Security.Claims`
- `System.Security.Cryptography`
----
Developers would think that the only alternative was to import another dependency.
Developers are able to create JWT tokens for their GitHub Apps using dependencies they likely already have imported.
- ~Tests for the changes have been added (for bug fixes / features)~
----
> docs: Provide easy alternative to create App JWT token

- Octokit.Reactive/IObservableCodespacesClient.cs
- Octokit.Reactive/ObservableCodespacesClient.cs
- Octokit.Tests.Integration/Clients/CodespacesClientTests.cs
- Octokit.Tests/Clients/CodespacesClientTests.cs
- Octokit/Clients/Codespace.cs
- Octokit/Clients/CodespacesClient.cs
- Octokit/Clients/ICodespacesClient.cs
- Octokit/Clients/MachinesCollection.cs
- Octokit/Helpers/ApiUrls.cs
- Octokit/Models/Common/CodespaceLocation.cs
- Octokit/Models/Request/NewCodespace.cs
Resolves #2915
----
* Adding two new functions to the Codespaces API:
```
MachinesCollection GetAvailableMachinesForRepo(string repoOwner, string repoName, string reference = null);
Codespace Create(string owner, string repo, NewCodespace newCodespace);
```
* Plus two new types: `MachinesCollection` and `NewCodespace`
* Plus one new StringEnum:
```
public enum CodespaceLocation
{
[Parameter(Value = "EuropeWest")]
EuropeWest,
[Parameter(Value = "SoutheastAsia")]
SoutheastAsia,
[Parameter(Value = "UsEast")]
UsEast,
[Parameter(Value = "UsWest")]
UsWest
}
```
* When retrieving a codespace the location is now also included.
* This new API additions allow the creation of new codespacesm
* retrieving the location of a Codespace,
* aswell as getting available machine types for a repository
Please …
> Adding support for creating Codespaces and getting available machine types

- Octokit.Reactive/Clients/IObservableActionsWorkflowsClient.cs
- Octokit.Reactive/Clients/ObservableActionsWorkflowsClient.cs
- Octokit.Tests.Integration/Clients/ActionsWorkflowsClientTests.cs
- Octokit.Tests/Clients/ActionsWorkflowsClientTests.cs
- Octokit.Tests/Reactive/ObservableActionsWorkflowsClientTests.cs
- Octokit/Clients/ActionsWorkflowsClient.cs
- Octokit/Clients/IActionsWorkflowsClient.cs
- Octokit/Helpers/ApiUrls.cs
* Non-existent.
* Adding unimplemented API.
----
> Add support for Workflows `CreateDispatch` via repository ID

- Octokit.AsyncPaginationExtension/Extensions.cs
- Octokit.Reactive/Clients/IObservableActionsSelfHostedRunnerGroupsClient.cs
- Octokit.Reactive/Clients/ObservableActionsSelfHostedRunnerGroupsClient.cs
- Octokit.Tests/Clients/ActionsSelfHostedRunnerGroupsClientTests.cs
- Octokit/Clients/ActionsSelfHostedRunnerGroupsClient.cs
- Octokit/Clients/IActionsSelfHostedRunnerGroupsClient.cs
- Octokit/Models/Response/OrganizationsResponse.cs
- Octokit/Models/Response/RepositoriesResponse.cs
Resolves #2964
----
* Runner group access APIs would return empty objects because they weren't wrapped in a response object
* Runner group access APIs return properly deserialized responses
I didn't see existing tests for deserialization, but I'm happy to add tests if there is an established pattern to follow.
The return type of several functions changed (although these functions would have returned empty objects before)
----
> Fix runner group access return type

- .gitignore
- .vscode/settings.json
- Octokit.Reactive/Clients/IObservableMetaClient.cs
- Octokit.Reactive/Clients/IObservablePublicKeysClient.cs
- Octokit.Reactive/Clients/ObservableMetaClient.cs
- Octokit.Reactive/Clients/ObservablePublicKeysClient.cs
- Octokit.Tests.Integration/Clients/PublicKeysClientTest.cs
- Octokit.Tests/Clients/PublicKeysClientTests.cs
- Octokit.Tests/Models/MetaPublicKeysTests.cs
- Octokit.Tests/Reactive/ObservablePublicKeysClientTests.cs
- Octokit/Clients/IMetaClient.cs
- Octokit/Clients/IPublicKeysClient.cs
- Octokit/Clients/MetaClient.cs
- Octokit/Clients/PublicKeysClient.cs
- Octokit/Helpers/ApiUrls.cs
- Octokit/Models/Common/PublicKeyType.cs
- Octokit/Models/Response/MetaPublicKey.cs
- Octokit/Models/Response/MetaPublicKeys.cs
Resolves #2944
----
* No support for `/meta/public_keys/<keyType>`.
[Secret Scanning](https://docs.github.com/en/code-security/secret-scanning/secret-scanning-partner-program#implement-signature-verification-in-your-secret-alert-service) and [Copilot Extensions](https://github.blog/2024-05-21-introducing-github-copilot-extensions/) enable [signature verification](https://docs.github.com/en/code-security/secret-scanning/secret-scanning-partner-program#implement-signature-verification-in-your-secret-alert-service) using public keys from the [meta/public_keys](https://api.github.com/meta/public_keys/secret_scanning) API.
* Adds support via`Client.Meta.PublicKeys.Get` …
> [FEAT]: Add support for Public Keys API

- Octokit.Reactive/Clients/IObservableOauthClient.cs
- Octokit.Reactive/Clients/ObservableOauthClient.cs
- Octokit/Clients/IOAuthClient.cs
- Octokit/Clients/OAuthClient.cs
I did not make an issue, but there is already multiples PR for other parts of the codebase so I guess this is fine?
----
We could never cancel login requests (especially device flow requests, which waits for the user to do something in a browser window).
We can now cancel such requests.
----
> Add optional cancellation token for oauth client

- Octokit.Tests/SimpleJsonTests.cs
- Octokit/SimpleJson.cs
Noticed this allocation while looking at a profile of solution load in visual studio. These StringBuilder allocations were showing up as 0.5% of total allocations. I took a peek at the code, and reaslized the StringBuilder need not be created unless there is a '\' in the string value being parsed. In that case, just copy already seen characters into a StringBuilder and continue as previously.
Resolves [2976](https://github.com/octokit/octokit.net/issues/2976)
----
* String parsing was always allocating a StringBuilder.
* Changed to only allocate if there are escaped characters in the json.
----
> Reduce string allocations during SimpleJson.ParseString

- Octokit.Tests/Clients/StatisticsClientTests.cs
- Octokit.Tests/Models/PunchCardTests.cs
- Octokit/Clients/StatisticsClient.cs
- Octokit/Models/Response/PunchCard.cs
- Octokit/Models/Response/PunchCardPoint.cs
Future-proofing. Just because, any time you have an arbitrary statistical counter, there could be some really big counts.
----
Numeric values deserialize as int32, using StatisticsClient.
Numeric values deserialize as int64, using StatisticsClient.
I don't see any docs for the PunchCard classes, which are where the API changes are.
PunchCard and PunchCardPoint public constructors accepting the old int array parameter types are added, just for backward compatibility. But the return type of CommitCount and GetCommitCountFor _do_ have to change to long, which I guess is unfortunately, technically breaking.
----
> BREAKING CHANGE: Use long type for reading PunchCard statistics, just in case
