octokit/octokit.net

CONTRIBUTING.md, Octokit.Tests.Integration/Clients/RepositoriesClientTests.cs, Octokit.Tests.Integration/Helper.cs, Octokit.Tests.Integration/Helpers/IntegrationTestAttribute.cs, Octokit.Tests.Integration/Helpers/PaidAccountTestAttribute.cs, Octokit.Tests.Integration/Octokit.Tests.Integration.csproj, Octokit/Clients/RepositoriesClient.cs, Octokit/Helpers/ApiErrorExtensions.cs
=> support for paid account test scenarios

Octokit.Tests/Clients/RepositoriesClientTests.cs, Octokit/Clients/RepositoriesClient.cs, Octokit/Http/InMemoryCredentialStore.cs, Octokit/Http/JsonHttpPipeline.cs, ReleaseNotes.md, SolutionInfo.cs
=> Release v0.6.2

Octokit.Tests.Integration/Clients/RepositoriesClientTests.cs, Octokit.Tests/Clients/RepositoriesClientTests.cs, Octokit.Tests/Exceptions/RepositoryExistsExceptionTests.cs, Octokit/Clients/RepositoriesClient.cs, Octokit/Exceptions/RepositoryExistsException.cs
=> Refactored RepositoryExistsException 

README.md
Fixes #685
I'm sending this PR live from stage, so bear with me... :sparkles:
=> Added a build badge to README.md

Octokit.Tests/Clients/TeamsClientTests.cs, Octokit/Helpers/ApiUrls.cs
Updated TeamMember api endpoint to route to latest team github api
endpoint (old endpoint was deprecated)
=> Fixed Team Member Endpoint

Octokit/Models/Response/CompareResult.cs
Added missing property 'Files' in 'CompareResult.class'
=> Added property 'Files' in 'CompareResult.Class'

Octokit.Tests/Clients/SearchClientTests.cs, Octokit/Models/Request/SearchCodeRequest.cs, Octokit/Models/Request/SearchIssuesRequest.cs
=> Add codeseach params

Octokit.Tests/Http/ConnectionTests.cs, Octokit.Tests/Http/JsonHttpPipelineTests.cs, Octokit/Http/JsonHttpPipeline.cs, ReleaseNotes.md, SolutionInfo.cs, build.fsx
- ~~[ ] :thumbsup: and merged #712~~ :boot:
- ~~[ ] update release notes to add #712~~ :boot:
=> 0.7.0 - All Torn Down

Octokit.Tests.Integration/Clients/RepositoriesClientTests.cs
It should be skipped if you don't
=> this test requires the organization environment variable be set

Octokit/Octokit-Monotouch.csproj
Octokit-Monotouch won't build with the missing files
=> Delete the missing files from the csproj for Octokit-Monotouch

Octokit/Models/Request/ReleaseAssetUpload.cs, Octokit/Octokit-Mono.csproj, Octokit/Octokit-MonoAndroid.csproj, Octokit/Octokit-Monotouch.csproj, Octokit/Octokit-Portable.csproj, Octokit/Octokit-netcore45.csproj, Octokit/Octokit.csproj, ReleaseNotes.md, SolutionInfo.cs
=> 0.7.1 - Please Advise

Octokit.Tests/Http/ConnectionTests.cs, Octokit.Tests/Http/JsonHttpPipelineTests.cs, Octokit/Http/JsonHttpPipeline.cs, ReleaseNotes.md, SolutionInfo.cs
Fixes #733 
@distantcam there's one particular *popular* repository you have access to which is causing the excessive paging you're seeing.
I'm removing that feature (as it's part of the preview APIs) and will bring this up with the team in the morning.
=> 0.7.2 - Can't Handle My Scale

Octokit/Models/Response/Repository.cs
Fixes https://github.com/octokit/octokit.net/issues/713
=> Deprecate Repository.Organization

Octokit/Models/Response/Repository.cs
Added obsolete tag to the SubscribersCount field
Not fully confident in understanding the codebase, so might need som more work. 
If so please let me know.
Fixes #736
=> Added obsolete tag to member in file. 

Octokit.Reactive/Clients/IObservableRepositoriesClient.cs, Octokit.Reactive/Clients/ObservableRepositoriesClient.cs, Octokit.Tests.Integration/Clients/RepositoriesClientTests.cs, Octokit.Tests/Clients/RepositoriesClientTests.cs, Octokit/Clients/IRepositoriesClient.cs, Octokit/Clients/RepositoriesClient.cs, Octokit/Models/Request/RepositoryRequest.cs, Octokit/Octokit-Mono.csproj, Octokit/Octokit-MonoAndroid.csproj, Octokit/Octokit-Monotouch.csproj, Octokit/Octokit-Portable.csproj, Octokit/Octokit-netcore45.csproj, Octokit/Octokit.csproj
See https://developer.github.com/v3/repos/#list-your-repositories for the details
cc @joshvera @Haacked
=> Add filter parameters for RepositoryClient.GetAllForCurrent

ReleaseNotes.md, SolutionInfo.cs
=> 0.7.3 - Strongly Typod

CustomDictionary.xml, Octokit.Tests.Integration/Clients/EventsClientTests.cs, Octokit.Tests/Clients/EventsClientTests.cs, Octokit.Tests/OctoKit.Tests-NetCore45.csproj, Octokit.Tests/Octokit.Tests-Portable.csproj, Octokit/Http/SimpleJsonSerializer.cs, Octokit/Models/Response/Activity.cs, Octokit/Models/Response/ActivityPayloads/ActivityPayload.cs, Octokit/Models/Response/ActivityPayloads/CommitCommentPayload.cs, Octokit/Models/Response/ActivityPayloads/ForkEventPayload.cs, Octokit/Models/Response/ActivityPayloads/IssueCommentPayload.cs, Octokit/Models/Response/ActivityPayloads/IssueEventPayload.cs, Octokit/Models/Response/ActivityPayloads/PullRequestCommentPayload.cs, Octokit/Models/Response/ActivityPayloads/PullRequestEventPayload.cs, Octokit/Models/Response/ActivityPayloads/PushEventPayload.cs, Octokit/Models/Response/ActivityPayloads/StarredEventPayload.cs, Octokit/Octokit-Mono.csproj, Octokit/Octokit-MonoAndroid.csproj, Octokit/Octokit-Monotouch.csproj, Octokit/Octokit-Portable.csproj, Octokit/Octokit-netcore45.csproj, Octokit/Octokit.csproj
=> Activity payload

Octokit.Reactive/Clients/IObservableAuthorizationsClient.cs, Octokit.Reactive/Clients/ObservableAuthorizationsClient.cs, Octokit.Tests.Integration/Clients/AuthorizationClientTests.cs, Octokit.Tests.Integration/Helper.cs, Octokit.Tests/Clients/AuthorizationsClientTests.cs, Octokit/Clients/AuthorizationsClient.cs, Octokit/Clients/IAuthorizationsClient.cs, Octokit/Helpers/ApiUrls.Authorizations.cs
Add functionality for checking, resetting and revoking OAuth application tokens
Fixes https://github.com/octokit/octokit.net/issues/682
Fixes https://github.com/octokit/octokit.net/issues/652
Fixes https://github.com/octokit/octokit.net/issues/653
Fixes https://github.com/octokit/octokit.net/issues/654
=> Application authorization checking, resetting and revoking

Octokit.Reactive/Clients/IObservableMiscellaneousClient.cs, Octokit.Reactive/Clients/ObservableMiscellaneousClient.cs, Octokit.Tests.Integration/Clients/MiscellaneousClientTests.cs, Octokit/Clients/IMiscellaneousClient.cs, Octokit/Clients/MiscellaneousClient.cs, Octokit/Models/Response/GitIgnoreTemplate.cs, Octokit/Octokit-Mono.csproj, Octokit/Octokit-MonoAndroid.csproj, Octokit/Octokit-Monotouch.csproj, Octokit/Octokit-Portable.csproj, Octokit/Octokit-netcore45.csproj, Octokit/Octokit.csproj
I have kind of an urgent need for this. :smile:
=> Implement Methods to retrieve gitignore

Octokit.Tests.Conventions/ModelTests.cs, Octokit.Tests/Clients/StatisticsClientTests.cs, Octokit.Tests/Helpers/AssertEx.cs, Octokit.Tests/Reactive/ObservablePullRequestsClientTests.cs, Octokit/Clients/MiscellaneousClient.cs, Octokit/Clients/StatisticsClient.cs, Octokit/Models/Response/CodeFrequency.cs, Octokit/Models/Response/Commit.cs, Octokit/Models/Response/CommitActivity.cs, Octokit/Models/Response/License.cs, Octokit/Models/Response/Merge.cs, Octokit/Models/Response/Participation.cs, Octokit/Models/Response/PullRequestCommit.cs, Octokit/Models/Response/WeeklyCommitActivity.cs
=> Readonly lists and dictionaries on response models

Octokit.Reactive/Clients/IObservablePullRequestsClient.cs, Octokit.Reactive/Clients/ObservablePullRequestsClient.cs, Octokit.Tests.Integration/Clients/PullRequestsClientTests.cs, Octokit.Tests/Clients/PullRequestsClientTests.cs, Octokit.Tests/Reactive/ObservablePullRequestsClientTests.cs, Octokit/Clients/IPullRequestsClient.cs, Octokit/Clients/PullRequestsClient.cs, Octokit/Helpers/ApiUrls.cs, Octokit/Models/Request/PullRequestRequest.cs, Octokit/Models/Response/PullRequestFile.cs, Octokit/Octokit-Mono.csproj, Octokit/Octokit-MonoAndroid.csproj, Octokit/Octokit-Monotouch.csproj, Octokit/Octokit-Portable.csproj, Octokit/Octokit-netcore45.csproj, Octokit/Octokit.csproj
=> Missing pull requests bits

ReleaseNotes.md, SolutionInfo.cs
=> 0.8 - Markov Twain

Octokit.Reactive/Clients/IObservableFollowersClient.cs, Octokit.Reactive/Clients/ObservableFollowersClient.cs, Octokit.Tests.Integration/Clients/FollowersClientTests.cs, Octokit.Tests/Clients/FollowersClientTests.cs, Octokit.Tests/Reactive/ObservableFollowersTest.cs, Octokit/Clients/FollowersClient.cs, Octokit/Clients/IFollowersClient.cs
=> Update Followers to follow GetAll* convention

ReleaseNotes.md, SolutionInfo.cs
A few breaking changes in here, so why not push this out as soon as possible?
=> v0.9.0 - It's the Vibe

Octokit.Reactive/Clients/IObservableAuthorizationsClient.cs, Octokit.Reactive/Clients/ObservableAuthorizationsClient.cs, Octokit.Reactive/Helpers/AuthorizationExtensions.cs, Octokit.Tests.Integration/Clients/AuthorizationClientTests.cs, Octokit.Tests/Clients/AuthorizationsClientTests.cs, Octokit/Clients/AuthorizationsClient.cs, Octokit/Clients/IAuthorizationsClient.cs, Octokit/Http/ApiConnection.cs, Octokit/Http/Connection.cs, Octokit/Http/IApiConnection.cs, Octokit/Http/IConnection.cs
=> Updates to handle 4/20 changes to authorization API

Octokit.Reactive/Clients/IObservableRepositoriesClient.cs, Octokit.Reactive/Clients/ObservableRepositoriesClient.cs, Octokit.Tests.Integration/Clients/EventsClientTests.cs, Octokit.Tests.Integration/Clients/RepositoriesClientTests.cs, Octokit.Tests.Integration/Reactive/ObservableRepositoriesClientTests.cs, Octokit.Tests/Clients/AuthorizationsClientTests.cs, Octokit.Tests/Clients/RepositoriesClientTests.cs, Octokit.Tests/Reactive/ObservableRepositoriesClientTests.cs, Octokit/Clients/IRepositoriesClient.cs, Octokit/Clients/RepositoriesClient.cs, Octokit/Models/Response/CommitComment.cs, ReleaseNotes.md, SolutionInfo.cs
=> release candidate

Octokit/Models/Response/PullRequestFile.cs
Properties not serialized correctly due to invalid names.
=> Renamed PullRequestFile's *Uri properties to *Url

Octokit.Tests/OctoKit.Tests-NetCore45.csproj, Octokit.Tests/Octokit.Tests-Portable.csproj, ReleaseNotes.md, SolutionInfo.cs
=> v0.11 release candidate

ReleaseNotes.md, SolutionInfo.cs
=> v0.12 - The Webzone™

README.md
=> introduced a "related projects" section

Octokit.Reactive/Octokit.Reactive-Mono.csproj, Octokit.Reactive/Octokit.Reactive-MonoAndroid.csproj, Octokit.Reactive/Octokit.Reactive-Monotouch.csproj, Octokit.Reactive/Octokit.Reactive.csproj, Octokit.Tests.Conventions/Octokit.Tests.Conventions.csproj, Octokit.Tests.Integration/Octokit.Tests.Integration.csproj, Octokit.Tests/OctoKit.Tests-NetCore45.csproj, Octokit.Tests/Octokit.Tests-Portable.csproj, Octokit.Tests/Octokit.Tests.csproj, Octokit/Octokit-Mono.csproj, Octokit/Octokit-MonoAndroid.csproj, Octokit/Octokit-Monotouch.csproj, Octokit/Octokit-Portable.csproj, Octokit/Octokit-netcore45.csproj, Octokit/Octokit.csproj
Woah! Quite a lot of projects you got going on there... :weary::gun:
This'll make Visual Studio/R# stop teasing me with those new and :sparkles:shiny:sparkles: C# 6 features :lipstick:
Though maybe it's time to start thinking about it? :wink:
=> Make sure I don't succumb to the temptation of using C# 6

ReleaseNotes.md, SolutionInfo.cs
Putting out this before repository redirects land (oh, and I need #795 for something)
=> v0.13 - Doof Wagon

Octokit.Tests/Clients/SearchClientTests.cs, Octokit/Models/Request/BaseSearchRequest.cs, Octokit/Models/Request/SearchRepositoriesRequest.cs
Fixed issue #732, to be able to create requests with no search term.
Added no-args constructor to BaseSearchRequest also.
Added a test to check things work as expected.
=> Added no-args constructor to the SearchRepositoriesRequest. Fixing issue 732.

Octokit.Tests.Integration/Clients/RepositoryContentsClientTests.cs, ReleaseNotes.md, SolutionInfo.cs, build.cmd
=> v0.14 - Jet Lag

docs/search.md
Forgot to change these... :disappointed:
=> Updated docs with new collection

Octokit.Tests/Clients/SearchClientTests.cs, Octokit/Models/Request/SearchRepositoriesRequest.cs
resolves #841
This seemed really straightforward, but if there's more to it, let me know!
=> Add multiple dates to DateRange filter

Octokit/Models/Response/Issue.cs
=> #875 fixing doc comments on Issue type

Octokit/Octokit-Monotouch.csproj
Fixes #886
cc @naveensrinivasan
=> removed missing files from Monotouch project

Octokit.Reactive/Clients/IObservableMiscellaneousClient.cs, Octokit.Reactive/Clients/ObservableMiscellaneousClient.cs, Octokit.Tests.Integration/Clients/MiscellaneousClientTests.cs, Octokit.Tests.Integration/Helper.cs, Octokit/Clients/IMiscellaneousClient.cs, Octokit/Clients/MiscellaneousClient.cs, Octokit/Models/Response/Meta.cs, Octokit/Octokit-Mono.csproj, Octokit/Octokit-MonoAndroid.csproj, Octokit/Octokit-Monotouch.csproj, Octokit/Octokit-Portable.csproj, Octokit/Octokit-netcore45.csproj, Octokit/Octokit.csproj
See https://developer.github.com/v3/meta/ for more information about
this endpoint.
=> Implement the Meta endpoint

Octokit/Models/Response/Milestone.cs
(see https://developer.github.com/v3/issues/milestones/)
=> Add 'closed_at' to reflect latest changes in the milestones-api

Octokit.Tests.Integration/Clients/IssuesClientTests.cs, Octokit.Tests/Clients/IssuesClientTests.cs, Octokit/Models/Response/Issue.cs
=> Add Events URL to the Issue class.

build.fsx
With this fix we should be able to compile the Xamarin Studio Solution from the shell.
=> Build fix for Xamarin Studio Solution

Octokit/Models/Response/CommitEntity.cs, Octokit/Models/Response/GitHubCommit.cs, Octokit/Octokit-Mono.csproj, Octokit/Octokit-MonoAndroid.csproj, Octokit/Octokit-Monotouch.csproj, Octokit/Octokit-Portable.csproj, Octokit/Octokit-netcore45.csproj, Octokit/Octokit.csproj
Fixes [#779](https://github.com/octokit/octokit.net/issues/779) :)
=> Changes GitHubCommit.Author/Committer

README.md
Updated the readme to include the nuget reference to Octokit.Reactive
=> Updated the readme with reactive octokit.

build.sh
Included build.sh to build form non-windows.
=> Created build.sh

.gitignore, mkdocs.yml
added a customization template for the project and organized the existing content under something resembling a hierarchy
=> bootstrapping a simple site layout

Octokit.Reactive/Clients/IObservableMiscellaneousClient.cs, Octokit.Reactive/Clients/ObservableMiscellaneousClient.cs, Octokit.Tests/Clients/MiscellaneousClientTests.cs, Octokit.Tests/Clients/SearchClientTests.cs, Octokit/Clients/IMiscellaneousClient.cs, Octokit/Clients/MiscellaneousClient.cs, Octokit/Models/Request/NewArbitraryMarkDown.cs, Octokit/Models/Request/SearchIssuesRequest.cs, Octokit/Models/Response/PullRequest.cs, Octokit/Octokit-Mono.csproj, Octokit/Octokit-MonoAndroid.csproj, Octokit/Octokit-Monotouch.csproj, Octokit/Octokit-Portable.csproj, Octokit/Octokit-netcore45.csproj, Octokit/Octokit.csproj, SolutionInfo.cs
Just extracting a couple of outstanding PRs which are basically ready to merge.
Supersedes #947
Supersedes #937
Supersedes #935
Fixes #938
Fixes #910
Fixes #839
cc @haacked @chenjiaming93
=> clean up some pending PRs

Octokit.Tests.Integration/Clients/RepositoriesClientTests.cs, Octokit/Clients/RepositoriesClient.cs, Octokit/Exceptions/InvalidGitignoreTemplateException.cs, Octokit/Octokit-Mono.csproj, Octokit/Octokit-MonoAndroid.csproj, Octokit/Octokit-Monotouch.csproj, Octokit/Octokit-Portable.csproj, Octokit/Octokit-netcore45.csproj, Octokit/Octokit.csproj
=> Gitignore exception

Octokit.Tests.Integration/Clients/PullRequestsClientTests.cs, Octokit/Clients/PullRequestsClient.cs, Octokit/Exceptions/PullRequestMismatchException.cs, Octokit/Exceptions/PullRequestNotMergeableException.cs, Octokit/Octokit-Mono.csproj, Octokit/Octokit-MonoAndroid.csproj, Octokit/Octokit-Monotouch.csproj, Octokit/Octokit-Portable.csproj, Octokit/Octokit-netcore45.csproj, Octokit/Octokit.csproj
This supersedes #934 and fixes merge conflicts.
=> better merge exception rebased

README.md
Included the beta nuget package location
=> Included the beta nuget package location

Octokit/Http/ProductHeaderValue.cs
Fixed a parameter name that was misleading and documented the methods and properties.
=> Document product header value

.travis.yml, README.md, build.sh
Included the travis CI for the coreclr builds.
=> Included the travis ci for the coreclr

Octokit.sln
This is empty and isn't needed.
=> Remove vestigial solution folder

README.md
=> Remove extra `)` in README

Octokit/Exceptions/InvalidGitignoreTemplateException.cs, Octokit/Helpers/CollectionExtensions.cs, Octokit/Helpers/StringExtensions.cs, Octokit/Http/ApiInfo.cs, Octokit/Http/HttpClientAdapter.cs, Octokit/Http/RateLimit.cs, Octokit/Models/Response/ActivityPayloads/ActivityPayload.cs
=> Code cleanup

Octokit.Tests.Integration/Helper.cs
=> Add comment to make test account usage clearer

docs/issues.md
Added some more info on where "_issuesClient" is obtained from following a recent Issue.
=> Clarified "_issuesClient"

Octokit.Reactive/Clients/ObservableBlobClient.cs, Octokit.Reactive/Clients/ObservableCommitsClient.cs, Octokit.Reactive/Clients/ObservableReferencesClient.cs, Octokit.Reactive/Clients/ObservableTagsClient.cs, Octokit.Reactive/Clients/ObservableTreesClient.cs, Octokit.Reactive/IObservableGitHubClient.cs, Octokit.Reactive/ObservableGitHubClient.cs, Octokit.Tests.Integration/Clients/BlobClientTests.cs, Octokit.Tests.Integration/Clients/CommitStatusClientTests.cs, Octokit.Tests.Integration/Clients/CommitsClientTests.cs, Octokit.Tests.Integration/Clients/DeploymentStatusClientTests.cs, Octokit.Tests.Integration/Clients/DeploymentsClientTests.cs, Octokit.Tests.Integration/Clients/MergingClientTests.cs, Octokit.Tests.Integration/Clients/PullRequestReviewCommentsClientTests.cs, Octokit.Tests.Integration/Clients/PullRequestsClientTests.cs, Octokit.Tests.Integration/Clients/ReferencesClientTests.cs, Octokit.Tests.Integration/Clients/RepositoryCommitsClientTests.cs, Octokit.Tests.Integration/Clients/StatisticsClientTests.cs, Octokit.Tests.Integration/Clients/TreeClientTests.cs, Octokit.Tests.Integration/Helpers/RepositorySetupHelper.cs, Octokit.Tests/Reactive/ObservableBlobClientTests.cs, Octokit.Tests/Reactive/ObservableCommitsClientTests.cs, Octokit.Tests/Reactive/ObservableTreesClientTests.cs, Octokit/GitHubClient.cs, Octokit/IGitHubClient.cs
=> Switch GitDatabase->Git on IGitHubProvider

docs/contributing.md, docs/demos/exploring-pull-requests.md, docs/getting-started.md, docs/index.md, mkdocs.yml
=> a bit of cleanup

Octokit/Models/Response/PullRequest.cs
=> Add Milestone property to PullRequest

Octokit.Reactive/Clients/IObservableRepositoriesClient.cs, Octokit.Reactive/Clients/IObservableUserAdministrationClient.cs, Octokit.Reactive/Clients/ObservableRepositoriesClient.cs, Octokit.Reactive/Clients/ObservableRepositoryContentsClient.cs, Octokit.Reactive/Clients/ObservableUsersClient.cs, Octokit.Tests.Integration/Clients/BranchesClientTests.cs, Octokit.Tests.Integration/Clients/PullRequestsClientTests.cs, Octokit.Tests.Integration/Clients/RepositoryCollaboratorClientTests.cs, Octokit.Tests.Integration/Clients/RepositoryHooksClientTests.cs, Octokit.Tests.Integration/Helper.cs, Octokit.Tests/Clients/RepositoriesClientTests.cs, Octokit.Tests/Clients/UserAdministrationClientTests.cs, Octokit.Tests/Exceptions/ApiExceptionTests.cs, Octokit.Tests/Reactive/Enterprise/ObservableEnterpriseAdminStatsClientTests.cs, Octokit.Tests/Reactive/ObservableRepositoriesClientTests.cs, Octokit.Tests/SimpleJsonSerializerTests.cs, Octokit/Clients/Enterprise/EnterpriseAdminStatsClient.cs, Octokit/Clients/IRepositoryContentsClient.cs, Octokit/Clients/IStarredClient.cs, Octokit/Clients/IUserAdministrationClient.cs, Octokit/Clients/RepositoriesClient.cs, Octokit/Clients/RepositoryContentsClient.cs, Octokit/Clients/RepositoryPagesClient.cs, Octokit/Clients/UsersClient.cs, Octokit/Exceptions/ApiException.cs, Octokit/Helpers/AcceptHeaders.cs, Octokit/Helpers/ApiUrls.cs, Octokit/IGitHubClient.cs, Octokit/Models/Request/NewRepositoryHook.cs, Octokit/Models/Request/NewRepositoryWebHook.cs
=> just a bit of code cleanup

Octokit.Tests.Integration/SelfTests.cs, ReleaseNotes.md, build.fsx, docs/shipping-releases.md
=> v0.18 - Bringing The Thunder

Octokit.Tests.Integration/Clients/SearchClientTests.cs
Added failing search issues api integration test. relates to #1082
=> Added failing search issues api integration test

Octokit/Models/Response/PullRequest.cs
=> Add Locked property to PullRequest

Octokit.Tests.Integration/Helpers/ReferenceExtensionsTests.cs, Octokit.Tests.Integration/Octokit.Tests.Integration.csproj, Octokit/Helpers/ReferenceExtensions.cs, Octokit/Octokit-Mono.csproj, Octokit/Octokit-MonoAndroid.csproj, Octokit/Octokit-Monotouch.csproj, Octokit/Octokit-Portable.csproj, Octokit/Octokit-netcore45.csproj, Octokit/Octokit.csproj
=> Create branch helper method

docs/issues.md
I changed placeholders in the issue sample, issue #1130.
=> #1130 Change issue sample placeholder to indicate that they should be changed

Octokit.Tests.Integration/Clients/RepositoriesClientTests.cs
The test is passing. Unskipping it. #1002
=> Issue 1002

ReleaseNotes.md, SolutionInfo.cs
I'm trying a bit of a different layout this time around.
=> v0.19 - Identifying Types

Octokit.Tests/Clients/GistsClientTests.cs
As was mentioned here
https://github.com/octokit/octokit.net/pull/1190#discussion-diff-56327668
Consistency is our friend! So, this PR intends to fix inconsistency a little bit.
/cc @ryangribble
=> Fix inconsistency in GistsClientTests

Octokit.Reactive/Clients/Enterprise/IObservableEnterpriseLdapClient.cs, Octokit.Reactive/Clients/Enterprise/ObservableEnterpriseLdapClient.cs, Octokit.Tests.Integration/Clients/Enterprise/EnterpriseLdapClientTests.cs, Octokit.Tests.Integration/Clients/RepositoriesClientTests.cs, Octokit.Tests.Integration/Clients/UserAdministrationClientTests.cs, Octokit.Tests.Integration/EnterpriseHelper.cs, Octokit.Tests.Integration/Reactive/Enterprise/ObservableEnterpriseLdapClientTests.cs, Octokit.Tests.Integration/Reactive/ObservableUserKeysClientTests.cs, Octokit.Tests/Clients/Enterprise/EnterpriseOrganizationClientTests.cs, Octokit.Tests/Clients/RepositoriesClientTests.cs, Octokit.Tests/Clients/RepositoryContentsClientTests.cs, Octokit.Tests/Clients/UserAdministrationClientTests.cs, Octokit.Tests/Reactive/Enterprise/ObservableEnterpriseLdapClientTests.cs, Octokit.Tests/Reactive/Enterprise/ObservableEnterpriseOrganizationClientTests.cs, Octokit.Tests/Reactive/Enterprise/ObservableEnterpriseSearchIndexingClientTests.cs, Octokit.Tests/Reactive/ObservableIssuesClientTests.cs, Octokit.Tests/Reactive/ObservableUserAdministrationClientTests.cs, Octokit/Clients/Enterprise/EnterpriseLdapClient.cs, Octokit/Clients/Enterprise/EnterpriseSearchIndexingClient.cs, Octokit/Clients/UserAdministrationClient.cs, Octokit/Http/IApiConnection.cs, Octokit/Models/Request/CreateFileRequest.cs, SolutionInfo.cs
I found the function [here](https://github.com/octokit/octokit.net/blob/master/Octokit.Tests/Reactive/ObservableIssuesClientTests.cs#L327) to be incorrect. Therefore corrected it.
--EDIT--
I also ran **./build FormatCode** just in case i missed some formatting things.
=> TheUpdateMethod.EnsureArgumentsNotNull function changed

Octokit.Tests/SimpleJsonSerializerTests.cs, Octokit/Models/Response/PullRequestCommit.cs
Some redundant commas were removed.
=> Some redundant parentheses were fixed.

Octokit.Tests.Integration/Clients/IssuesClientTests.cs, Octokit.Tests/Clients/PullRequestReviewCommentsClientTests.cs, Octokit.Tests/GitHubClientTests.cs, Octokit.Tests/Helpers/UriExtensionsTests.cs, Octokit.Tests/Http/ConnectionTests.cs, Octokit.Tests/Http/HttpClientAdapterTests.cs, Octokit.Tests/Models/MilestoneRequestTests.cs, Octokit.Tests/Reactive/ObservablePullRequestReviewCommentsClientTests.cs, Octokit/Http/Connection.cs, Octokit/Models/Request/RepositoryRequest.cs, Octokit/Models/Response/Page.cs
Some redundant commas were removed.
=> Remove redundant commas

Octokit/Helpers/ApiUrls.cs, Octokit/Http/ApiConnection.cs
I have fixed some misspells in ApiUrls.cs and ApiConnection.cs to make code more clean.
=> Some misspells in ApiUrls and ApiConnection were fixed.

.travis.yml
=> remove the PCL unpackaging when running on Travis

Octokit/Clients/UserAdministrationClient.cs
I continue my battle with code redundancies. Now, all redundant control flow jump statements were removed.
=> All redundant control flow jump statements were removed

Octokit.Tests.Integration/Reactive/ObservableUserAdministrationClientTests.cs, Octokit.Tests.Integration/Reactive/ObservableUserKeysClientTests.cs, Octokit/Exceptions/ApiException.cs, Octokit/Exceptions/RepositoryExistsException.cs, Octokit/Exceptions/TwoFactorAuthorizationException.cs, Octokit/Helpers/ModelExtensions.cs, Octokit/Models/Request/NewArbitraryMarkDown.cs
Just continue my war with redundancies in code.
Now all redundant parentheses were removed from code.
/cc @shiftkey
=> Redundant parentheses were removed

Octokit.Tests.Integration/Clients/IssuesClientTests.cs, Octokit/Models/Response/Issue.cs
=> Add repository property to Issue response model

Octokit.Reactive/Clients/IObservableIssuesEventsClient.cs, Octokit.Reactive/Clients/ObservableIssuesEventsClient.cs, Octokit.Tests.Integration/Clients/IssuesEventsClientTests.cs, Octokit.Tests/Clients/IssuesEventsClientTests.cs, Octokit.Tests/Octokit.Tests.csproj, Octokit.Tests/Reactive/ObservableIssuesEventsClientTests.cs, Octokit/Clients/IIssuesEventsClient.cs, Octokit/Clients/IssuesEventsClient.cs
=> Add ApiOptions overloads to methods on I(Observable)IssuesEventsClient

Octokit.Reactive/Clients/IObservableWatchedClient.cs, Octokit.Reactive/Clients/ObservableWatchedClient.cs, Octokit.Tests.Integration/Clients/WatchedClientTests.cs, Octokit.Tests.Integration/Octokit.Tests.Integration.csproj, Octokit.Tests/Clients/WatchedClientTests.cs, Octokit.Tests/Octokit.Tests.csproj, Octokit.Tests/Reactive/ObservableWatchedClientTests.cs, Octokit/Clients/IWatchedClient.cs, Octokit/Clients/WatchedClient.cs
Fixes #1184 
To-do:
~~I've grabbed @devkhan commits from his PR and added some fixes and tests. I suppose, this issue #1279 could be closed after this one.~~
=> Add ApiOption overloads to methods on I(Observable)WatchedClient 

Octokit.Reactive/Clients/IObservablePullRequestReviewCommentsClient.cs, Octokit.Reactive/Clients/ObservablePullRequestReviewCommentsClient.cs, Octokit.Tests.Integration/Clients/PullRequestReviewCommentsClientTests.cs, Octokit.Tests/Clients/PullRequestReviewCommentsClientTests.cs, Octokit.Tests/Reactive/ObservablePullRequestReviewCommentsClientTests.cs, Octokit/Clients/IPullRequestReviewCommentsClient.cs, Octokit/Clients/PullRequestReviewCommentsClient.cs
Fixes #1166 
To-do:
/cc @shiftkey. @ryangribble
=> Add ApiOption overloads to methods on I(Observable)PullRequestReviewCommentsClient

Octokit.Tests.Integration/Clients/DeploymentStatusClientTests.cs, Octokit.Tests.Integration/Clients/DeploymentsClientTests.cs, Octokit.Tests/Clients/DeploymentStatusClientTests.cs, Octokit.Tests/Clients/DeploymentsClientTests.cs, Octokit/Clients/DeploymentStatusClient.cs, Octokit/Clients/DeploymentsClient.cs, Octokit/Helpers/AcceptHeaders.cs, Octokit/Models/Request/NewDeployment.cs, Octokit/Models/Request/NewDeploymentStatus.cs, Octokit/Models/Response/Deployment.cs, Octokit/Models/Response/DeploymentStatus.cs
This PR implements the functionality described in issue #1249, which is to add new preview fields.
I was looking into adding tests for these methods, but how would I do that? If I look at the [deployments API](https://developer.github.com/v3/repos/deployments/#create-a-deployment), the response does not contain any of the new information. Is that correct?
=> Deployment and DeploymentStatus API enhancements preview period. (#1249)

Octokit.Tests.Integration/Clients/RepositoryHooksClientTests.cs, Octokit.Tests.Integration/fixtures/RepositoriesHooksFixture.cs, ReleaseNotes.md, SolutionInfo.cs, samples/linqpad-samples/2-releases.linq, samples/linqpad-samples/5-interact-with-git-database.linq, samples/linqpad-samples/6-create-repository.linq
=> v0.21 - Which Puppy

ReleaseNotes.md, SolutionInfo.cs
I published up v0.21 today without realising I missed calling out some of the new work that @maddin2016 had contributed. This is the remedy for that (yes, it's not technically a bugfix release but it'll help me sleep at night).
=> v0.21.1 - I've Made A Huge Mistake

ReleaseNotes.md, SolutionInfo.cs
Aiming to ship this **Wednesday 31 August** AEST. Running through the test suite today/tomorrow.
=> v0.22 - Ridgy Didge

Octokit.Tests.Integration/Clients/SearchClientTests.cs, Octokit.Tests/Clients/SearchClientTests.cs, Octokit.Tests/Models/SearchIssuesRequestExclusionsTests.cs, Octokit.Tests/Models/SearchIssuesRequestTests.cs, Octokit/Models/Request/SearchRepositoriesRequest.cs
fix #1459 
Fixed value of `Parameter` attribute. 
Added new integration test and refined unit tests.
=> Fix of bug with search of C# code

docs/labels.md
=> Add docs snippet for label coloring

Octokit/Models/Response/CommitContent.cs
Fixes incorrect comment identified in issue #1526
=> Modified code comment for RepositoryContentInfo.Sha

build/Tasks/FormatCode.cs, build/tools.project.json
=> Add a code formatting task to CAKE

Octokit.sln
paths in .sln file should match actual file names
=> fix .sln file for linux

Octokit.Tests.Integration/Clients/NotificationsClientTests.cs, Octokit.Tests.Integration/Octokit.Tests.Integration.csproj, Octokit.Tests.Integration/Reactive/ObservableNotificationsClientTests.cs, Octokit.Tests/Clients/NotificationsClientTests.cs, Octokit.Tests/Reactive/ObservableNotificationsClientTests.cs, Octokit/Clients/NotificationsClient.cs
=> bugfix - PUT should have a payload for Mark as Read

Octokit.Reactive/Clients/IObservableOrganizationOutsideCollaboratorsClient.cs, Octokit.Reactive/Clients/IObservableOrganizationsClient.cs, Octokit.Reactive/Clients/ObservableOrganizationOutsideCollaboratorsClient.cs, Octokit.Reactive/Clients/ObservableOrganizationsClient.cs, Octokit.Tests.Integration/Clients/OrganizationOutsideCollaboratorsClientTests.cs, Octokit.Tests.Integration/Reactive/ObservableOrganizationOutsideCollaboratorsClientTests.cs, Octokit.Tests/Clients/OrganizationOutsideCollaboratorsClientTests.cs, Octokit.Tests/Reactive/ObservableOrganizationOutsideCollaboratorsClientTests.cs, Octokit/Clients/IOrganizationOutsideCollaboratorsClient.cs, Octokit/Clients/IOrganizationsClient.cs, Octokit/Clients/OrganizationOutsideCollaboratorsClient.cs, Octokit/Clients/OrganizationsClient.cs, Octokit/Exceptions/UserIsLastOwnerOfOrganizationException.cs, Octokit/Exceptions/UserIsNotMemberOfOrganizationException.cs, Octokit/Exceptions/UserIsOrganizationMemberException.cs, Octokit/Helpers/ApiUrls.cs, Octokit/Http/Connection.cs, Octokit/Http/IConnection.cs
=> Add client for organization outside collaborators

Octokit.Reactive/Clients/IObservableOrganizationMembersClient.cs, Octokit.Reactive/Clients/IObservableTeamsClient.cs, Octokit.Reactive/Clients/ObservableOrganizationMembersClient.cs, Octokit.Reactive/Clients/ObservableTeamsClient.cs, Octokit.Tests.Integration/Clients/OrganizationMembersClientTests.cs, Octokit.Tests.Integration/Clients/OrganizationOutsideCollaboratorsClientTests.cs, Octokit.Tests.Integration/Clients/RepositoryCollaboratorClientTests.cs, Octokit.Tests.Integration/Clients/TeamsClientTests.cs, Octokit.Tests.Integration/Helper.cs, Octokit.Tests.Integration/Helpers/TeamContext.cs, Octokit.Tests.Integration/Reactive/ObservableOrganizationMembersClientTests.cs, Octokit.Tests.Integration/Reactive/ObservableOrganizationOutsideCollaboratorsClientTests.cs, Octokit.Tests.Integration/Reactive/ObservableRepositoryCollaboratorClientTests.cs, Octokit.Tests.Integration/Reactive/ObservableTeamsClientTests.cs, Octokit.Tests/Clients/OrganizationMembersClientTests.cs, Octokit.Tests/Clients/TeamsClientTests.cs, Octokit.Tests/Reactive/ObservableOrganizationMembersClientTests.cs, Octokit.Tests/Reactive/ObservableTeamsClientTests.cs, Octokit/Clients/IOrganizationMembersClient.cs, Octokit/Clients/ITeamsClient.cs, Octokit/Clients/OrganizationMembersClient.cs, Octokit/Clients/TeamsClient.cs, Octokit/Helpers/ApiUrls.cs, Octokit/Models/Response/OrganizationMembershipInvitation.cs, Octokit/Models/Response/OrganizationMembershipInvite.cs, Octokit/Models/Response/OrganizationMembershipRole.cs
=> List pending organization / team invitations

Octokit.Tests.Integration/Clients/SearchClientTests.cs, Octokit.Tests/Clients/SearchClientTests.cs, Octokit/Models/Request/SearchCodeRequest.cs
Fixes #1671 
new field allows filtering by organization
=> Added Organization to code search (#1671)

Octokit/Models/Response/BranchProtection.cs
=> Provide constructors for EnforceAdmins class to allow mocking

Octokit.Reactive/Clients/ObservableTeamsClient.cs, Octokit.Tests.Integration/Clients/RepositoryBranchesClientTests.cs, Octokit.Tests.Integration/Clients/SearchClientTests.cs, Octokit/Clients/RepositoryBranchesClient.cs, Octokit/Models/Request/NewTeam.cs, ReleaseNotes.md
Aiming to release this tomorrow
=> Release v0.27 - On a Roll

docs/labels.md
Fixed the code formatting in Labels documentation
=> Fixed code formatting

.travis.yml, Octokit/Models/Response/Milestone.cs
Added UpdatedAt property to Milestone.  It seems like this would not be null, but added similar to ClosedAt property just in case.  This is also a breaking change to Milestone constructor.
=> Added UpdatedAt property to Milestone.

Octokit.Reactive/Clients/IObservableRepositoryInvitationsClient.cs, Octokit.Reactive/Clients/ObservableRepositoryInvitationsClient.cs, Octokit.Tests.Integration/Clients/RepositoryInvitationsClientTests.cs, Octokit.Tests/Clients/RepositoryInvitationsClientTests.cs, Octokit.Tests/Reactive/ObservableRepositoryInvitationsClientTests.cs, Octokit/Clients/IRepositoryInvitationsClient.cs, Octokit/Clients/RepositoryInvitationsClient.cs
=> Add pagination support to repository invitation.

Octokit/Http/SimpleJsonSerializer.cs
Fixes #1683 
I think this is good to go - passes tests at least. Might want to double-check the integration tests though - I had a few problems with those that appeared unrelated to this change.
=> Refactors GitHubSerializerStrategy to be thread-safe (#1683)

Octokit.Tests.Integration/Clients/PullRequestsClientTests.cs, Octokit.Tests/Reactive/ObservablePullRequestsClientTests.cs, Octokit/Models/Response/PullRequestFile.cs
Fixes #1768 
Pretty straight forward change, and gets my consuming project rolling again. Unit test and convention tests pass, but it looks like I'm having unrelated issues with the integration tests.
=> Add PreviousFileName to the PullRequestFile model

Octokit.Tests/Helpers/StringExtensionsTests.cs, Octokit.Tests/Models/SearchIssuesRequestExclusionsTests.cs, Octokit.Tests/Models/SearchIssuesRequestTests.cs, Octokit/Helpers/StringExtensions.cs, Octokit/Models/Request/SearchIssuesRequest.cs, Octokit/Models/Request/SearchIssuesRequestExclusions.cs
=> Enable support for milestone-based issues queries

.travis.yml, Octokit.Tests.Integration/Clients/Enterprise/EnterprisePreReceiveEnvironmentsClientTests.cs, Octokit.Tests.Integration/Clients/GitHubAppsClientTests.cs, Octokit.Tests.Integration/Clients/SearchClientTests.cs, Octokit.Tests.Integration/Helper.cs, Octokit.Tests.Integration/Reactive/Enterprise/ObservableEnterprisePreReceiveEnvironmentsClientTests.cs, Octokit.Tests.Integration/Reactive/ObservableReleaseClientTests.cs, Octokit.Tests/Clients/RepositoryBranchesClientTests.cs, Octokit.Tests/Clients/SearchClientTests.cs, Octokit/Authentication/BearerTokenAuthenticator.cs, Octokit/Models/Request/SearchLabelsRequest.cs, Octokit/Models/Response/Installation.cs, Octokit/Models/Response/InstallationPermissions.cs, Octokit/Models/Response/PullRequest.cs, Octokit/Models/Response/Verification.cs, ReleaseNotes.md, appveyor.yml, build.ps1, build.sh, build/Build.csproj
Sorry it's taken a while, we've had heaps of good stuff waiting for "just one more PR" to sneak in... I'm going to step up the release frequency going forward 😀
=> Release v0.30 - Where Have You Been All My Life?

docs/github-apps.md
=> Attempt to clarify GitHubApp docs

Octokit.Reactive/Clients/ObservableRepositoriesClient.cs, Octokit.Tests.Integration/Clients/CheckRunsClientTests.cs, Octokit.Tests.Integration/Clients/RepositoriesClientTests.cs, Octokit.Tests.Integration/Clients/RepositoryContentsClientTests.cs, Octokit.Tests.Integration/Clients/RepositoryHooksClientTests.cs, Octokit.Tests.Integration/Reactive/ObservableCheckRunsClientTests.cs, Octokit.Tests/Clients/CheckRunsClientTests.cs, Octokit.Tests/Clients/ProjectCardsClientTests.cs, Octokit.Tests/Clients/RepositoriesClientTests.cs, Octokit.Tests/Models/RepositoryTransferTest.cs, Octokit.Tests/Reactive/ObservableCheckRunsClientTests.cs, Octokit.Tests/Reactive/ObservableCheckSuitesClientTests.cs, Octokit.Tests/Reactive/ObservableRepositoriesClientTests.cs, Octokit/Helpers/Ensure.cs, Octokit/Models/Request/CheckRunUpdate.cs, Octokit/Models/Request/CheckSuiteTriggerRequest.cs, Octokit/Models/Request/NewCheckRun.cs, Octokit/Models/Request/NewCheckSuite.cs, Octokit/Models/Response/CheckRunOutputResponse.cs, Octokit/Models/Response/EventInfo.cs, ReleaseNotes.md
=> Release v0.31 - Check yo' self!

Octokit/Models/Request/CheckRunUpdate.cs, Octokit/Models/Request/NewCheckRun.cs
Hahaha https://github.com/tgstation/tgstation/pull/39291/checks?check_run_id=8701837
Hopefully this doesn't break any tests
=> Fixes check runs taking over 2017 years to complete

README.md
- Added badges for nuget
- Added 50 horse power
=> Adding nuget badges

docs/releases.md
=> update docs to include the await keyword

docs/github-apps.md, docs/issues.md
:walking_man: :walking_woman: **[Missing Persons - Walking in L.A.](https://www.youtube.com/watch?v=R_UpLtGEWoY)**
=> Spellcheck documentation.

Octokit.Tests.Integration/Clients/PullRequestsClientTests.cs, Octokit/Models/Response/PullRequest.cs
I noticed while trying to read labels off a PR that the model was missing it from the response.
https://developer.github.com/v3/pulls/#get-a-single-pull-request
=> add labels to pull request

Octokit.Tests.Integration/Clients/RepositoryBranchesClientTests.cs, Octokit.Tests.Integration/Helpers/OrganizationRepositoryWithTeamContext.cs, Octokit.Tests.Integration/Reactive/ObservableRepositoryBranchesClientTests.cs, Octokit.Tests/Clients/RepositoryBranchesClientTests.cs, Octokit.Tests/Reactive/ObservableRepositoryBranchesClientTests.cs, Octokit/Clients/RepositoryBranchesClient.cs, Octokit/Helpers/AcceptHeaders.cs, Octokit/Models/Request/BranchProtectionUpdate.cs, Octokit/Models/Response/BranchProtection.cs
Add `RequireApprovingReviewCount`setting to existing branch protection calls, as per [this blog post](https://developer.github.com/changes/2018-03-16-protected-branches-required-approving-reviews/)
=> Update Branch Protection to support RequiredApprovingReview preview

Octokit/Models/Response/Label.cs
Small change - I added Id to the Label model property.
Resolve #1941
=> Add Id field to Label model

Octokit.Reactive/Clients/IObservableMigrationsClient.cs, Octokit.Reactive/Clients/ObservableMigrationsClient.cs, Octokit.Tests.Integration/Clients/MigrationsClientTests.cs, Octokit.Tests/Clients/MigrationsClientTests.cs, Octokit.Tests/Reactive/ObservableMigrationsClientTests.cs, Octokit/Clients/IMigrationsClient.cs, Octokit/Clients/MigrationsClient.cs
=> Add pagination support to Migrations client

README.md
Since I updated my GitHub username a while back
=> Updated link to my ScriptCs.Octokit repo

Octokit.Reactive/Octokit.Reactive.csproj, Octokit/Octokit.csproj
=> add license metadata to package outputs

Octokit.Tests.Conventions/Octokit.Tests.Conventions.csproj, Octokit.Tests.Integration/Octokit.Tests.Integration.csproj, Octokit.Tests/Octokit.Tests.csproj
=> no need to build and run tests against net46

Octokit.Tests.Integration/Clients/MigrationsClientTests.cs, Octokit.Tests/Http/ApiInfoParserTests.cs, Octokit.Tests/Http/ApiInfoTests.cs, Octokit.Tests/Http/ConnectionTests.cs, Octokit.Tests/Http/JsonHttpPipelineTests.cs, Octokit.Tests/Http/RateLimitTests.cs, Octokit.Tests/Http/RedirectHandlerTests.cs, Octokit.Tests/Models/NewReferenceTests.cs, Octokit.Tests/Reactive/ObservableDeploymentStatusClientTests.cs
There's one unmarked test that seems to be deadlocking the CI build, but aside from that this PR should resolve all the feedback from the xUnit analyzers.
=> next set of tidy up of test warnings

Octokit.Tests.Integration/Clients/Enterprise/EnterpriseManagementConsoleClientTests.cs, Octokit.Tests.Integration/Helpers/GitHubEnterpriseManagementConsoleTestAttribute.cs
=> tidy up new tests

Octokit/Models/Request/SearchRepositoriesRequest.cs
Related to #2030 
If there is need to add more languages let me know and i could get working on that :)
=> add JupyterNotebook to Repository Search

Octokit.Reactive/Clients/IObservableOrganizationMembersClient.cs, Octokit.Reactive/Clients/ObservableOrganizationMembersClient.cs, Octokit.Tests.Integration/Clients/OrganizationMembersClientTests.cs, Octokit.Tests.Integration/Reactive/ObservableOrganizationMembersClientTests.cs, Octokit.Tests/Clients/OrganizationMembersClientTests.cs, Octokit.Tests/Reactive/ObservableOrganizationMembersClientTests.cs, Octokit/Clients/IOrganizationMembersClient.cs, Octokit/Clients/OrganizationMembersClient.cs, Octokit/Helpers/ApiUrls.cs, Octokit/Models/Request/OrganizationMembershipUpdate.cs, Octokit/Models/Response/OrganizationMembership.cs
Fixes octokit/octokit.net#1959
=> Add get/update/delete methods for organization memberships

build/Build.csproj
* Update to Cake.Frosting 0.36.0
=> (build) Update to Cake 0.36.0

Octokit/Models/Response/Repository.cs
=> add IsTemplate field repository response model

Octokit.Tests.Integration/Clients/IssueTimelineClientTests.cs, Octokit/Models/Response/TimelineEventInfo.cs
=> handle int32 overflow with IssueTimeline API

README.md
=> bump minimum versions in README

Octokit.Tests.Integration/Clients/CommitCommentReactionsClientTests.cs, Octokit/Models/Response/Reaction.cs
As per the [Reactions docs](https://developer.github.com/v3/reactions/#reaction-types), there's 2 reactions that are not available to ocktokit.net clients. They are added in this PR.
Let me know if there are any tests that need to be updated or added for this.
=> Add Rocket and Eyes emoji reactions

.vscode/tasks.json
Just a helper script when working locally
=> add format command for vscode

.github/workflows/publish.yml
This one goes out to @geoffreyhuntley and all the other hecklers
=> add publish on tag action to push releases to NuGet

.github/workflows/publish.yml
Similar changes to #2289 to support publish workflow
=> tidy up workflow to address new restrictions

Octokit/Models/Response/PullRequest.cs
=> Add Draft to MergeableState enum

Octokit.Tests.Integration/Clients/RepositoriesClientTests.cs, Octokit/Models/Request/NewRepository.cs, Octokit/Models/Request/RepositoryUpdate.cs, Octokit/Models/Response/Repository.cs
fixes #2415 
Also added Merge Options to New Repository object as they were missing.
=> Add AutoMerge and add MergeOptions to NewRepository object

Octokit/Models/Response/GitHubApp.cs
Fix typo in XML documentation for the Slug property.
=> feat: Fixes GitHubApp response object code docs typo

Octokit.Tests.Integration/Clients/PullRequestsClientTests.cs, Octokit/Models/Request/NewPullRequest.cs
=> New pull request from existing issue

README.md
Ref to https://github.com/octokit/octokit.net/releases/tag/v2.0.0
=> Update dotnet supported version in readme

docs/git-database.md
=> Add documentation on how to create a branch

.github/workflows/netcore.yml, .github/workflows/publish.yml
=> ci: revert 0d6b7c41 and 30fdeca1

docs/releases.md
Resolves #2618
----
* None code changes.
* Fix the sample code for "Get All" not working.
* Add the "Get Latest" section.
----
* N/A
----
=> Fix #2618 - Improve docs for the 'release' chapter

README.md
I was looking through the README recently and noticed this date was off. It's only been bumped [once](https://github.com/octokit/octokit.net/commit/7114bcb41ed3cf7a271b8bb5bb94c9199fc6b07b) in the past that I can see and it's time to update it again!
----
* The GitHub copyright date in the README was given as 2017.
* The GitHub copyright date in the README is given as 2023. 
* N/A
----
* N/A
----
=> Happy New Year!

Octokit/Models/Response/AccountType.cs
Resolves #2687
----
When retrieve any information for migrated repo where is information about user activity then octokit throws an error:
"Requested value 'Mannequin' was not found."
* 
There is no error anymore
* 
* 
----
* N/A
----
=> Added Mannequin account type for migrated repos

Octokit/GitHubClient.cs, Octokit/IGitHubClient.cs
Changed "Pacakges" to "Packages".
=> Fix Pacakges typo
